### ISSUE TITLE
modifications to QA summary page

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1002]
As the product owner
I would like to more efficiently view the QA summary page
So that I can more easily evaluate the overall QA status for a particular extraction script

Currently on the QA summary page (http://factotum.epa.gov/qa/extractionscript/52/summary) for an extraction script, many document records appear which do not have a QA note. 

Definition of Done:
1. 'Product' label should be removed
2.  Only include on QA summary page those documents which have a non-empty and non-null QA note.
3.  For each data document associated with the extraction script which has a non-null and non-empty QA note, the datadocument.title should be appear (no label of 'data document' is necessary, just indicate the document title)
  - datadocument.title should be a hyperlink to the data document page
   - Beneath the data document title, label 'QA note: note text note text note text'

**Comment by mwfrost** [comment]
The fact that documents are being listed without any QA notes suggests that `QANote` objects are being created when they shouldn't be.

@kdionisio Can you run `SELECT * FROM dashboard_qanotes; ` and tell me if the results are full of empty-string notes?
