### ISSUE TITLE
aggregate products in PUCs for bubble plot

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1003]
As the product owner,
I would like the representation of products within a PUC in all bubble plots to be consistent
So that data is not misinterpreted.

Definition of Done:
For the bubble plot displayed on the chemical landing page (http://factotum.epa.gov/dsstox/DTXSID6026296/), the two highest levels of the PUC (general category and product family) should display as their own bubbles, where the higher level PUCs are the aggregated product count from all lower level PUCs 

(same as how this is done in the bubble plot on the Dashboard page) (same as was requested in #866 for the Dashboard bubble plot)

**Comment by mwfrost** [comment]
I have some info-design issues with showing the nested hierarchy as two separate bubbles. Each lower level PUC is getting displayed twice this way. It might be a good idea for us to start investigating alternatives, like a treemap. https://datavizcatalogue.com/methods/treemap.html

**Comment by mwfrost** [comment]
Another alternative: https://observablehq.com/@d3/circle-packing

**Comment by kdionisio** [comment]
replaced by #1014
