### ISSUE TITLE
list of PUCs on chemical landing page

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1004]
As a Factotum user
I would like to view the list of PUCs containing the chemical of interest more efficiently
So that I can interpret data at a glance.

Currently the display of PUCs containing the chemical of interest includes a lot of repeated text and repeated color legends, resulting in the list taking up a lot of space.
http://factotum.epa.gov/dsstox/DTXSID6026296/

Definition of Done:
1. Represent the list of PUCs containing the chemical as a 'tree', to reduce repetitive text (e.g. the level 1/general category text only needs to be listed once) and visually represent the hierarchy of the PUCs
2. Building on the above, the color legend should be represented only once, since there is only one color for each high level/general category
3. Default view should be a list of the general categories containing the chemical; user can then drill down into the general categories to see the more refined levels of the PUC containing the chemical

**Comment by debboutr** [comment]
@kdionisio right now we have a **link** to the detail page of PUCs listed. If there is a single PUC that is level 3, let's say `Personal care -- hair styling and care -- shampoo`, would we want there to be a **link** to only that PUC as you drill down in the tree? Or at the level 1 and 2 would we want there to also be a link to those detail pages as well? It seems by the way we accumulate in level one PUCs that we would want all three.

**Comment by kdionisio** [comment]
@debboutr Agreed I think we still want all three!
