### ISSUE TITLE
edit text on CO data group page

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1008]
As a Factotum data curator
I want to be clear on which id needs to be included in the clean composition file upload
So that I can upload the correct data.

On the data group detail page for group type Composition (http://factotum.epa.gov/datagroup/60/), there is text in the 'upload clean composition data' section which states 'The uploaded csv must have....' and then |id| ...
It is unclear which 'id' is needed in the first column, so the labeling needs to be refined.

Definition of done: 
Text in the 'upload clean composition data' section of the data group detail page for group type composition should read 'The uploaded csv must have...' and then | ExtractedChemical_id| ...

**Comment by mwfrost** [comment]
Note that there is no real field called "ExtractedChemicalID". The reason we just called this the "id" field is that the primary key is a reference to the RawChem table. The ExtractedChemical model does not have its own primary key. It just uses `rawchem_ptr_id` to link to the `id` column in the RawChem table.

**Comment by kdionisio** [comment]
That is fine, I am calling it ExtractedChemicalID because this is the label of the appropriate column in the raw composition download that the user will be working off of - so then it should be clear to the user which column from their raw composition download needs to be used on the cleaned composition data upload
