### ISSUE TITLE
Remove Elastic 2.4.6 from docker-compose and associate files

### ISSUE THREAD

**Issue by dmlyons2** [HumanExposure/factotum#1046]
## Describe the ideal solution or feature request
A clear and concise description of what the customer wants to happen.

## Difficulty, impact, and usage score
| Technical difficulty | User goals | Usage frequency |
|--------------------| --------------------| --------------------|
| ie. Small, medium, large (filled out after submission) |  ie. How important is this to the user, what the user wants to accomplish | ie. Daily, weekly, monthly |

## How does this tie into our current product?
Describe whether this request is related to an existing workflow, feature, or otherwise something in the product today. Or, does this open us up to new markets and innovative ideas?

## Who asked for this?
Add more on who asked for this, ie. company, person, how much they pay us, what their tier is, are they a strategic account, etc.

**Comment by debboutr** [comment]
These files may be lingering from `haystack`

`https://github.com/HumanExposure/factotum/tree/dev/templates/search/indexes/dashboard`
