### ISSUE TITLE
remove unnecessary chemical curation entries

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1061]
As a Factotum user
I only want to view data groups in the chemical curation list that I actually need to curate
So that I can more efficiently find data groups which need to be worked on

Definition of Done:
The drop down menu on: 
http://factotum.epa.gov/chemical_curation/
for the 'Download uncurated chemicals for a Data Group' should not include data groups that have 0 records to curate.

**Comment by debboutr** [comment]
@kdionisio this ticket got done with issue #1107. You should be able to check it on prod right now and see that it's kosher.

**Comment by kdionisio** [comment]
@debboutr   yes great, thanks!!
