### ISSUE TITLE
link to documents with CP keyword set from chemical page

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1070]
As a Factotum user
I want to be able to link to all documents which have a particular list presence keyword set assigned
So that I can investigate the data points of interest for my analysis

Definition of done:
- On the chemical landing page (http://factotum.epa.gov/chemical/DTXSID7021360/), 
in the list of CP keyword sets at the bottom of the page, clicking on the number of CP keyword sets which contain the chemical of interest should bring you to a page (OR new table should appear on the bottom of the /chemical/ page) listing all documents (by dashboard_datadocument.title) which are assigned to that CP keyword set, and contain the chemical of interest.
- in the table listing the documents which are assigned to the keyword set of interest, the document titles should be displayed as a hyperlink which takes you to that data document page (e.g. http://factotum.epa.gov/datadocument/1370045/)
so you can see which document is linked to that keyword set
- implement document index table with data tables using ajax calls, only column in table at this point will be the document title, represented as a hyperlink to the data document page

**Comment by debboutr** [comment]
@kdionisio Tad and I have worked through the majority of this ticket and are now looking at it with prod data and noticed something interesting. We are displaying a count of the number of chemicals that have the same set of tags, but each chemical has to have been linked to the given `dsstox` item. We have now set up a query to load the table with documents that all hold chemicals that have the same set of tags and have noticed there can be quite a few more that aren't linked to a `dsstox`. Does this seem okay to keep it this way? Or should we filter the documents to be just ones that have chemicals which are linked to the `dsstox`? Hope this makes sense.
