### ISSUE TITLE
accurate hit count on search results

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1075]
Hit count on search results is not correct

Definition of Done
Hit count for search results should be accurate

**Comment by debboutr** [comment]
might be important to consider the state of our seed data here w/ `ProductDocument` associations. In production, we are going under the assumption that all Products will be related to Documents, where in seed data this is not true. This may not be a bad thing, but based on how products are going to be created and curated, there would always be a document first.
