### ISSUE TITLE
Update to D3.js

### ISSUE THREAD

**Issue by dmlyons2** [HumanExposure/factotum#1097]
The three charts above the bubble plot are all written in NVD3, which is D3 with training wheels, and uses an old version of D3. Update these three charts to D3 and remove NVD3 from the application.

**Comment by mwfrost** [comment]
This could be an opportunity to turn the all-blue bar charts into stacked bar charts that disaggregate the documents by document type (Composition, Functional Use, etc).

**Comment by kdionisio** [comment]
replaced by #1133
