### ISSUE TITLE
link to chemical summary page from search results page

### ISSUE THREAD

**Issue by dmlyons2** [HumanExposure/factotum#1099]
As a Factotum user,
I want to easily link to relevant chemical summary pages
If I search on a chemical name

Definition of Done:
- If a user searches on a term that is a chemical name, user should be able to link directly to relevant chemical summary pages (e.g. http://factotum.epa.gov/chemical/DTXSID9020663/) from the search results page.
- 'Relevant' chemical summary pages are defined as those 'similar to' or 'containing' the search term (e.g., if user searches for 'paraben', should be able to link to any chemical summary page where true chemical name contains 'paraben' - e.g. ethyl paraben, methyl paraben, etc)

**Comment by mwfrost** [comment]
Fang, 
1. I think the true/raw CAS should also be displayed. 
2. We have not discussed any facets for the chemicals, and I cannot think of any attribute that would work for faceting.

**Comment by fang-yan-csra** [comment]
Thanks Matt. The true/raw CAS will be displayed as highlight in the detailed area if the search hit those fields.
