### ISSUE TITLE
What do we search for?

### ISSUE THREAD

**Issue by dmlyons2** [HumanExposure/factotum#1100]
As an application admin
I would like data about what users are searching for 
So that I can effectively support search configuration

Information collected:
- search string
- user or null
- date/time
- application (defaults to factotum but could include other apps in the future)

I do not want this in the same database as prod_factotum, it will go into a new database called prod_search (or something similar).[ Django Multiple Databases](https://docs.djangoproject.com/en/2.2/topics/db/multi-db/)

Def of Done: 

- A new schema that is collecting search criteria mentioned above on the production factotum application.

- Search chars stored will be 255 chars or less.

**Comment by mcovalt** [comment]
There is no maximum search string length at the moment. Should we implement one now that we are storing them? If so, what should the character limit be?

**Comment by dmlyons2** [comment]
255 chars for the limit
