### ISSUE TITLE
key error

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1131]
When uploading extracted text data for  a CO data group (http://factotum.epa.gov/datagroup/506/), some extracted text csvs give errors on upload (see error below). However, the data still appears to have been uploaded.

Key Error at /datagroup/506/
'data_document_id'
Request Method: POST

Two example extracted text upload files which resulted in the error, but yet data still appeared to have been uploaded:
[https://app.zenhub.com/files/99837877/53aad58c-af32-404e-ac31-0aaddf9c88cf/download](https://app.zenhub.com/files/99837877/53aad58c-af32-404e-ac31-0aaddf9c88cf/download)

Definition of Done:
Identify cause of error and resolve; identify if data needs to be reloaded

**Comment by dmlyons2** [comment]
@zachmunzenrider could not replicate
