### ISSUE TITLE
delete product bug

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1132]
When on a /product/ page, user attempts to use the trash can icon in the upper right to delete the product. User sees error:

FieldError at /product_curation/
Cannot resolve keyword 'data_source' into field. Choices are: brand_name, color, created_at, datadocument.....etc etc

However the product does in fact appear to have been deleted.

Definition of Done:
- Delete product button does not give error
- when product is deleted user is redirected to the associated data document page with a message indicating the product has been deleted

**Comment by debboutr** [comment]
It seems as though the `/product_curation/` view may no longer be needed? Should I remove the link to this view in the nav bar as well? Data Curation --> Product Curation. Or does that need to be brought back to a working state?

**Comment by kdionisio** [comment]
@debboutr correct, we do not need the /product_curation/view any more
