### ISSUE TITLE
product page - fill screen

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1151]
As a user of Factotum
I would like the data/information on the /product/ page to fill the screen width
So that the data is easier to interpret and more visually pleasing

e.g., see here, where data does not fill width of screen: http://factotum.epa.gov/product/228937/

Definition of Done:
Reformat /product/ page so that data fills width of screen

**Comment by mwfrost** [comment]
Kathie,
Is this going to be an ongoing overhaul? For example, will this page need to be redesigned as full-width?
factotum.epa.gov/puc/185/

If so, we should maybe change our default bootstrap container from `container` to `container-fluid`

**Comment by kdionisio** [comment]
@mwfrost 
hmmmm good question...I don't know?? I would imagine yes, that we will want all pages to be full width, particularly the /puc/ and /chemical/ pages as well since those will be some of our 'public' pages. Is there any reason to not make them all full width?

**Comment by mwfrost** [comment]
Only the most content-dense websites run the content all the way to the edges of the browser window. The data document and product detail pages might fit that description, with their combination of sidebars and tables. 

Generally, though, margins are good. This GitHub page is a nice example of how margins help organize content and make the view more page-like. I think the problem with the Product page was driven more by the combination of monitor and zoom than by the layout.

**Comment by mwfrost** [comment]
For comparison:

<img width="1279" alt="sc_2019116_54312_521" src="https://user-images.githubusercontent.com/201835/68303345-86fbea80-0058-11ea-81b2-863c5941ce1e.png">
<img width="1280" alt="sc_2019116_54338_134" src="https://user-images.githubusercontent.com/201835/68303346-86fbea80-0058-11ea-8a4b-17f766febac1.png">

**Comment by zachmunzenrider** [comment]
Kathie - I think that Matt's branch is doing what you want it to do, but I just wanted to double-check that this is the case. As you can see from this screenshot, the Product page is now taking up the full width of the browser, with no appreciable margin on either side of the page content. Is this what you're looking for?

![image.png](https://images.zenhubusercontent.com/5be47c474f4473195308604f/016f4a1d-fd72-4b36-bae4-bf9ed1a6b6c2)

**Comment by kdionisio** [comment]
Yes, that's fine, thank you! And to be clear, just looking at Matt's previous messages - I'm fine with having some margin on the edges of the page, but the content on that product page seemed to be very condensed to the center of the page with excessive margins on the sides. Thanks!

**Comment by zachmunzenrider** [comment]
Great, thanks for the clarification! Based on this, I've approved the full-width approach that Matt used for this ticket.
