### ISSUE TITLE
Large File Upload and Processing

### ISSUE THREAD

**Issue by dmlyons2** [HumanExposure/factotum#1182]
When large files are uploaded and/or there is SQL intensive processing going on in the upload the application with timeout causing errors.   

Modify one of the current file upload and processing workflows to provide feedback on what is going on in the background. For example: once you upload a file you would get some messaging like
1. "Uploading File" with a progress bar
2. "Checking file format" with a progress bar
3. "Processing file" with a progress bar

This ticket is to change one of the file upload and processing workflows but it will be requested on nearly all in the future.

Definition of Done:  
1. Modify on of the file upload and processing workflows
2. Provide user feedback during the upload, check, and processing. The example stated progress bar but it is at the discretion of the dev to determine how the feedback is provided.
3. Consider that the work done in this ticket will become a pattern for future upload workflows and likely go back and apply to previously completed workflows.

**Comment by mcovalt** [comment]
The quickest means-to-an-end here seems to be storing the job status [in the session](https://docs.djangoproject.com/en/2.2/topics/http/sessions/). The job status can be updated as the processing job progresses. A new view can be made that uses the  `GET`er's session ID to return a payload containing the job status.

More tooling would have to be made to prevent a user from making multiple jobs. Using a global queue would make a lot of sense if we wish to control the number of concurrent jobs.
