### ISSUE TITLE
upload clean composition data bug

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1195]
When attempting to upload clean composition data, user is getting an error that the 'script_id field is required' However, this field is not listed as one of the required fields for the clean composition data template. In addition, the cleaning script is selected as a drop down selection prior to uploading the clean composition data, so a script_id should not be required in the upload (the script_id should be obtained based on the drop down menu option selected in the composition upload section:
http://factotum.epa.gov/datagroup/538/

Definition of Done:
Clean composition upload is successful.
![clean_comp_upload_bug_11_7_2019.PNG](https://images.zenhubusercontent.com/5be1bc3045b0290c78fb7cad/d7d0a94d-253e-4f68-8229-e80fcedd3ea3)

**Comment by l-koval** [comment]
attempted upload file:
[clean_comp_file.zip](https://github.com/HumanExposure/factotum/files/3824556/clean_comp_file.zip)
