### ISSUE TITLE
bug - error when uploading register records .csv for a data group

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#120]
Additional note: it was discovered that the bug detailed below comes from the data group name being too long. Ticket should now include instituting a check for length of the data group name in the code. Should there also/instead be a limit set on length of the data group name when the data group name is entered in the web form, when the data group is 1st created?

#########
When uploading the register records .csv file for a data group, I encountered the following error:

![image](https://user-images.githubusercontent.com/16561576/35825799-f22242da-0a84-11e8-980d-b3513ae4b0c0.png)

Though the above error appeared, the upload of the register records .csv did complete successfully (as in the records were actually registered in factotum, even though I received the error - so perhaps whatever caused the error occurred *after* the records were registered?). 

The error occurred within the "Sun Products Corporation-Ingredient Disclosure" data source, for the "Sun Products Corporation-Ingredient Disclosure 1" data group. I can send the actual register records .csv which was used during the upload if that is helpful.

Note that although the records appear to be registered when I look at the data group within the application, the application gives me the following error when I try to upload the data documents associated with the registered records:
![image](https://user-images.githubusercontent.com/16561576/35826189-048de50e-0a86-11e8-8850-50f01ec2de83.png)

**Comment by kdionisio** [comment]
Thank you @debboutr! So if I shorten the name of the data group I should be good? I can delete the current data group and redo it using a shorter name.

**Comment by debboutr** [comment]
you'll want to delete all of the datadocuments that were created too, but yes that'll work for now, we'll have to handle that error better in the code, so nothing is stored until we know that the length of that checks out first

**Comment by kdionisio** [comment]
resolved
