### ISSUE TITLE
remove fields from CP doc view

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1208]
As the factotum product owner
I would like to remove fields from the CP data document page
Because visibility of these fields is no longer needed

Example page: http://factotum.epa.gov/datadocument/1373628/

Definition of Done:
On /datadocument/ page for CP group type,
- Remove 'cat code', 'CPCat cassette', 'ACToR snaid' and 'CPCat source' fields from extracted text box on the left panel 
- Remove above 4 fields from the data entry pop-up that appears when you select the 'edit' button in the extracted text box on the left panel
- Change 'Doc date' label to 'Document date' and remove underline

**Comment by michael-barbour** [comment]
The first two definitions of done I have complete, but I'm having trouble finding what you mean for the third.

>Change 'Doc date' label to 'Document date' and remove underline

I can't find anywhere on the page that says 'Doc Date' or any underlined text.

![Modal](https://user-images.githubusercontent.com/22226925/70823333-9e439b80-1dad-11ea-9541-85c93413a623.png)
![Sidebar](https://user-images.githubusercontent.com/22226925/70823334-9e439b80-1dad-11ea-8416-9164d997c340.png)

**Comment by kdionisio** [comment]
*Note 3rd bullet under definition of done appears to have already been completed in a previous ticket
