### ISSUE TITLE
remove unnecessary fields from data entry view

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1211]
As a factotum data curator
I want to remove fields from the initial data entry for extracted text of CP documents
 because the fields are not relevant for CP documents

Currently, it seems that the prod name and rev num fields appear in the web form pop up which appears when a user initially enters extracted text for a CP data document. It seems the fields do not appear when the user later goes to edit previously entered extracted text.

Example page: http://factotum.epa.gov/datadocument/1400346/

Definition of Done:
- For group type CP, when user **initially** adds extracted text (via the pop up web form accessed by the edit button in the extracted text left panel box on the /datadocument/ page)
  - only the document date field should appear
  - field should be labeled as 'Document date:' rather than 'Doc date:'

**Comment by michael-barbour** [comment]
This issue seems like it should be merged with #1208

They both deal with the ExtractedText form for CP documents and can be resolved at the same time by merging and simplifying the forms.
