### ISSUE TITLE
remove add product functionality for documents of type HH

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1214]
***Combine this ticket with #1209?***
Both tickets are requesting the same change just on different data group types

As the product owner,
I want to remove the 'add product' functionality for HH documents
Because products are not associated with documents of type HH

Example link: http://factotum.epa.gov/datadocument/1367257/

Definition of Done:
For /datadocument/ pages of group type HH,
remove the 'linked products' label and the 'add product' button in the left panel of the page

**Comment by dmlyons2** [comment]
Combine this ticket with #1209?
