### ISSUE TITLE
server side pagination and search (8 pts)

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#122]
Please switch from client side pagination and search to server side pagination and search. The current client side pagination and search is not working well for the large amount of data we are displaying.

**Comment by mwfrost** [comment]
Which tables are the highest priority for this? There's a fair amount of customization required to deliver the results, so I'd like to start with the views that are currently slowing you down the most.

**Comment by kdionisio** [comment]
@mwfrost I would prioritize the table of products that appears when you click on the 'product curation' link in the nav bar. This is the table that is being used the most right now by our data curator.

**Comment by kdionisio** [comment]
Modifying ticket to be a request for server side pagination on the data group detail page only. Server side pagination for additional pages/tables will be addressed in future issues.

**Comment by mwfrost** [comment]
Can someone reviewing this look into whether the datatables javascript is being applied to the table object? I have turned off datatables pagination and searching and csv export, but shouldn't there still be some sorting widgets?
