### ISSUE TITLE
product attributes - functionality to assign attributes to product (8 pts)

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#124]
**Hold on this ticket until #410 is complete so that this ticket can build off of #410**
**dependent on completion of #123 (done) and #410  **

As Karyn the curator
I want to be able to assign attributes to each product
So that I can maintain, access, and sort on pieces of data which are relevant for exposure modeling

In ticket #123, the product attributes data model was created. This ticket is to add functionality to assign product attributes at the same time a curator is assigning the product category.

Anytime a user has the option of assigning a PUC, they should also have the option of assigning product attributes. Because the available attributes for any given PUC are limited to a specific subset of all attributes, after user selects a PUC, user should see all product attributes which are allowed for that PUC. User should have ability to select 0 - many of the allowed product attributes for each product.

If user changes the PUC before it has been assigned, view updates and allowed attributes for the new PUC are displayed. 

If user changes a previously assigned PUC, the previously assigned attributes for the product are disassociated from the product, and user must select new attributes based on those allowed for the new PUC assignment.

Definition of Done:
Ability to select 0 - many product attributes for a product when assigning a PUC, where product attributes selected can only be from the list of allowed product attributes for that PUC.

Test:

**Comment by kdionisio** [comment]
**Note that we have since created a separate 'module' for the 'assign PUC' functionality. The above ability to assign attributes to a product should exist within this 'assign PUC' module.

**Comment by debboutr** [comment]
@kdionisio I was just reviewing this ticket, but am wondering how the attribute data will be entered to then be associated w/ a given PUC? Is there a list of attributes that you have already entered through admin or is there another way that we are anticipating to fill out records for the model that we had built in ticket #123 ? _Sorry if this has been answered somewhere already_

**Comment by kdionisio** [comment]
As discussed in stand-up on 10/17/18, for simplicity, allow user to select attributes on product view page rather than on PUC selection page. User should see both attributes that have been assigned to the product, as well as all 'allowed' attributes for the PUC that the product is assigned to.
