### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1242]
In the http://factotum.epa.gov/datagroup/406/  data group, there appears to be a mismatch in the URL leading to the pdf file of the data document. 

If the file icon from the /datagroup/ page is selected (to bring user directly to the data document), user is directed to this URL, which is invalid:
http://factotum.epa.gov/media/7ba1089f-4894-4b2b-82b6-bf8042693a06/pdf/document_1373534.2.pdf

If instead, the user goes to the /datadocument/ page and selects the file icon on the /datadocument/ page (to go to the data document), user is directed to this URL, which is valid:
http://factotum.epa.gov/media/7ba1089f-4894-4b2b-82b6-bf8042693a06/pdf/document_1373534.pdf

This appending of a period with number(s) appears to be happening for each file in /datagroup/406/. Possibly because periods were included in the original file name uploaded when registering records? (e.g. Exposure of Children Table 8.10.pdf)

Definition of Done:
Links to file/data document from /datagroup/406/ page link to valid URL

**Comment by dmlyons2** [comment]
@dmlyons2 get a screenshot of this folder

**Comment by kdionisio** [comment]
Will this issue also address the file not found error when attempting to view the data document from this page? 
http://factotum.epa.gov/datadocument/321522/
Or is this a different error that needs to be ticketed separately?

**Comment by kdionisio** [comment]
Here is another example of a document with the same error as described in the original ticket: http://factotum.epa.gov/datagroup/623/
