### ISSUE TITLE
data group edit page

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1244]
There are currently problems with saving edits on the data group 'edit' page: 
http://factotum.epa.gov/datagroup/edit/583/
(accessed from the /datagroup/ page).

problems:
- title states 'Create New Data Group for Data Source "" '
- when attempting to save edits, user sees error that 'group type is a required field' however group type is populated (in fact, group type is 'locked down' or in a sense auto populated by default)

Definition of Done:
1. Page title states 'Create new data group for data source XXXX' where XXX = name of the data source
2. Save edits button is functional without an error

**Comment by mwfrost** [comment]
The problem appears to be that the `data_group_update` view uses the `data_group/datagroup_form.html` template, but that template has been modified to serve the `data_group_create` view, and it doesn't work well with the update view.

https://github.com/HumanExposure/factotum/blob/f374ffbea8f5c2179e76317310f07e23126927f3/dashboard/views/data_group.py#L258
