### ISSUE TITLE
view documents linked to a chemical

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1264]
As a Factotum user
I want to link directly to the documents associated with a chemical of interest
So that I can easily access data of interest

On /chemical/ page, there currently exists a table of documents, however this table only includes documents associated with the CP keywords

http://factotum.epa.gov/chemical/DTXSID7021360/

Definition of Done:
- on /chemical/ page, include table (at bottom of page) which lists *all* documents associated with the DTXSID of the chemical page user is on (this may include CP, CO, HH, etc documents).
- table should include columns for:
  - dashboard_datadocument.title (column titled 'Document')
  - dashboard_grouptype.title (column titled 'Data type')
- document.title should be a hyperlink to the appropriate /datadocument/ page
- current table listing only documents associated with CP keyword sets should be removed
- implementation of new table should be consistent with formatting and appearance of table on /datagroup/ page

**Comment by debboutr** [comment]
@kdionisio did you want the Keyword Sets to be removed in this ticket as well, I get that we want to add functionality to the table, but should there still be the grouped keyword sets that we had? thanks
