### ISSUE TITLE
figure - DTXSID by data group type

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1278]
As a Factotum user
I would like to view a plot of number of DTXSID by data group type
So that I can easily assess the scope of chemicals by data type included in the database

Definition of Done:
On home page, view plot of number of unique DTXSID by data group type
- Since each DTXSID may be associated with >1 data group type, this could be represented by a Venn diagram, but open to a more exciting figure as well
- Figure is visible on both logged in and public version of Factotum

**Comment by mwfrost** [comment]
Just for reference:
```
RawChem.objects.filter(dsstox__isnull=False).values('dsstox__sid','extracted_text__data_document__data_group__group_type__title').annotate(Count('id'))   
```

**Comment by mwfrost** [comment]
There are seven Group Type categories, which means there are theoretically 2^7=128 possible combinations of Group Types to which any SID can belong. That is _possible_ to show in a Venn Diagram, but the results look like this:
http://moebio.com/research/sevensets/

Amazing, but not very useful for us. 

A combination matrix is probably superior. Here is a fancy example: https://bost.ocks.org/mike/miserables/

**Comment by kdionisio** [comment]
@mwfrost question on your comment above. That Venn diagram is very cool :-). But I see how it may not be useful. Unless the reality of our data is that we have many fewer than the 128 possible combinations? That is unclear at this point. Also possible that we could/may want to limit the Venn diagram to only a smaller number of specific group types (probably the three 'main' group types, e.g. LP, FU, CO). Other group types are much smaller and more used for a specific use case, thus not a 'core' part of the database.

In the combination matrix, what would be along the x/y axes? Group type, or chemical? I'm not visualizing how this diagram would work to satisfy the request...if the axes are chemical, then the axes may be far too large to be useful (since we have >25,000 unique DTXSIDs).
