### ISSUE TITLE
synced navigation of bubble plot/table

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1282]
As a user
I want to more easily navigate the PUCs in the bubble plot
So that I can easily browse data

Definition of Done:
On home page and on /chemical/ page,
- Clicking on a PUC in the PUC table should automatically zoom the bubble plot in/out appropriately. 
- Clicking on a bubble in the bubble plot should automatically expand/condense the PUC table appropriately
- Applicable to both logged in and public versions of both pages

**Comment by mwfrost** [comment]
Before this ticket, the front page takes 8622.61ms to completely load with the production data installed.

**Comment by mwfrost** [comment]
With seed data, loading `http://127.0.0.1:8000/dl_pucs_json/?kind=FO` takes 58 ms
