### ISSUE TITLE
refine search results - chemical search

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1289]
As a user, 
I want to see the most appropriate search results listed first
So that it is easier to find the data I am looking for

Definition of Done:
If user searches for a chemical, search results should be returned in the following order:
- Exact match on dashboard_dsstoxlookup.sid, true_cas, or true_chemname
- Exact match on synonym to sid, cas, or chemname
- Exact match on dashboard_rawcas or raw_chem_name
- Exact match on synonym to rawcas or raw_chem_name
- Close match to sid, true_cas, true_chemname, rawcas or raw_chem_name
- Match in any other field being searched on (i.e. search term matches term in 'description' field)

**Comment by mwfrost** [comment]
<img width="763" alt="Screen Shot 2019-12-19 at 8 44 08 AM" src="https://user-images.githubusercontent.com/201835/71191890-21487400-223c-11ea-88ce-4547f7621bf2.png">

@kdionisio 
Kathie,
Does this screen shot accurately reflect the failure that we are trying to correct in this ticket?
Result 1 has "water" in the document title, but it has no True Chemical. Results 2 and 3 both have water (or a synonym) in a chemical name field, but no "water" in the document title. The presence of "water" in the chemical name field should be enough to score results 2 and 3 higher than result 1?

**Comment by kdionisio** [comment]
@mwfrost Yes the above is good, thanks!
