### ISSUE TITLE
clean up null/blank strings in DB

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1298]
As the Factotum product owner
I want to clean up nulls and blank strings in the database
So that I do not have nulls and blank strings interfering with data processing

Definition of Done:
Use of Null vs. blank string in all data fields should be consistent (e.g. should not have both null and blank strings in different records for the same data field)

**Comment by michael-barbour** [comment]
Ricks comments on this ticket are still very applicable.  I'm posting a reference to them here.

https://github.com/HumanExposure/factotum/issues/1260#issuecomment-566798007
https://github.com/HumanExposure/factotum/issues/1260#issuecomment-568091724
