### ISSUE TITLE
revise chemicals API

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1316]
As the product owner
I would like to update/revise the Chemicals API
so that it better conforms with RESTful API standards

Definition of Done:
For the Chemicals API, change to the following. Bulleted items are variables to return. Please label variables in the API as they are labeled below. Also, alongside each variable is the text that should be included in the API as the definition/documentation for each variable returned.

chemicalsList (should return unique list of all DTXSID in the database)
- DTXSID  (dashboard_dsstoxlookup.sid):  The DSSTox Substance Identifier, a unique identifier associated with a chemical substance.
- Preferred name (dashboard_dsstoxlookup.true_chemname): Preferred name for the chemical substance.
- Preferred CAS (dashboard_dsstoxlookup.true_cas): Preferred CAS number for the chemical substance.

chemicalsRead (for a specific DTXSID)

Main heading documentation for the Chemicals API should be:
Service providing a list of all registered chemical substances linked to data in ChemExpoDB. All chemical data in ChemExpoDB is linked by the DTXSID, or the unique structure based identifier for the chemical substance. Service provides the DTXSID, preferred chemical name, and preferred CAS.

**Comment by mcovalt** [comment]
@kdionisio Here is the translation I'm using to convert the field names as listed to the JSON response field names. This follows expected conventions for programmers accessing the response:

* DTXSID → `id`
* Preferred name → `name`
* Preferred CAS → `cas`

The API documentation will still respect the human readable field names and descriptions.
