### ISSUE TITLE
create documents API

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1319]
As the product owner
I would like to create a documents API
so that users of other FActotum APIs are able to obtain meta data on the document

Definition of Done:
Create a documents API per previous API template. Bulleted items are variables to return. Please label variables in the API as they are labeled below. Also, alongside each variable is the text that should be included in the API as the definition/documentation for each variable returned.

documentsList (should return unique list of all documents in the database)
- Document ID (dashboard_datadocument.id): Unique numeric identifier for the original data document providing data to ChemExpoDB. 
- Title (dashboard_datadocument.title): Title of the document.
- Subtitle (dashboard_datadocument.subtitle): Subtitle for the document. May also be the heading/caption for the table from which data was extracted.
- Organization (dashboard_datadocument.organization): The organization which published the document. If the document is a peer-reviewed journal article, the name of the journal.
- Date (dashboard_extractedtext.doc_date): Publication date for the document.
- Data type (dashboard_grouptype.title): Type of data provided by the document, e.g. 'Composition' indicates the document provides data on chemical composition of a consumer product.
- Document type (dashboard_documenttype.title): Standardized description of the type of document (e.g. Safety Data Sheet (SDS), product label, journal article, government report).
- URL (**Note this is not the URL field from the datadocument model, but rather the factotum.epa.gov/ URL which the user would go to if they wanted to view/download the document itself): Link to a locally stored copy of the document. 
- Notes (dashboard_datadocument.note): General notes about the data document, written by ChemExpoDB data curators.
- Product ID (dashboard_products.id; *Note may be >1 per document): Unique numeric identifier for products associated with the original data document. May be >1 product associated with each document. See the Products API for additional information on the product.
- Component (dashboard_rawchem.component): Subcategory grouping chemical information on the document (may or may not be populated). Used when the document provides information on chemical make-up of multiple components or portions of a product (e.g. a hair care set (product) which contains a bottle of shampoo (component 1) and bottle of body wash (component 2))
- DTXSID (dashboard_dsstoxlookup.sid, *Note may be >1 per document, and is associated with a specific component): The DSSTox Substance Identifier for each chemical included on the document May be >1 per document. See the chemicals API for additional information on the chemical substance.
- Weight fraction - lower (dashboard_extractedchemical.lower_wf_analysis): Lower bound of weight fraction for the chemical substance in the product, if provided on the document. If weight fraction is provided as a range, lower and upper values are populated. Values range from 0-1.
- Weight fraction - central (dashboard_extractedchemical.central_wf_analysis): Central value for weight fraction for the chemical substance in the product, if provided on the document. If weight fraction is provided as a point estimate, the central value is populated. Values range from 0-1.
- Weight fraction - upper (dashboard_extractedchemical.upper_wf_analysis): Upper bound of weight fraction for the chemical substance in the product, if provided on the document. If weight fraction is provided as a range, lower and upper values are populated. Values range from 0-1.
- Ingredient rank (dashboard_extractedchemical.ingredient_rank): Rank of the chemical in the ingredient list or document.

documentsRead (for a specific Document ID)

Main heading documentation for the documents API should be:
Service providing a list of all documents in ChemExpoDB, along with meta data describing the document. Service also provides the actual data points found in, and extracted from, the document. e.g., chemicals and their weight fractions may be included for composition documents.

**Comment by mwfrost** [comment]
@kdionisio 
Should this response include RawChem records that have no corresponding ExtractedText data or no curated DTXSID?
If the record has no Component, has not been curated, and has no ExtractedText data, it looks like this:
```
{
component: null,
sid: null,
lower_wf_analysis: null,
central_wf_analysis: null,
upper_wf_analysis: null,
ingredient_rank: null
},
```

**Comment by kdionisio** [comment]
@mwfrost  But it would still have the document ID, document title, etc, correct? If so then yes, these records should still be included in the response.
