### ISSUE TITLE
change relationship between raw chem and functional use

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1322]
As a Factotum data curator
I need to load data where a single chemical record is associated with multiple functional uses
So that I can maintain relationships found in the data document.

For the FU group type, every chemical record may be associated with >=1 functional use. Currently, the data model only allows for uploading 1 functional use per chemical record.

Definition of Done:
For the FU group type, allow for each chemical record (i.e. each dashboard_rawchem record) to be associated with >=1 dashboard_extractedfunctionaluse record.
- Data model must allow for the above
- Extracted data upload on /datagroup/ page for FU group type must allow for the above
- Extracted text templates available on /datagroup/ page for FU group type must be appropriate for new data relationship

**Comment by mwfrost** [comment]
This diagram shows the existing relationships and (in red) the new relationship between RawChem and ExtractedFunctionalUse.
![erd_before.png](https://images.zenhubusercontent.com/5be34a63f724c70c7221c972/22f07b33-0661-414e-9ba0-bd0fa516338e)
