### ISSUE TITLE
presentation of LP keywords on /chemical/ page

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1338]
As the product owner
I would like to improve the presentation of list presence data on the chemical summary page
So that I can improve the user experience

On the chemical summary page, the presentation of list presence keyword sets which contain the chemical is clunky.
  - takes up a lot of white space on the page to show minimal data
 

![image.png](https://images.zenhubusercontent.com/5be1bc3045b0290c78fb7cad/4f025ca7-45f9-4525-8f6f-7485af3081ba)

Definition of Done:
Implement improved presentation of list presence keyword sets on /chemical/ page such that page space is used more efficiently and user can see all keyword sets more easily. Should still include indication of the number of documents containing that keyword set but can be presented differently

**Comment by kdionisio** [comment]
**Also need a separate LP keyword - chemical summary page

**Comment by Sakshi-Handa** [comment]
No longer relevant. Table display is improved/compact. 
Additionally, #1921 set the default to minimize LP tags table on /chemical/ page.
