### ISSUE TITLE
Research and implement indexing scheme

### ISSUE THREAD

**Issue by mwfrost** [HumanExposure/factotum#134]
The search functionality (built in #104 ) depends on the elasticsearch engine's index. Keeping that index in sync with the data at production scale will present some challenges. When we first merge the search branch with production, we will need to sync the indexes manually with `python manage.py rebuild_index`. Then it will need to be an automated process.

Here are a few approaches to doing it:
http://django-haystack.readthedocs.io/en/v2.4.1/searchindex_api.html#keeping-the-index-fresh

**Comment by debboutr** [comment]
when running `rebuild_index` there seems to be an issue w/ the Product model's `brand_name` field which has `db_index=True` in it's arguments. Here's the error I get:
```
haystack.exceptions.SearchFieldError: The model 'None' combined with model_attr 'brand_name' returned None, but doesn't allow a default or null value.
```

**Comment by kdionisio** [comment]
moving to new elastic search
