### ISSUE TITLE
HP data type

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1347]
As a Factotum product owner
I want the ability to store a specific list of HP data types
So that users are restricted to choosing from a specific set of HP data types

A HP data type defines the type of data provided in that document. e.g., a HP document may provide information on 'mass' of a product used, 'frequency' of use of the product, 'duration' of use of the product. Mass, frequency, duration are all options for HP data type.

The HP data types are a predefined list of 6-12 set data types. They would be populated by an admin with a base list, and then have the option of adding to that list of data types at future dates.

Each dashboard_extractedlistpresence record will have a distinct HP data type (e.g. record 1 is of HP data type 'frequency', record 2 is of HP data type 'mass')

Definition of Done:
- Ability to store the list of HP data types.
- Ability to add/edit HP data types should be available through the admin panel
- Necessary fields to store for HP data type are title (max 50 chars) and description (max 255 chars)
- store created at/edited at

**Comment by michael-barbour** [comment]
>Each dashboard_extractedlistpresence record

I talked to Kathie and this was a type-o.  Data Types are actually meant to be attached to dashboard_extractedhabitsandpractices
