### ISSUE TITLE
associate HP data records with PUC

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1351]
As a Factotum data curator
I want to assign a PUC to each extractedhabitsandpractices data record
So that I am easily able to categorize HP documents by what type of product data they will provide

Ability to link dashboard_extractedhabitsandpractices records and PUCs is already present in the data models, however functionality does not exist in the application to create this linkage.

http://factotum.epa.gov/datadocument/321338/

Definition of Done:
- For HP data group type, on the /datadocument/ page, from an existing data record card in the center of the page, user should have ability to assign/select 1 or more PUCs to associate with that individual data record (note a PUC is associated with each data record, the PUC is not associated with the data document as a whole)
- User should also have ability to edit/change an existing PUC to HP data record association, or to remove the HP data record to PUC association
- HP extracted data record can be associated with many PUCs

**Comment by michael-barbour** [comment]
This data was omitted from the Habits and Practices data card.  The only way to view which PUCs are attached to a card is to open the "Edit" modal.  This seems to fit the criteria of what is being asked for, but I want to make sure that's what is expected.

Current card information.  Tags, Data Type, Product surveyed and Notes
![image](https://user-images.githubusercontent.com/22226925/79124893-43c24800-7d6b-11ea-9403-9ef226261853.png)

Example of the PUCs on the Edit Modal.
![image](https://user-images.githubusercontent.com/22226925/79124946-5472be00-7d6b-11ea-8d6a-e4960fdbc8a0.png)
