### ISSUE TITLE
move pucs summary page link

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1355]
As the Factotum product owner
I want to move the link to the PUC summary page
So that it is more accessible to the user

Currently, a user links to the PUCs summary page (http://factotum.epa.gov/pucs/) from the data curation menu. However this menu is only available to logged in users and the PUCs summary page should be available to 'public' users.

Definition of Done:
- Ensure the http://factotum.epa.gov/pucs/ page is accessible to public users
- On the Get Data page (http://factotum.epa.gov/get_data/), include a button linking to the PUCs summary page (http://factotum.epa.gov/pucs/)
- On the home page, create a link to the PUCs summary page (http://factotum.epa.gov/pucs/) (ideas - hyperlink the 'PUCs' title in the table next to the bubble plot?)
- Remove the 'PUCs' link under the data curation menu

**Comment by mwfrost** [comment]
For sprint review: http://localhost:8000/pucs/
