### ISSUE TITLE
bulk assign raw category to PUC-data display

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1356]
As a Factotum data curator
I want to be able to batch assign raw categories to a PUC
So that I can more easily curate data

Currently, there are many data records in Factotum with a 'raw_category' field populated. Often this raw category field provides enough information to assign any associated products to a PUC.

Definition of Done
- Create a new 'classification_method' in the dashboard_producttopuc model for 'Bulk assignment to PUC by raw category'
- For logged in users, create a new link in the 'Data Curation' tab in the nav bar for 'Bulk assign raw category to PUC'
- Create new 'Bulk assign raw category to PUC' page, which includes on page a table listing all unique data group to dashboard_datadocument.raw_category combinations
   - Table should include columns for
       - dashboard_datagroup.name (hyperlinked to /datagroup/ page)   
       - dashboard_datadocument.raw_category
       - Number of documents in that data group with that raw_category (default sort table by this column, in descending order)
  - Table should only include entries where the number of documents in the data group with that raw_category is >50
*Optional implement with AG Grid

**Comment by debboutr** [comment]
Something I forgot to mention... The `raw_category` is an attr of the DataDocument. In order to link these to PUCs there will need to be a Product created? How will that work?

**Comment by kdionisio** [comment]
Good call @debboutr 
We can add an additional condition on which documents appear in the above described table. A document will only appear in the table IF at least one product has been created for the document.

**Comment by michael-barbour** [comment]
Are data documents without raw categories valuable?  A fair number are blank.

![image](https://user-images.githubusercontent.com/22226925/74044800-ad079280-4999-11ea-9f23-08a6e2a12ffa.png)

**Comment by michael-barbour** [comment]
> Are data documents without raw categories valuable? A fair number are blank.
> 
> ![image](https://user-images.githubusercontent.com/22226925/74044800-ad079280-4999-11ea-9f23-08a6e2a12ffa.png)

Filtering out blank raw categories per Kathie's request

**Comment by michael-barbour** [comment]
@kdionisio 
In regards to your previous request to filter out documents without products, do you want those filtered documents to be removed from the document count in the third column?  Should the third column be "The number of products attached to data documents by raw category"?

**Comment by kdionisio** [comment]
@michael-barbour correct, documents with a blank raw category should not be counted

The 'count' should be: Number of documents in that data group with that raw_category, where raw category = null is dropped entirely.
