### ISSUE TITLE
redesign FU chemical cards

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1357]
As the Factotum product owner
I want to redesign the chemical cards on the FU /datadocument/ pages
To maintain consistent look and feel of the application

http://factotum.epa.gov/datadocument/255432/

Definition of Done:
- Chemical data (raw chem name, raw cas, DTXSID, preferred chem name, preferred CAS) on the chemical cards on the /datadocument/ page for group type FU should mimic the format and appearance for chemical data on chemical cards for group type CO
- Pencil and trash can icons in upper right of each chemical card, allowing user to edit or delete chemical records, should be visible (same as for CO chemical cards) (only for logged in users)
- Underneath chemical information, currently reported functional use is displayed. In line with reported functional use, also display the 'Clean functional use' and 'Curated  functional use'
  - Above three can be labeled simply as 'Reported' 'Cleaned' and 'Curated'
- Ability to add new chemical record should be present on /datadocument/ page (i.e. the green '+' sign to add a new chemical record) (only for logged in users)

**Comment by debboutr** [comment]
@kdionisio if we are now going to have the ability to edit in multiple `report_funcuse`s, how many should a user have the ability to add? Right now I've given the user to hit an "add" button to add up to 7 funcuses on the creation of a new chem. Is this adequate? If the user will need to add more, then they can go to the edit window where they can add up to 7? more. As I have it currently, there are 7 inputs for a `report_funcuse` but only the first is visible and each time you hit the "add" button, which is just a plus icon, a new input will display.

**Comment by kdionisio** [comment]
@debboutr Let's make it 12 inputs max (unless that will cause problems?) But otherwise I'm fine with your proposed implementation. Also fine to, for example, allow the user to add 5 via an 'add' button and then add more through an edit window. I am not too worried about the user experience in this case in terms of inputting the data because the vast majority of this data will be bulk uploaded via csv, the user would likely just be correcting things manually rather than adding in 12 functional uses per chemical manually.

**Comment by michael-barbour** [comment]
Where is the curated functional use coming from?
I am using the reported and cleaned functional use on the model created for #1323 and #1322

**Comment by kdionisio** [comment]
@michael-barbour hmmmm...indeed a great question. It appears I have not yet requested a curated functional use field to be added :-). Due to this, assume the definition of done above has been revised to eliminate any reference to curated functional use. Thanks!
