### ISSUE TITLE
batch assign products to PUC based on raw category

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1362]
As a data curator, 
I want to be able to assign all products with a linked raw category to a PUC
so that I can do more efficient data curation

In #1356, a page + table were created listing groups of documents eligible for the above. Records in the table represent unique data group to datadocument.raw_category combinations, and are limited to documents which already have >=1 product associated with them

Definition of Done:
- For each record/row of the table created in #1356, there should exist a button to 'Map to PUC,' which allows the user to specify a PUC from our existing PUC set
- When user specifies a PUC, all products linked to a document in that group should be assigned to the PUC
- dashboard_producttopuc.classification_method for all of these linkages should be assigned to 'bulk assignment to PUC by raw category' (abbreviation for this classification method presumably was created in #1356?)

**Comment by michael-barbour** [comment]
The table does not filter out products that have already been bulk assigned already.

If a data group and raw category set has already gone through the bulk assignment process the connections will be deleted and the new connection will be saved.

I.E.  If product 1 is connected to puc 1 and a request would request in product 1 to be connected to puc 2.  The result would be "product 1" -> "puc 2" classification_method "BA"
