### ISSUE TITLE
chemical-PUC summary

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1377]
**Editing per discussion which occurred when this ticket was pointed
As a product owner
I want to create a unique link to chemical-PUC summary data
So that I can link to this data from other parts of the application and from other applications

'Chemical' in this instance always refers to the DTXSID, and not the raw chemical record.
/chemical/ page currently exists, and displays chemical-PUC summary information

Definition of Done:
On /chemical/ page, create unique URL that directs user to a specific portion of the /chemical/ page, in this case, the information on a unique chemical-PUC combination.
- unique URL exists for each chemical-PUC combination
- unique URL directs user to the /chemical/ page, where the PUC of interest is somehow 'highlighted'
   - 'filter' option for that PUC is turned 'on', such that the documents table is displaying documents associated with that PUC, and the products table is displaying products associated with that PUC
  - bubble plot is zoomed in to that PUC

**Comment by zachmunzenrider** [comment]
A question about the existing filtering behavior when you arrive at this page through the new, PUC-specific URL: should the other filter icons disappear?  It might be a recipe for confusion if they do not!

Alternately, if they remain in place as they are now, and the user clicks on one, should the page just revert to its old functionality?
