### ISSUE TITLE
Error pages 401, 403, 404, 500

### ISSUE THREAD

**Issue by dmlyons2** [HumanExposure/factotum#1385]
Now that we are in docker we are publishing standard nginx error pages.  Please replace these pages with a blank white page with the following image centered on the page. 

As a product owner
I want my application to error out gracefully
So that the user still knows they are in the application and can report the error to me.

![401](https://user-images.githubusercontent.com/1336349/73951418-15d00b80-48c3-11ea-91f6-dc1281ab31dc.png)
![403](https://user-images.githubusercontent.com/1336349/73951435-1c5e8300-48c3-11ea-9dc9-f19e94ca2e21.png)
![404](https://user-images.githubusercontent.com/1336349/73951442-1ff20a00-48c3-11ea-8072-1c3a7be8a14d.png)
![500](https://user-images.githubusercontent.com/1336349/73951450-22546400-48c3-11ea-9512-8efaa4a9c43c.png)

**Comment by mwfrost** [comment]
We can't use this?
https://www.quotemaster.org/images/a5/a5f30ab2ae1be7a5b05abb6cc6cd4c14.jpg
