### ISSUE TITLE
chemical presence - chemical connection (API)

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1389]
As a scientist
I want to be able to retrieve the chemical presence to chemical connection via API
So that I can programatically retrieve data of interest

Currently, the chemical presence API returns base information on the chemical presence keywords and their definitions. Users would also like to know which chemicals have been assigned to each keyword.

Definition of Done:
- new API to provide data on the DTXSID - chemical presence keyword connection/relationship; new API to be titled api.factotum.epa.gov/chemicalpresence. 
- new API would include query parameter options for:
  - document ID
  - chemical ID (i.e. DTXSID)
  - chemical presence keyword ID
- payload would include
  - chemical ID (i.e. DTXSID)
  - rid (dashboard_rawchem.rid)
  - chemical presence keyword set (**note we are returning the keyword *sets*)
  - document ID(s) (may be more than one per chemical/chemical presence keyword set combination)
- new API will not have a 'List' option to retrieve all DTXSID - chemical presence keyword set combinations that exist (this does not make sense in this case due to the number of values which would be returned, and how non-useful that information would be)

**Comment by michael-barbour** [comment]
So I've written the payload to return like this:
``` json
{
    "chemical_id": "DTXSID0000000",
    "chemical_presence_keyword_sets": [
        {
            "tags": ["anticaking","antifouling"],
            "documents": [354786]
        },
        {
            "tags": ["abrasive","flavor","slimicide"],
            "documents": [254781, 354786]
        }
    ]
}
```
I think I got confused because of the comments on your document id.

> document ID(s) (may be more than one per chemical/chemical presence keyword set combination)

You ask for an array of documents so I have written my code to return an array.  If you're also asking for an rid in the payload, then you would never get an array of documents.  This is because a rawchem can only belong to one document.  Also, rid is an nullable, blankable character string, you may get duplicate rows.  If this is all known then I'll rewrite the query to return what you've asked for without the list of documents.

**Comment by kdionisio** [comment]
Edit - only raw chemical records that have RID populated should be returned in payload!

**Comment by michael-barbour** [comment]
My idea for a payload with rids would look like this with RID.
```JSON
{
    "chemical_id": "DTXSID0000000",
    "chemical_presence_keyword_sets": [
        {
            "tags": ["anticaking","antifouling"],
            "documents": [
               {"id": 354786, "rids": ["DTXRID10000", "DTXRID10001"]}
           ]
        },
        {
            "tags": ["abrasive","flavor","slimicide"],
            "documents": [
               {"id": 254781, "rids": ["DTXRID10002"]},
               {"id": 354786, "rids": ["DTXRID10003", "DTXRID10004"]}
           ]
        }
    ]
}
```

**Comment by michael-barbour** [comment]
This is still awaiting a discussion regarding how we will be pulling the related data.  I've connected my current branch to this issue to hopefully prevent it from getting lost.  I'll continue working on it when we have a resolution.
