### ISSUE TITLE
dual figure+table display (chemical page)

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1390]
As a user,
I want to see both the table of documents and the bubble plot simultaneously on the chemical page
because they display different pieces of information

Currently on the /chemical/ page, there is a toggle 'button/circle' in the upper left allowing user to toggle between a 'Show PUCs' (ie the bubble plot) and 'Show Table' (ie the table of documents) view.  Rather, user would like to see both the bubble plot and the table at the same time.

http://factotum.epa.gov/chemical/DTXSID9022528/

Definition of Done:
On /chemical/ page, 
- remove option to toggle between 'show PUCs' and 'Show table' (both table of documents and bubble plot should be visible at all times)
- bubble plot and 'PUC' table can remain in their current locations
- move table of list presence keyword sets lower on the page so that it does not overlap with bubble plot (overlapping is misleading since the list presence keywords and the PUC bubble plot are not related pieces of data)
- make table of list presence keyword sets wider so that user can see all keywords in the set (see screenshot, many full keyword sets are not visible due to ellipses)
- move table of documents underneath the table of keyword sets

[https://app.zenhub.com/files/99837877/378b2185-c826-4eb3-957c-f46dac5bc7ce/download](https://app.zenhub.com/files/99837877/378b2185-c826-4eb3-957c-f46dac5bc7ce/download)

**Comment by zachmunzenrider** [comment]
I believe I ended up addressing all these changes in #1122, and this ticket can be closed

**Comment by kdionisio** [comment]
closing because this issue was taken care of as part of #1122
