### ISSUE TITLE
WF data incorrect in API response

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1391]
It appears there is a bug causing incorrect data to be delivered in the documents API, specifically the cleaned/curated weight fraction data. 

Data which should be delivered via the documents API are the dashboard_extractedchemical.central_wf_analysis, lower_wf_analysis, and upper_wf_analysis

HOwever for this example, though there appears to be upper and lower wf_analysis values per the UI, the upper and lower wf analysis values returned in the API are not correct (they are all 0). Note that the central wf analysis values returned via the API DO appear to be correct.

http://api.factotum.epa.gov/documents/1097132/
vs.
http://factotum.epa.gov/datadocument/1097132/

Definition of Done:
lower_wf_analysis and upper_wf_analysis values returned in the documents API are correct

**Comment by michael-barbour** [comment]
Add blocker of 1366 due to the tests being connected.  In order to write a test for this ticket I'll need the already written tests in https://github.com/HumanExposure/factotum_ws/pull/52
