### ISSUE TITLE
'unknown' brand/manufacturer

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1400]
As the product owner
I would like consistency in the representation of missing data
So that I can maintain a clean database

In the dashboard_product model, specifically
dashboard_product.brand_name   and
dashboard_product.manufacturer  fields,

The missing data is inconsistently represented. Some values in these two fields are blank, and others are populated with 'unknown'

Definition of Done:
Change all instances of 'unknown' in dashboard_product.brand_name and dashboard_product.manufacturer to a blank value

**Comment by mwfrost** [comment]
@kdionisio Are any of these values capitalized? Like "Unknown"?

**Comment by kdionisio** [comment]
I have not checked for "Unknown", but all the instances I have seen are "unknown".

**Comment by mwfrost** [comment]
I will approve this branch since it suits the ticket as written - uncapitalized "unknown" will be processed.
