### ISSUE TITLE
inability to load curated chemicals

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1402]
On attempting to load a .csv of curated chemicals on the http://factotum.epa.gov/chemical_curation/ page, I receive a server error (500)

File I am attempting to upload:
[https://app.zenhub.com/files/99837877/c3a3209e-5e7e-4887-8feb-fa163a7c8e75/download](https://app.zenhub.com/files/99837877/c3a3209e-5e7e-4887-8feb-fa163a7c8e75/download)

Definition of done:
Ability to upload linked file of curated chemicals to Factotum via /chemical_curation/ page

**Comment by michael-barbour** [comment]
Problem True Chem Id:  **DTXSID9052846**

_Dave in Slack:_

Had a problem this morning where Kathie is trying to upload curated chemicals on the chemical curation page and she had a bad char that was not UTF8. She then fixed the file and got this error:

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
>     return self.cursor.execute(sql, params)
>   File "/usr/local/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 71, in execute
>     return self.cursor.execute(query, args)
>   File "/usr/local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 206, in execute
>     res = self._query(query)
>   File "/usr/local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 312, in _query
>     db.query(q)
>   File "/usr/local/lib/python3.7/site-packages/MySQLdb/connections.py", line 224, in query
>     _mysql.connection.query(self, query)
> MySQLdb._exceptions.IntegrityError: (1062, "Duplicate entry 'DTXSID9052846' for key 'sid'")
> The above exception was the direct cause of the following exception:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
>     response = get_response(request)
>   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
>     response = self.process_exception_by_middleware(e, request)
>   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/usr/local/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
>     return view_func(request, *args, **kwargs)
>   File "/app/dashboard/views/chemical_curation.py", line 26, in chemical_curation_index
>     ups = formset.save()
>   File "/app/dashboard/forms/chemical_curation.py", line 88, in save
>     DSSToxLookup.objects.bulk_create(new_dsstox)
>   File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
>     return getattr(self.get_queryset(), name)(*args, **kwargs)
>   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 474, in bulk_create
>     ids = self._batched_insert(objs_without_pk, fields, batch_size, ignore_conflicts=ignore_conflicts)
>   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 1211, in _batched_insert
>     self._insert(item, fields=fields, using=self.db, ignore_conflicts=ignore_conflicts)
>   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 1186, in _insert
>     return query.get_compiler(using=using).execute_sql(return_id)
>   File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1368, in execute_sql
>     cursor.execute(sql, params)
>   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
>     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
>   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
>     return executor(sql, params, many, context)
>   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
>     return self.cursor.execute(sql, params)
>   File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
>     raise dj_exc_value.with_traceback(traceback) from exc_value
>   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
>     return self.cursor.execute(sql, params)
>   File "/usr/local/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 71, in execute
>     return self.cursor.execute(query, args)
>   File "/usr/local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 206, in execute
>     res = self._query(query)
>   File "/usr/local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 312, in _query
>     db.query(q)
>   File "/usr/local/lib/python3.7/site-packages/MySQLdb/connections.py", line 224, in query
>     _mysql.connection.query(self, query)
> django.db.utils.IntegrityError: (1062, "Duplicate entry 'DTXSID9052846' for key 'sid'")

**Comment by zachmunzenrider** [comment]
Kathie - I think I see exactly what's going on here, but you should weigh in on what you'd like the correct behavior to be.

The file you're trying to upload has records with duplicate SIDs, including 15 with the SID 'DTXSID9052846`. There is currently no record matching this SID in the database, so the system is trying to insert all of them, and failing because it violates the unique constraint.

To be clear--there are a lot of other duplicate SIDs in this upload file, but the others all seem to already have a matching SID in the database, so the system isn't trying to create a new one.

It would be easy to add a condition to this code to prevent duplicates from being created, but I'd want to be sure that's the behavior you want. An option would be to only include the first record in the csv in the set of new records to be inserted, and ignore all the rest. As another option, it could fail gracefully, with a meaningful error message.

**Comment by kdionisio** [comment]
ok - I think there is some misinterpretation of how the data needs to be inserted. It is OK for there to be duplicate SIDs in the file we are loading. Note that in the cases where we have duplicate SIDs, the associated RIDs are NOT the same.

Keep in mind that every single dashboard_rawchem record that exists in our database will eventually get assigned it's own unique RID.

If we have new data we are trying to load for an existing batch of dashboard_rawchem records, it may looks like this (where the rawchem.id is existing data in Factotum, the RID and SID are new pieces of data that we are trying to load to Factotum):

rawchem.id=1, RID123, SID 1
rawchem.id=2, RID124, SID1
rawchem.id=3, RID125, SID1
rawchem.id=4, RID987, SID9
rawchem.id=5, RID988, SID9
rawchem.id=6, RID989, SID9

There are two potential situations on load. First situation, SID1 already exists in the dsstoxlookup table. In this case, the rawchem.id=1,2,3 records should be updated with rawchem.rid=RID123, RID124, and RID125, and all three records should be linked to the SID1 record which already exists in dsstoxlookup.

Second situation. SID9 does NOT exist in the dsstoxlookup table. In this case a new record should be created in dsstoxlookup for SID9. Then rawchem.id=4,5,6 records should be updated with rawchem.rid=RID987, 988, 989, and all three records should be linked to the SID9 record in dsstoxlookup.

Hope that clarifies things.

**Comment by zachmunzenrider** [comment]
This makes sense! I should be able to fix this without too much trouble.

**Comment by zachmunzenrider** [comment]
Kathie - I believe I've fixed (locally) the original problem you reported, but now when I upload the csv (against my prod data, which is a few weeks old) I get this error message:

![image.png](https://images.zenhubusercontent.com/5be47c474f4473195308604f/3054afd5-e43e-439c-985d-e0d19c576d22)

I believe this means there is no matching RawChem record for each of the listed rows, and I can tell that's true in my db by examining the RawChem table.

Is this a concern for you? Or do you think it's just an issue of stale data in my local environment?

**Comment by kdionisio** [comment]
@zachmunzenrider I am not concerned. I did some spot checks of those IDs and they do exist in the production database. Some of these records were pushed into Factotum just last week, so it is certainly reasonable to think this is just a matter of you having 'old' data.
