### ISSUE TITLE
upload clean FU and FU category

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1408]
As a Factotum data curator
I want to curate the reported functional uses outside of the application and load the associated functional use categories
So that I can store clean functional use data.

Currently, reported functional uses are stored for multiple data group types. Each reported functional use has an associated 'clean/curated' functional use field (created in #1323), and has the ability to be linked to a functional use category (created in #1326).

Definition of done:
- On the data group page for CO, LP, and FU data group types, ability to download all reported functional uses that have been stored in the database (when reported functional uses exist for the data group).
  - download would be available as a .csv
  - .csv download should include the reported functional use (when populated) and associated ID 
- On data group page for CO, LP, and FU data group types, ability to upload associated clean/curated functional use field and functional use category
  - required format for upload should be indicated to user, either through a template that can be downloaded, or by listing the required columns/column headers on the data group page
  - upload would be via a single .csv file
  - required columns for the upload would be the relevant ID (same ID as included in the download of reported functional uses), the clean/curated functional use (created in #1323), and the associated functional use category (created in #1326)
- Functionality of the upload
  - upon upload, reported functional use/clean/curated functional use record should be linked to the appropriate FU category as indicated in upload file
  - User should be required to select a script of script type 'FU curation', which should be linked to each clean/curated record and FU category assignment
- Additional requirements 
  - new script type needs to be added: 'FU curation'
  - behavior of upload if FU category indicated in upload does not exist in the FU category data model??????
  - How should FU category be referred to in the upload file? By the FU category ID? ????

**Comment by mwfrost** [comment]
Kathie has clarified that the functional use fields should be appended to the existing csv download - this is not a new file
