### ISSUE TITLE
composition - chemical connection (API)

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1411]
As a scientist
I want to be able to retrieve the composition data (i.e. weight fraction) to chemical connection via API
So that I can programatically retrieve data of interest

Definition of Done:
- new API to provide data on the DTXSID - composition connection/relationship; new API to be titled `api.factotum.epa.gov/composition`
- new API would include query parameter options for:
  - document ID
  - chemical ID (i.e. DTXSID)
  - DTXRID
  - product ID
- payload would include
  - chemical ID(s) (i.e. DTXSID)
  - DTXRID
  - product ID(s)
  - document ID(s)
  - dashboard_rawchem.component
  - dashboard_extractedchemical.ingredient rank
  - dashboard_extractedchemical.lower_wf_analysis
  - dashboard_extractedchemical.central_wf_analysis
  - dashboard_extractedchemical.upper_wf_analysis
- new API will not have a 'List' option to retrieve all DTXSID - weight fraction combinations that exist (this does not make sense in this case due to the number of values which would be returned, and how non-useful that information would be)

**Comment by kdionisio** [comment]
**Also need to include rid (dashboard_rawchem.rid) in payload

**Comment by michael-barbour** [comment]
> new API will not have a 'List' option to retrieve all DTXSID - weight fraction combinations that exist (this does not make sense in this case due to the number of values which would be returned, and how non-useful that information would be)

The responses may return multiple results so all of these query params should be thought of as simplifying the list.  For instance say *True Chem: Water* is linked to 2 ExtractedChemicals with RIDs 1 and 2.  The response would look like this:
```JSON
{
   "data":[
      {
         "chemical_id":"DTXSID6026296",
         "ingredient_rank":null,
         "lower_wf_analysis":0.125,
         "central_wf_analysis":null,
         "upper_wf_analysis":0.25,
         "component":null,
         "rid":"1",
         "document":1,
         "products":[
            1
         ]
      },
      {
         "chemical_id":"DTXSID6026296",
         "ingredient_rank":null,
         "lower_wf_analysis":null,
         "central_wf_analysis":null,
         "upper_wf_analysis":null,
         "component":null,
         "rid":"2",
         "document":1,
         "products":[
            1
         ]
      }
   ]
}
```
Also, the default response is currently a list of all curated (with dsstox) ExtractedChemicals that have an RID that is not blank or null (as it's where we are sourcing all of our data), so it might make more sense for us to format the request like to keep with *JSON:API*: 
```JSON
{
   "data":[
      {
         "rid":"DTXRID002",
         "ingredient_rank":null,
         "lower_wf_analysis":0.125,
         "central_wf_analysis":null,
         "upper_wf_analysis":0.25,
         "component":null,
         "relationships":{
            "chemical":{
               "id":"DTXSID9022528"
            },
            "document":{
               "id":156051
            },
            "products":[
               {
                  "id":1868
               }
            ]
         }
      ]
   }
```
