### ISSUE TITLE
functional use - chemical connection (API)

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1412]
As a scientist
I want to be able to retrieve the functional use to chemical connection via API
So that I can programatically retrieve data of interest

The functional use API (#1407) will return base information on the functional use categories and their definitions. Users would also like to know which chemicals have been assigned to each functional use category.

Definition of Done:
- new API to provide data on the DTXSID - functional use category connection/relationship; new API to be titled `api.factotum.epa.gov/function`
- new API would include query parameter options for:
  - document ID
  - chemical ID (i.e. DTXSID)
  - functional use category ID
- payload would include
  - chemical ID(s) (i.e. DTXSID)
  - document ID(s) 
  - functional use category ID(s)
- new API will not have a 'List' option to retrieve all DTXSID -functional use category combinations that exist (this does not make sense in this case due to the number of values which would be returned, and how non-useful that information would be)

**Comment by kdionisio** [comment]
**also need to include rid (dashboard_rawchem.rid) in payload

**Comment by michael-barbour** [comment]
So unlike 1411 this is not supposed to have an RID filter.

Are null values for the payload permitted?  Specifically SID, RID, and Category (document cannot be null by nature).

https://github.com/HumanExposure/factotum/issues/1411

**Comment by kdionisio** [comment]
RID should be in the payload (per the comment above), but RID does not need to be a query param. option.

Also, for the payload, any given field in the payload *can* be null.  However we do not want to return a record in the payload where *all* fields in the payload are null.

**Comment by michael-barbour** [comment]
Closed via PR #1440
