### ISSUE TITLE
what am I filtering?

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1417]
As a Factotum user
I want to know what filters have been applied
So that I know what I am looking at in the tables on the /chemical/ page

Currently, in the PUCs table on the /chemical/ page, a user can 'filter' by a particular PUC. Selecting a filter results in the documents table and the products table only displaying documents/products applicable to the filter. Similar for the list presence keyword table.

Definition of Done:
Visual indication to user on /chemical/ page showing:
- In PUCs table next to bubble plot, visual indication that a filter has successfully been applied when the filter is selected (e.g. highlight/bold the PUC in the table that the filter was applied for)
- Visual indication on the documents table showing which subset of documents are being displayed (i.e. user should see some indication that documents being displayed have been filtered by a particular PUC, e.g. change text under table to read 'Showing 1 to 2 of 2 entries *for documents related to 'PROD TYPE* (filtered from 4,294 total *documents*)'
-Visual indication on the products table showing which subset of products are being displayed (i.e. change text below table to read 'Showing 1 to 2 of 2 entries *for products related to 'PROD TYPE'* (filtered from 63 total *products*)'
- Visual indication on the list presence keyword table showing that a filter has been successfully applied (e.g. bold/highlight/outline that row in the list presence keyword table)
- Visual indication in the documents table showing which list presence keyword set has been filtered on
- When a list presence keyword set filter has been applied, products table should default back to displaying *all* products

**Comment by BryanMG957** [comment]
Works great
