### ISSUE TITLE
unable to register records in new FU data group

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1446]
Upon attempting to create a new FU data group and register documents (both events occur after a single action by the user), user received a '502' error.

Data group still appears to  have been created, however no documents were registered (data group is showing 0 registered documents)

Examples of FU data groups created where no records/documents were registered:
http://factotum.epa.gov/datagroup/742/
http://factotum.epa.gov/datagroup/737/

Register records files which were used:
[https://app.zenhub.com/files/99837877/e280d19c-bdb4-407b-9774-20b916d64444/download](https://app.zenhub.com/files/99837877/e280d19c-bdb4-407b-9774-20b916d64444/download)

Definition of Done:
- Ability to register records for a new FU data group
- If error is encountered upon registering records, the data group should not be created

*Note user was able to create a new FU data group and register records successfully for a different FU data group of smaller size.

**Comment by dmlyons2** [comment]
How big was the file that was being uploaded?

**Comment by kdionisio** [comment]
appears to be an issue of too big file size and n ot a bug
