### ISSUE TITLE
bubble plot - article PUCs (home page)

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1465]
As a data curator
I want to view a visual summary of data showing products linked to 'article' PUCs on the homepage
so that I can better understand data that has been curated

Definition of Done:
- On the factotum home page, underneath the existing bubble plot, create a bubble plot and corresponding table for the PUCs of kind 'articles'
- Label as 'Article PUCs'
- Change label of existing bubble plot from 'PUCs' to 'Formulation PUCs'

**Comment by zachmunzenrider** [comment]
I asked Kathie in Slack: Michael asked a good question about the Article PUCs--will they have the same 3-tier  "General Category - Product Family - Product Type" that Formulation PUCs do? Or is it a flatter structure?

And Kathie responded:
good question - so the article PUCs are still 'PUCs'; they are in the PUC table and thus can have the 3-tier hierarchical structure. At the moment however, the article PUCs have only 1 tier, and there are only ~12 of them. But as we get more data we would likely be adding tiers 2 and tier 3....buuut, that 'as we get more data' may be well in the future

**Comment by zachmunzenrider** [comment]
Michael also caught the fact that the bubble plots aren't catching for the puc hierarchy--a product could have 2 pucs with different classification methods, and both pucs would get represented in the bubble chart. Not sure if this is a big issue or not. . . .
