### ISSUE TITLE
change document type

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1485]
As the Factotum product owner
I would like to batch change the data document type for a specific set of documents
 So that I can improve the quality of data in the application

In a specific data source, many of the data documents are incorrectly assigned for the document type. We have identified a set of documents (by data document ID) where the document type needs to be changed.

Definition of done:
For the list of dashboard_datadocument.ids in the attached file, change the dashboard_datadocument.document_type_id to be 40

[https://app.zenhub.com/files/99837877/5236e23b-5da9-4811-bf3a-e46cccf81ae2/download](https://app.zenhub.com/files/99837877/5236e23b-5da9-4811-bf3a-e46cccf81ae2/download)

**Comment by mwfrost** [comment]
Could we use this ticket to develop a way to perform the task via the API?

**Comment by dmlyons2** [comment]
```python
import mysql.connector
import csv

mydb = mysql.connector.connect (
  host="localhost",
  user="root",
  password="root",
  database="prod_factotum",
  auth_plugin="mysql_native_password"
)

mycursor = mydb.cursor()

with open('load.csv') as csv_file:
	csv_reader = csv.reader(csv_file, delimiter=',')
	line_count = 0
	for row in csv_reader:
		if line_count == 0:
			print ("Processing csv")
			line_count += 1
		else:
			sql = "UPDATE prod_factotum.dashboard_datadocument SET document_type_id=40 WHERE id=%s" % row[0]
			print(sql)
			mycursor.execute(sql)
			mydb.commit()
			line_count += 1

```
