### ISSUE TITLE
select cards for LP keyword assignment

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1487]
After push of Kubota sprint, the functionality to assign list presence keyword/tags to chemical records on CP group type data document pages is not working. The 'select all' chemical card button is not working in the 'List Presence Keyword', and the user is also not able to individually select a chemical card and then assign a list presence keyword.

http://factotum.epa.gov/datadocument/1511926/

Definition of Done:
LP keyword assignment functionality is working, both for individually selecting a chemical card and assigning a keyword, and to 'select all' chemical cards and assign keywords.

**Comment by dmlyons2** [comment]
This was a collectstatic issue with the docker container.
