### ISSUE TITLE
create data model - DSSTox substance (3 pts)

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#149]
As Karyn the curator
I want to be able to store information that links extracted chemicals to the EPA chemical database
So that I can integrate Factotum chemical data with other EPA chemical databases.

New data model, 'DSSTox Substance' is needed. Each row represents a substance (i.e., chemical) from the ExtractedChemical model. Data model should include the following fields:
1. extracted_chemical id (the id (i.e., foreign key) from the extracted_chemical data model)
2. true_cas (text, max 50 characters)
3. true_chemname (text, max 500 characters)
4. rid (text, max 50 characters)
5. sid (text, max 50 characters)
6. created_at (date entry was created)
7. updated_at (last date entry was updated)

In extractedchemical data model, update 'cas' field to be 'raw_cas' and 'chemname' field to be 'raw_chemname'

**Comment by Daveahern** [comment]
@kdionisio to what extent are data elements 2 through 5 required?

**Comment by kdionisio** [comment]
If you are asking if 2-5 above should be required fields in the data model, the answer is no!
