### ISSUE TITLE
edit document meta data from QA page

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1490]
As a Factotum curator
I want to be able to edit meta data about a document from the QA page
So that I can correct or add information efficiently while I am conducting QA

http://factotum.epa.gov/qa/extractedtext/1514542/

Definition of Done
On the /qa/extractedtext/ page,
- Curator should have ability to edit and save changes to the meta data fields in the set of data fields at the top of the page, specifically:
   - data document title
   -  subtitle
   - raw category
   - URL
   - Note
 - Curator should maintain ability to edit/change the data document type selection as some part of editing process
- editing of these fields does not need to be linked to QA notes requirement etc. as part of the official QA

**Comment by mwfrost** [comment]
Potential solution: open the data document edit modal, then redirect the user back to the QA page on save
