### ISSUE TITLE
faster loading for docs with many chemicals

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1491]
As a factotum user
I want to be able to load pages with many chemicals more quickly 
So that the page  is more user friendly

Some documents exist in Factotum that have hundreds of chemical records associated with a single document, e.g.
http://factotum.epa.gov/datadocument/1512365/

These pages take a very long time to load and are relatively non user-friendly.

Definition of Done:
- Faster loading of /datadocument/ pages which include >30-40 chemical records
- OK to change to a more appropriate organization/display of chemical cards on these pages

**Comment by mwfrost** [comment]
Proposed solutions: AJAX call for chemical cards after page load

**Comment by michael-barbour** [comment]
For CP and HP group types verify that the selector remains functional for assigning keywords.  The event listerners will probably have to be assigned after the ajax call.
