### ISSUE TITLE
align weight fraction type with appropriate upload

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1492]
As the Factotum product owner
I want to align selection of weight fraction type with the data upload it corresponds with
To improve the ease of the user experience when uploading data

Currently the weight fraction type is associated with the 'extracted text' data upload on the data group page (under 'extracted' tab)
http://factotum.epa.gov/datagroup/20/

Rather weight fraction type should be associated with the 'clean composition data' upload on the data group page (under 'composition' tab)
http://factotum.epa.gov/datagroup/691/

Definition of Done:
- Selection of 'choose weight fraction type' should be moved from the 'extracted' tab to the 'composition' tab on the /datagroup/ page
- User should be required to select the weight fraction type when they upload the clean composition data under the 'composition' tab
- For existing data groups 198 and 199, change any values in raw_min_comp, raw_max_comp, and raw_central_comp to NA/blank/null (as appropriate),
- How to handle weight fraction type id field in extractedchemical model?? not required? change to predicted once predicted values are uploaded?

**Comment by mwfrost** [comment]
This entails moving the `weight_fraction_type` field and validation logic out of `dashboard/forms/data_group.py:ExtractFileFormSet` and `dashboard/forms/data_group.py:CompositionExtractFileForm` into `dashboard/forms/data_group.py:CleanCompFormSet` `dashboard/forms/data_group.py:CleanCompForm`, respectively.

**Comment by fang-yan-csra** [comment]
the sql script to correct data for data group 198 and 199:

```
update dashboard_extractedchemical
set raw_min_comp ='',
    raw_max_comp = '',
    raw_central_comp =''
where rawchem_ptr_id <> 0
    and rawchem_ptr_id in (
  select rawchem.id
    from dashboard_rawchem rawchem
    join dashboard_extractedtext extractedtext
      on rawchem.extracted_text_id = extractedtext.data_document_id
    join dashboard_datadocument datadocument
      on datadocument.id = extractedtext.data_document_id  
   where datadocument.data_group_id in (198, 199)
);
```

**Comment by dmlyons2** [comment]
@Sakshi-Handa @KisitoAsongwe @mwfrost @kdionisio @fang-yan-csra 

I just reopened this ticket. @kdionisio asked to apply this query to the production database. The above query will not work because there is no table called **dashboard_extractedchemical** - Help a brother out.

**Comment by mwfrost** [comment]
Have you run migration #169?

**Comment by dmlyons2** [comment]
Yes, Here is the show migrations from prod_factotum: 
``` bash
admin
 [X] 0001_initial
 [X] 0002_logentry_remove_auto_add
 [X] 0003_logentry_add_action_flag_choices
auth
 [X] 0001_initial
 [X] 0002_alter_permission_name_max_length
 [X] 0003_alter_user_email_max_length
 [X] 0004_alter_user_username_opts
 [X] 0005_alter_user_last_login_null
 [X] 0006_require_contenttypes_0002
 [X] 0007_alter_validators_add_error_messages
 [X] 0008_alter_user_username_max_length
 [X] 0009_alter_user_last_name_max_length
 [X] 0010_alter_group_name_max_length
 [X] 0011_update_proxy_permissions
authtoken
 [X] 0001_initial
 [X] 0002_auto_20160226_1747
celery_usertask
 [X] 0001_initial
contenttypes
 [X] 0001_initial
 [X] 0002_remove_content_type_name
dashboard
 [X] 0001_squashed_migrations_0001_to_0158 (164 squashed migrations)
 [X] 0159_hp_pucs_blank_attribute
 [X] 0160_doc_epa_reg_number
 [X] 0161_product_epa_reg_number
 [X] 0162_created_by_updated_by
 [X] 0163_puc_kind_choices
 [X] 0164_funcuse_extraction_script
 [X] 0165_extractedhp_options_and_extractedhpdoc
 [X] 0166_allow_blank_extr_scr
 [X] 0167_puckind
 [X] 0168_detected_chem_flag
 [X] 0169_rename_extracted_chemical
elastic
 [X] 0001_logstash_views
 [X] 0002_upd_logstash_views
 [X] 0003_fix_puc_in_view
 [X] 0004_querylog
feedback
 [X] 0001_initial
 [X] 0002_comment_email
sessions
 [X] 0001_initial
taggit
 [X] 0001_initial
 [X] 0002_auto_20150616_2121
```

**Comment by mwfrost** [comment]
I think just changing the table name in the first line should do the trick
```
update dashboard_extractedcompositon
set raw_min_comp ='',
    raw_max_comp = '',
    raw_central_comp =''
where rawchem_ptr_id <> 0
  and rawchem_ptr_id in (
  select rawchem.id
    from dashboard_rawchem rawchem
    join dashboard_extractedtext extractedtext
      on rawchem.extracted_text_id = extractedtext.data_document_id
    join dashboard_datadocument datadocument
      on datadocument.id = extractedtext.data_document_id  
   where datadocument.data_group_id in (198, 199)
);

```

**Comment by dmlyons2** [comment]
Awesome -> `/* Affected rows: 26,015  Found rows: 0  Warnings: 0  Duration for 1 query: 24.688 sec. */`
