### ISSUE TITLE
delete extracted list presence keywords

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1503]
As the FActotum Product Owner
I have a need to delete specific extracted list presence keywords

Currently getting 502 Bad Gateway error, due to VPN connection?

Definition of Done:
Delete extracted list presence keywords via **script or SQL query** to run against prod data

active_ingredient(asterisk) 
agricultural(asterisk)
detected(asterisk)
fungicide(asterisk)
insecticide(asterisk)
pesticide(asterisk)

**Comment by fang-yan-csra** [comment]
-- delete reference first
delete from dashboard_extractedlistpresencetotag
where id <> 0
and tag_id in (
    select id 
    from dashboard_extractedlistpresencetag
    where name = 'active_ingredient*'
       or name = 'agricultural*'
       or name = 'detected*'
       or name = 'fungicide*'
       or name = 'insecticide*'
       or name = 'pesticide*'
);

-- delete tag
delete from dashboard_extractedlistpresencetag
where name = 'active_ingredient*'
or name = 'agricultural*'
or name = 'detected*'
or name = 'fungicide*'
or name = 'insecticide*'
or name = 'pesticide*'
;

commit;

**Comment by fang-yan-csra** [comment]
I can delete extracted list presence keywords from factotum Admin page without issue.
