### ISSUE TITLE
unnecessary fields on data doc page - LM

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1505]
As the product owner
I want to remove unnecessary fields from the data document page for group type LM
so that I ensure data quality

For /datadocument/ pages of data group type LM, for the 'edit/add chemical record' pop up modal, this should only show fields associated with the dashboard_rawchem model (currently there are fields shown which are from the dashboard_extractedchemical model) 

http://factotum.epa.gov/datadocument/1555997/

Definition of Done:
For /datadocument/ pages of data group type LM, on the chemical card edit modal, the following fields are the only fields which should appear (remove from UI view but not from database):
- raw chemical name
- raw CAS

**Comment by zachmunzenrider** [comment]
Man, you'd think this one would be a cinch. You'd think. . . .

**Comment by michael-barbour** [comment]
@kdionisio It seems the functional uses are automatically added to all "chemicals" (everything except HP cards).  Do you want to keep these on the edit/add modals or would you prefer them removed?
