### ISSUE TITLE
navigation of /chemical/ page

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1509]
Bugs on /chemical/ page when specific PUC is specified, e.g.

http://factotum.epa.gov/chemical/DTXSID9022528/puc/137/

- Bubble plot not zooming in to the correct PUC
- Documents table showing no documents
- Product table showing no products

Errors likely occurred after completion of #1470/#1465

Definition of Done:
Appropriate selections on /chemical/xxxx/puc/xxx/ page, specifically:
- Bubble plot zooms in on appropriate PUC
- Documents table shows correct subset of documents (i.e. for that chemical/PUC combination)
- Product table shows correct subset of products (i.e. for that chemical/PUC combination)

**Comment by Sakshi-Handa** [comment]
Issue appears to be resolved. Bubble plot zooms into PUC and tables subset based on PUC .

**Comment by mwfrost** [comment]
Ethylparaben, the DTXSID in the example, does not appear to be _directly_ linked to any products in PUC 137 (Personal Care) in the prod data, so no documents or products appear in the tables for the example in the ticket. 

It is directly linked to numerous child PUCs, like 245 (bubble bath), so you can see the correct behavior here:
http://factotum.epa.gov/chemical/DTXSID9022528/puc/245/
