### ISSUE TITLE
502 error - H&P admin panel

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1513]
Product owner not able to edit 'extracted habits and practicess' in admin panel of Factotum

Able to access the 'extracted habits and practicess' page in admin panel (http://factotum.epa.gov/admin/dashboard/extractedhabitsandpractices/), but clicking on either an existing entry (to attempt to edit it) or the 'add new' button, results in a 502 Gateway error

**Comment by mwfrost** [comment]
Our initial suspicion is that the detail page loads slowly (if at all) because the Extracted Text dropdown offers every extracted text record as an option. Making that field read-only might fix this problem.

**Comment by Sakshi-Handa** [comment]
Issue is no longer relevant. 
An admin is able to add/edit existing habits and practices entries via the admin panel. 
https://ccte-factotum.epa.gov/admin/dashboard/extractedhabitsandpractices/2427/change/
