### ISSUE TITLE
products associated with HHE reports

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1514]
Currently, the data group type HH has  a 'Bulk Create Products' button on the /datagroup/ page. This button should not exist since HH documents do not have associated products.

http://factotum.epa.gov/datagroup/196/

Definition of Done:
- On the /datagroup/ page for group type HH, 'Bulk create products' button does not exist
- An SQL Query to Delete all products associated with data group id = 196

**Comment by fang-yan-csra** [comment]
sql script to clean data:

delete pd, p
from dashboard_product p
join dashboard_productdocument pd on pd.product_id = p.id
where pd.document_id in (
    select id 
    from dashboard_datadocument
    where data_group_id = 196
);

commit;
