### ISSUE TITLE
QA report func use

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1524]
As a data curator
I want to QA the reported functional use field
So that I can ensure accuracy of extraction

https://factotum.epa.gov/qa/extractedtext/1496320/

Definition of Done:
The dashboard_functionaluse.report_funcuse field should be displayed in each chemical card on the /qa/extractedtext/ page

**Comment by mwfrost** [comment]
@kdionisio Does the functional use data need to be editable on this page?
