### ISSUE TITLE
Data Clean Up

### ISSUE THREAD

**Issue by dmlyons2** [HumanExposure/factotum#1532]
After 1514 is pushed run this query:

```sql
delete pd, p
from dashboard_product p
join dashboard_productdocument pd on pd.product_id = p.id
where pd.document_id in (
select id
from dashboard_datadocument
where data_group_id = 196
);

commit;

**Comment by dmlyons2** [comment]
Query Failed

```SQL
/* SQL Error (1451): Cannot delete or update a parent row: a foreign key constraint fails (`prod_factotum`.`dashboard_producttopuc`, CONSTRAINT `dashboard_producttop_product_id_598702d2_fk_dashboard` FOREIGN KEY (`product_id`) REFERENCES `dashboard_product` (`id`)) */
/* Affected rows: 0  Found rows: 0  Warnings: 0  Duration for 0 of 1 query: 0.000 sec. */
```

**Comment by dmlyons2** [comment]
@fang-yan-csra can you take a look at this?

**Comment by fang-yan-csra** [comment]
delete from dashboard_producttopuc
where id <> 0 and
product_id in (
	select pd.product_id
	from dashboard_productdocument pd
	where pd.document_id in (
	select id
	from dashboard_datadocument
	where data_group_id = 196
	)
);

delete from dashboard_producttotag
where id <> 0 and
content_object_id in (
	select pd.product_id
	from dashboard_productdocument pd
	where pd.document_id in (
	select id
	from dashboard_datadocument
	where data_group_id = 196
	)
);

delete pd, p
from dashboard_product p
join dashboard_productdocument pd on pd.product_id = p.id
where pd.document_id in (
select id
from dashboard_datadocument
where data_group_id = 196
);

commit;

**Comment by dmlyons2** [comment]
Completed
