### ISSUE TITLE
public list presence tag summary page

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1534]
As a non-logged in user
I want to be able to view the list presence tag summary page
So that I can assess available data

Definition of Done:
1. Please make /list\_presence\_tag/ page available to a non-logged in user
2. use  semicolon instead of a dash as the separator between list presence keywords (Currently a dash is used, which is confusing since the dash is also used _within_ a list presence keyword)

**Comment by mwfrost** [comment]
@kdionisio Should non-authenticated users be able to click the link to the list presence tag detail page? That page is currently login-only

**Comment by kdionisio** [comment]
ah yes, list presence tag detail page should be available to non-authenticated users!

**Comment by mwfrost** [comment]
Test URL: http://127.0.0.1:8000/list_presence_tags/
