### ISSUE TITLE
list presence tags list - full page

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1536]
As the Factotum product owner
I would like to have a page listing all List Presence tags 
So that users can browse through to access data of interest

Definition of Done:
- Creation of a list presence tag page, which lists all existing list presence tags, tag kind, and their definitions
- On new page, each list presence tag should be a hyperlink to the /list\_presence\_tag/ page
- New page should be accessible to non-logged in users
- On the Get Data page (/get_data/), include a button linking to the new page

**Comment by mwfrost** [comment]
Test URL: http://127.0.0.1:8000/list_presence_tags/
