### ISSUE TITLE
detected chemical flag

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1544]
As a data curator
I want to be able to notate whether a chemical record was detected or not detected
So that I can record and use this piece of data

Definition of Done:
- Applies to LM and LP data group types
- should not be a required field
- Detected/not detected flag applies to an individual chemical record
- User should have ability to include indication of detected/non-detected for each chemical record when doing the extracted text .csv upload
- Detected/Non-detected flag should appear on chemical cards on /datadocument/ page (perhaps as check box?); field should be editable on chemical card
- Detected/non-detected flag should appear on chemical cards on /qa/extractedtext/ page, and should be editable

**Comment by mwfrost** [comment]
The new attribute should be added to the `RawChem` model, so that it can be inherited by both `ExtractedChemical` and `ExtractedListPresence`. Conditional logic will exclude it from other non-LP and non-LM displayes. 

A boolean field will not work, since this needs to be True, False, or Null.

**Comment by zachmunzenrider** [comment]
I've got this working pretty well locally, but I'd like to make sure I'm applying this functionality to the correct data group types.

In `views/data_document.py` we map group types to chemical forms like this:

```CHEMICAL_FORMS = {
    "CO": ExtractedChemicalForm,
    "LM": ExtractedLMChemicalForm,
    "FU": ExtractedFunctionalUseForm,
    "CP": ExtractedListPresenceForm,
    "HP": ExtractedHabitsAndPracticesForm,
    "HH": ExtractedHHRecForm,
}
```
We don't have an `LP` group type (as mentioned in the ticket). We do have `CO`, `CP`, and `LM` group types that look like they'd be good candidates for this new flag.

On top of that, we have a templates for displaying certain chemical cards called `co_co_chemical_cards.html`. This template gets used if the child is an ExtractedChemical or ExtractedListPresence,  but not if it's an ExtractedLMChemical

Kathie, can you confirm whether this new flag should apply to these three types--CO, CP, and LM?

**Comment by kdionisio** [comment]
Detected chemical flag should apply to LM and CP group types! Thanks!

**Comment by mwfrost** [comment]
@kdionisio - the `chem_detected_flag` field in the uploaded csv needs to use the following codes:
1 for "detected"
0 for non-detected
Blank for unknown

What is the best way to document this requirement?

**Comment by kdionisio** [comment]
link for demo: https://factotum-stg.epa.gov/datadocument/1374315/
