### ISSUE TITLE
upload large batches of product data

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1547]
As a data curator
I want to be able to programatically upload large batches of product data
So that I can push in batch product data that I am not able to upload through the UI

Currently attempting to upload large batches of product data (including product images) which are either timing out in UI upload, or are very limited in UI upload (due to limits on total image size user can upload at once and vast quantities of data which need to be uploaded).

Definition of Done:
Upload product data (including product images) via API
This needs to be an authenticated api call

**Comment by mwfrost** [comment]
Rather than creating separate serializers for LIST, FETCH, and CREATE, Kathie agrees that all three views should use the same fields listed in the upload csv template, rather than the subset of fields specified in #1318

**Comment by mwfrost** [comment]
This branch now uses a `create` method along with Michael's `bulk` creation method.
