### ISSUE TITLE
PUCs API

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1565]
As a user of the APIs
I want to retrieve meta data on PUCs
So that I can complete information received from other APIs

Definition of Done:
- Creation of PUCs endpoint
- Need to view for each dashboard_puc.id,
  - dashboard_puc.gen_cat
  - dashboard_puc.prod_fam
  - dashboard_puc.prod_type
  - dashboard_puc.description
  - dashboard_puc.kind

**Comment by michael-barbour** [comment]
**Question:**  Would you like to keep using the "level_n_category" or use the gen_cat, prod_fam, and prod_type as the naming?  This will only affect the way these fields will be shown on the API.

Previously:

- gen_cat was called level_1_category
- prod_fam was called level_2_category
- prod_type was called level_3_category

I'm also changing the filter to be in line with our other filters.  Let me know if this is a problem for some reason.

Old filter:

- filter[chemical]=dtxsid0001

New Filters (in line with our other filters):

- filter[sid]=dtxsid0001
- filter[chemical]=1

**Comment by kdionisio** [comment]
All of the above is good with me! I'm fine with still using the level_n_category terminology for the API.Thanks!
