### ISSUE TITLE
chemicals API - RID attribute

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1566]
As a user of the chemicals endpoint
I want to get a list of all RIDs in Factotum
So that I can get a list of all chemical records I need to retrieve information for

Definition of Done:
For chemicals endpoint, add dashboard_rawchem.rid as an attribute

**Comment by michael-barbour** [comment]
We talked about this briefly on pointing but adding an RID, either as an attribute or related resource, will probably be a bad design choice.  There is too high of a chance that an incredibly large number of curated chemicals are connected to a single True Chemical for us to be able to provide that data without pagination.

A more jsonapi appropriate solution would be to instead filter curatedChemicals down either by SID or TrueChemical id.  This would allow the data curators to see a paginated list containing relevent data regardless of endpoint.

A mock-up of the proposed response would look like
/chemicalInstance/?include=chemical&filter[sid]=DTXSID6026296
**_or_** /chemicalInstance/?include=chemical&filter[chemical]=8
```json
{
  "data": [
    {
      "id": "1",
      "type": "chemicalInstance",
      "attributes": {
        "rid": "DTXRID002",
        "name": "Water",
        "cas": "7732-18-5"
      },
      "relationships": {
        "chemical": {
          "data": {
            "type": "chemical",
            "id": "8"
          },
          "links": {
            "self": "__BASE_SERVER__/chemicalInstance/1/relationships/chemical",
            "related": "__BASE_SERVER__/chemicalInstance/1/chemical/"
          }
        }
      },
      "links": {
        "self": "__BASE_SERVER__/chemicalInstance/1"
      }
    }
  ],
  "included": [
    {
      "type": "chemical",
      "id": "8",
      "attributes": {
        "sid": "DTXSID6026296",
        "name": "water",
        "cas": "7732-18-5"
      },
      "links": {
        "self": "__BASE_SERVER__/chemicals/8/"
      }
    }
  ]
}
```

**Of note:**  This data for the most part is already in the API.  It currently exists off of compositions, chemicalpresence (pending rework), and functionalUses using a filter by either SID or TrueChemical id (sid shown below).  If multiple requests are acceptable we can keep the raw "curatedChemical" data slightly more obscured and reduce the number of top level resources.
e.g:

-  /compositions/?filter[sid]=DTXSID6026296
-  /functionalUses/?filter[sid]=DTXSID6026296
-  /chemicalPresences/?filter[sid]=DTXSID6026296 (when updated)

**Comment by michael-barbour** [comment]
I talked with Kathie about this.  The information the DataHub team needs are the RIDs in our database.  The chemicalInstance endpoint is an appropriate way of returning this data as it will display every raw chemical record in our database.  I am proceeding with the suggested solution.

The SID in our system is not a definitive source of truth, so filtering by that SID should be optional.  This wont be an issue with the way this endpoint is set up.

Some of our records have unassigned RIDs.  In order to filter these results out the query param of `filter[rid.isnull]=false`

**Comment by michael-barbour** [comment]
http://127.0.0.1:8001/chemicalInstances/?include=products,dataDocument,products.puc&filter[rid.isnull]=false

Above is an example of a set of query params that will return 

- chemicalInstances (all raw chems) filtered where RID is not "".
- The serialized related data document resource
- The serialized related product resource
- The serialized related true chemical resource
- The serialized related puc resource attached to the product resource
