### ISSUE TITLE
PMID

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1577]
As a product owner
I want to make consolidate the PMID field
So that it is consistently stored and able to be retrieved across all data group types for which it is applicable.

Currently, pmid field exists in both the dashboard_extractedlmdoc and the dashboard_extractedhpdoc models. The PMID stored in these two fields is the same PMID.

Also, PMID is applicable to other data group types beyond LM and HP (e.g., also applicable to LP data group type).

Definition of Done:
Consolidate PMID field as property of data document, applicable to documents in data group type LM, HP, and LP

**Comment by zachmunzenrider** [comment]
After team discussion, we agreed this needs to be refactored into the datadocument model, as it's a core attribute of a data document. Also, this will involve a data migration to preserve existing data.

**Comment by zachmunzenrider** [comment]
Sakshi - I've completed the back-end part of this ticket, consolidating the PMID field into the datadocument model. This ticket, however, doesn't specify what needs to happen on the front end. I propose we do the following, but please correct me if I'm going in the wrong direction:

1. Remove the PMID field from the modal pop-up forms for LM Docs and HP Docs
2. Add a PMID field to the Edit Datadocument form. We can easily set this up so the PMID form field only displays if the datagroup  is LM, HP, or LP, or it could just display for any type of datadocument.
