### ISSUE TITLE
LM study type

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1579]
As the literature monitoring data owner
I would like to change a label on study type
So that the selection of study type is more clear

Definition of Done:
For LM data group type, change the 'Non-targeted' study type to 'Non-targeted or Suspect Screening'

**Comment by mwfrost** [comment]
Note: changing the Choice field to allow this longer string will mean expanding the `ExtractedLMDoc.study_type` field size to 36 or 40 characters. That involves a migration.

**Comment by mwfrost** [comment]
Data Document 9 in the seed data is an LM type, and would work for testing this.
