### ISSUE TITLE
return weight fraction type via API

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1581]
As a user of the Factotum Compositions API
I want to know which weight fraction type corresponds to the data I am seeing in each composition record returned
So that I can appropriately interpret my data

Definition of Done:
'compositions' API should return weight fraction type for each composition record returned (dashboard_weightfractiontype.title, as identified by dashboard_extractedchemical.weight_fraction_type_id)

**Comment by mwfrost** [comment]
Test URL: http://127.0.0.1:8001/compositions/
