### ISSUE TITLE
product image display after API upload

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1594]
When a product image is uploaded via the products API, the image does not appear to display correctly

e.g. https://factotum.epa.gov/product/607024/

Definition of Done:
After uploading a product image via API, product image should display correctly on /product/ page

**Comment by larger-allison** [comment]
[product_api_test.zip](https://github.com/HumanExposure/factotum/files/4996423/product_api_test.zip)

**Comment by fang-yan-csra** [comment]
I'm able to create a product by modifying the attached script (change the image location to point to local file). Not sure why didn't work on production.

<img width="1341" alt="Screen Shot 2020-08-31 at 4 02 33 PM" src="https://user-images.githubusercontent.com/30635634/91763526-b52c5700-eba3-11ea-8c24-276d755fe6f8.png">

**Comment by kdionisio** [comment]
Hold - Kathie to test

**Comment by mwfrost** [comment]
Discussed during the sprint planning meeting. 

Dave suggested two things:
- a diagnostic step where we push a hotfix branch in with some print statements to help him debug the errors
- a change to the codebase that puts all newly uploaded images into a new directory, so they at least don't contribute to the folder bloat

The dev team will take some time to look at the problem and discuss it here, then will point next week.
