### ISSUE TITLE
creation of ingredients data model (8 pts)

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#161]
**Issue dependent on completion of #148 and #149**

As any user
I want to store a 'analysis' set of composition data
So that I can easily retrieve the analysis-ready data for use in data analysis and modeling, or for web services

Composition data = chemical ingredients in a product and their weight fractions (i.e., amount of the chemical in the product)
Analysis-ready data = data which has been cleaned and curated to be in consistent formats, and is ready for analysis or use in data models

Please create a new data model for 'ingredients.' The ingredients data model will include the following fields:
1. Product key 
There is a many-to-many relationship between the product data model and the ingredients data model
*required

2. DSSTox substance key
Data model created in #149 
There is a many-to-many relationship between the DSSTox substance data model and the ingredients data model
*required

3. lower_WF_analysis 
Analysis ready lower bound for weight fraction
*decimal(20,15), not required, restricted to values between 0-1 inclusive

4. central_WF_analysis
Analysis ready central tendency value for weight fraction
*decimal(20,15), not required, restricted to values between 0-1 inclusive

4. upper_WF_analysis 
Analysis ready upper bound for weight fraction
*decimal(20,15), not required, restricted to values between 0-1 inclusive

5. wf_type
Text, one of a pre-defined 'type' for weight fractions (note that weight fraction type was created and defined in #148); 

Definition of Done:
1. ingredients data model created with fields as described above

*Note, Kathie can give a summary of the various WF values (raw/analysis-ready, lower bound/upper bound/central tendency value), what they mean, and how they relate to each other when she returns so everyone understands the big picture of where we are going with this

**Comment by zachmunzenrider** [comment]
@kdionisio it occurs to me that if the WF_analysis values must be between 0 and 1, it's counter-intuitive to have the fields be decimal(20,15). I'm going to make them decimal(16,15) but please tell me if there's a reason I shouldn't do that! Thx

**Comment by kdionisio** [comment]
That’s is fine, thanks!
