### ISSUE TITLE
extractedchemical to extractedcomposition

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1610]
As a product owner
I want to change the name of the dashboard_extractedchemical model
so that it is consistent with other models and does not cause confusion

Name of the current model is not consistent with other 'extracted' models and causes confusion

Definition of Done:
- Change all references to dashboard_extractedchemical to dashboard_extractedcomposition

**Comment by BryanMG957** [comment]
Found this blog post that could be helpful for this ticket:

https://hacksoft.io/renaming-models-in-django-without-heavy-data-migrations/#the-execution
