### ISSUE TITLE
product URL displayed in UI

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1613]
As a Factotum curator
I want to be able to edit and view the URL associated with a product in the UI
So that I can enter or use this piece of data

Currently there exists a dashboard_product.url field, however there is no way to edit or view this field in the UI

Definition of Done:
- ability to edit dashboard_product.url on https://factotum.epa.gov/product/edit/367981/ page
- hyperlink to the dashboard_product.url URL from the https://factotum.epa.gov/product/367981/ page
    - hyperlink should appear as an external link icon, using the same icon used here https://factotum.epa.gov/datadocument/1261122/ to link to the external data source
  - icon should only be visible if the dashboard_product.url field is populated
  - icon should have a tool tip hover which reads 'View product source (external)'
  - icon can be in line with the trash can and pencil icons on the upper right of the /product/ page

**Comment by mwfrost** [comment]
The link should open in a new tab
