### ISSUE TITLE
LP tag navigation

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1615]
As a Factotum user
I want to easily see the definition of a list presence tag and navigate across list presence tags
So that I can more easily explore data to find data of interest

Definition of Done
On the list presence tag summary page (https://factotum.epa.gov/list_presence_tag/457/), each list presence tag displayed in the 'Sets' table:
  - have a tool tip hover which displays the definition of that list presence tag
  - should be a hyperlink to that list presence tag summary page (https://factotum.epa.gov/list_presence_tag/457/)

**Comment by mwfrost** [comment]
For sprint demo:
http://127.0.0.1:8000/list_presence_tag/457/
