### ISSUE TITLE
search on text for LP keyword

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1619]
As a Factotum user
I want the search to look within a list presence tag/keyword
So that I can easily find what I am looking for in search results

Currently, the search appears to search only on the full list presence tag. Thus if a user searches for a word or phrase that is a portion of a tag, the tag is not returned.

Example - search on animal does not return the 'animal_feed' tag:
https://factotum.epa.gov/search/tag/?q=YW5pbWFs

Similarly a search for 'animal feed' does not return the 'animal_feed' tag:
https://factotum.epa.gov/search/tag/?q=YW5pbWFsIGZlZWQ=

But a search on 'animal_feed' does return the 'animal_feed' tag
https://factotum.epa.gov/search/tag/?q=YW5pbWFsX2ZlZWQ=

Definition of Done:
Search searches for matching text within a list presence tag, rather than searching only on the full list presence tag

**Comment by Sakshi-Handa** [comment]
Looks like this is still relevant, despite changes made in #2070. Maybe we need to revisit how the LP tags are searched. 
Additionally, searching for 'animal' should result in 4 relevant LP Tags. But the elastic search only returns the 'pharmaceutical' tag.
![image.png](https://images.zenhubusercontent.com/5f318c2978fa23cbc1a57b71/b8c10d1c-d6b4-4eb6-a38c-8a1aa1727123)
