### ISSUE TITLE
Instructions for Detected Chemical Flag

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#1625]
As a data curator
I would like to display instructions for using the detected chemical flag
So that it is clear how to code the chemical records when extracting data from documents. 
 
Definition of Done:
•	Applies to LM and LP data group types
•	On the /datagroup/ page, under the Extracted tab, add list of codes that apply to the chem_detected_flag field to be used when uploading extracted text.
•	Use the "I" icon and italicized text formatting for instructions.

**Comment by mwfrost** [comment]
@Sakshi-Handa We refer to data groups that contain list presence records as "CP" types, for "chemical presence." "List presence" is only used at the extracted chemical level. I've explained the difference to the dev.

**Comment by kdionisio** [comment]
*Slight change - ticket needs to only apply to CP data group types. LM data group types do not have the ability to be uploaded in batch thus do not need these instructions

**Comment by mwfrost** [comment]
To demo, use a list presence data group with partial extraction:
http://127.0.0.1:8000/datagroup/189/
