### ISSUE TITLE
Bulk Delete Products associated with Data Group

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#1626]
As a data curator
I would like to efficiently remove all products within a data group
so that I can quickly and easily remove all product entries associated with a data group.

Currently, products within a data group must be deleted individually, or the entire data group has to be deleted to remove the product records. This is a problem when we need to redo extraction scripts and reupload product data, because we would create duplicate records for all products in a data group. 

Definition of Done:
•	On the /datagroup/ page, for composition documents (i.e. CO data group type), with existing products, add a trash can icon above the products column
•	After selecting the trash can icon, the user should receive a confirmation of action, including data group name and number of products that will be deleted.  
•	Action would result in the removal of all product records associated with the documents in this data group.
•	Trash can icon should include a ‘hover’ with text ‘Delete all product records associated with this data group’

**Comment by mwfrost** [comment]
This process needs to be implemented as a Celery task.

**Comment by mwfrost** [comment]
To demo:
http://127.0.0.1:8000/datagroup/37/
Create the products using the Bulk Create button, then delete them.
