### ISSUE TITLE
Error when Deleting Data Groups

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#1627]
There is an error given when attempting to delete data groups from the data group page.  
 
On the /datagroup/ page, the trashcan icon in the top right corner should be able to delete the entire data group. Once pressed, it gives a confirmation screen. After confirming, the production version of factotum gives back "502 Bad Gateway" From <https://factotum.epa.gov/datagroup/delete/89/> 

The data group was not able to be deleted in Factotum Stage as well, returning :
OperationalError at /datagroup/delete/89/
(1054, "Unknown column 'dashboard_rawchem.chem_detected_flag' in 'field list'")
 https://factotum-stg.epa.gov/datagroup/delete/89/
*See attached pdf here.
[https://app.zenhub.com/files/99837877/5dfc5b82-5a27-4919-ba52-1af06e84a430/download](https://app.zenhub.com/files/99837877/5dfc5b82-5a27-4919-ba52-1af06e84a430/download)
 
Definition of done:
Selecting the trashcan icon in the top right corner of the /datagroup/ page and confirming should result in the data group being deleted.

**Comment by zachmunzenrider** [comment]
This is happening because the latest Django migration hasn't been run on stage. An easy fix, but someone with stage access needs to do it.

**Comment by kdionisio** [comment]
hold to check with Dave on migration issues before pointing

**Comment by Sakshi-Handa** [comment]
Issue was resolved. #1687 added requirement for confirmation before deleting a datagroup.
