### ISSUE TITLE
Group Components in Composition QA

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#1638]
As a data curator
I would like to group the chemical record cards for related components together on the QA page for a composition document
So that it is easier to check the chemical records in each component of a product. 
 
Ex. https://factotum.epa.gov/qa/extractedtext/1550033/
The chemical record cards on this QA page have 'components' on the right side of the card; 
"polyvinyl chloride resin", "pigment", "aluminum". The chemical cards are not ordered by component, which makes it difficult to check the chemical records as they appear in the document, where they are grouped by component. 
 
Definition of Done:
•	Applies to composition QA documents
•	For QA documents with components, order chemical cards by component, with components listed alphabetically; within a component order chemical cards by the ranking of the chemical.

**Comment by mwfrost** [comment]
Note that changing the order of QA chemical records might break some of our selenium tests if they depend on indexed locations of cards in the page.

**Comment by mwfrost** [comment]
To demo component sorting, per ticket:
http://127.0.0.1:8000/qa/extractedtext/1550033/

To demo intra-component rank sorting:
http://localhost:8000/qa/extractedtext/279872/
