### ISSUE TITLE
format faceted search results (5 pts)

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#164]
As Karyn the curator
I want to view faceted search results in a tabular layout with basic search/sort capabilities
So that I can more easily absorb information from the search results, and organize search results for further analysis.

Please change layout of faceted search results to be in a table format with basic functionality (pagination,
 search within table, etc.) (e.g., implement data tables, or similar)

**Comment by mwfrost** [comment]
The faceted search returns heterogeneous objects, and the table can only show attributes common to all the objects. That should not be a problem, since the attributes we are returning with search results can be stacked and shown together.

**Comment by kdionisio** [comment]
**edited to note searching/sorting capability within table is not required at this time.
