### ISSUE TITLE
Add New Columns for Composition QA Summary Page  

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#1652]
As a data curator,
I would like to add columns on the Documents table on the QA Summary page for Scripted Composition Groups,
So that I can easily see more details about the document once QA is complete. 
 
Ex. https://factotum.epa.gov/qa/compextractionscript/52/summary
Since the /qa/compextractionscript/#/ page is not accessible after QA is complete, We would like to display useful information in the table on the QA Summary page, which is always accessible to curators. 
We would like a new column for “Data Group”, to indicate what data group the document belongs to, as some scripts are linked to multiple data groups.
A "Chemical Records” column, to show the number of chemical records in the document, to help keep track of records after QA is completed. 
A "Date Updated" column, to show when the document was last updated. 
 
![QA Summary Comp.JPG](https://images.zenhubusercontent.com/5f318c2978fa23cbc1a57b71/09ef0524-385b-4e7d-8aeb-f3fcc1eb7c10)

Definition of Done:
•	Applies to the /qa/compextractionscript/#/summary
•	To the left of the "document' column, add a new column with the header "Data Group" and fill each row with the data group each document is associated with. 
•	To the left of the "Audit Log" column, add a new column called "Chemical Records", that displays a count of the total number of extracted chemical records associated with each document. 
•	Add functionality to sort on each of the new columns.

**Comment by Sakshi-Handa** [comment]
Edited definition of done:
removed "Updated date" column, not needed because audit log represents the date

**Comment by Sakshi-Handa** [comment]
Please continue using data-tables for display, 
no need to convert table to AG Grid

**Comment by mwfrost** [comment]
To demo:
http://127.0.0.1:8000/qa/compextractionscript/52/summary
