### ISSUE TITLE
Update Composition QA Group Page Layout 

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#1653]
As a data curator,
I would like to clean up the Composition QA Group page (/qa/compextractionscript/#/) , 
So that I can see information more relevant to the QA process for each document within a QA group. 
 
I want to remove and add columns to clean up the table corresponding to each QA Group. 
The columns "ID" and "Revision number" are distracting, so can be removed from the table display.
The 'document date' column currently represents a date extracted from the document (e.g. when the manufacturer wrote the SDS), while it would be more useful to curators to know when the document was last updated.  
**(Updated seems to refer to changes to document details, There doesn't seem to be any date that shows when chemical records in a document were last updated?)**
It would also be helpful to have a count of records in each document before starting to QA, to prioritize workflows. 
Ex. https://factotum.epa.gov/qa/compextractionscript/341/
 
![QA Group Edits.JPG](https://images.zenhubusercontent.com/5f318c2978fa23cbc1a57b71/c94889c4-0665-45d2-b563-3feb71acf624)

Definition of done:
•	Remove the columns and values for "ID" and "Revision Number" from the /qa/compextractionscript/#/ page
•	For the "Document Date" column, replace the column header with "Updated at" and the row values with 'dashboard_extractedtext.updated_at'
o	Set the Date and Time formatting like this: "Nov. 18, 2019."
•	To the left of the "QA Checked" column, add a new column called "Chemical Records", that displays a count of the total number of extracted chemical records associated with each document. 
o	Add sorting functionality to the new "Chemical Records" column and Updated Date Column.

**Comment by Sakshi-Handa** [comment]
Updated ticket: Convert table to AG grid, and 
removed time  from new "date updated" column

**Comment by Sakshi-Handa** [comment]
Updated Definition of Done: removed AG Grid requirement
Please continue using data-tables for display,

**Comment by Sakshi-Handa** [comment]
Realized I would also like ability to sort on the date column as well, added to Definition of done.

**Comment by mwfrost** [comment]
http://127.0.0.1:8000/qa/compextractionscript/341/
