### ISSUE TITLE
Add Extraction Script Date to Composition QA main page

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#1654]
As a data curator,
I would like to display the date the extraction script was last updated to the Composition QA, 
So that I can easily tell the age of the extraction script and prioritize newly added groups for QA. 
 
![QA Script Date.JPG](https://images.zenhubusercontent.com/5f318c2978fa23cbc1a57b71/f41c1fb1-a1ed-4b96-9c7a-c274d19156a2)

Definition of done: 
•	Applies to https://factotum.epa.gov/qa/compextractionscript/ page. 
•	To the right of the "Extraction Script" column, add a new column with the header "Script Updated", and populate with 'dashboard_script.updated_at'
•	Dates are formatted like this: "Nov. 18, 2019"
•	Add functionality to sort this new column.

**Comment by Sakshi-Handa** [comment]
updated definition of done: just the date, no time needed.

**Comment by Sakshi-Handa** [comment]
Please continue using data-tables for display, 
no need to convert table to AG Grid

**Comment by mwfrost** [comment]
For demo:
http://127.0.0.1:8000/qa/compextractionscript/

Show correct sorting
