### ISSUE TITLE
Bug sorting /chemical/ product table

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#1674]
I received an error when attempting to sort by PUC column on the Products table at the bottom of the /chemical/ page. 

Ex. https://factotum-stg.epa.gov/chemical/DTXSID9020584/
 In the table "Products Containing Ethanol", the chemical Ethanol is present in over 10k product entries. Pressing the sort arrow results in a Datatables error, and does not perform the action. 

![Products Table Ethanol.JPG](https://images.zenhubusercontent.com/5f318c2978fa23cbc1a57b71/8f248b96-c4c8-41ab-901c-ff06fd6460af)

This error might have shown up after completing ticket #1617 (display of product entries when sorting by PUC). The table worked for the chemical given in the #1617 example,, but gave an error for others chemicals. 

Also had an issue with the order it is sorting.  When the arrow is pressed once, it returns a list of blanks (products with no PUC assigned), then PUCs from A-Z. I would like blanks to appear at the end, after all assigned PUCs.
Ex. https://factotum.epa.gov/chemical/DTXSID4020533/ 

![Products Table 1-4 Dioxane.JPG](https://images.zenhubusercontent.com/5f318c2978fa23cbc1a57b71/e23a5cb4-5ed1-4321-b971-d1e68f5c55cc)

Definition of Done:
On /chemical/ page 'Products Containing Chemical' table, the PUC column sorts alphabetically by PUC name, from A-Z then lists 'blank' products without PUCs.

**Comment by mwfrost** [comment]
To demo:
http://127.0.0.1:8000/chemical/DTXSID9020584/
