### ISSUE TITLE
Bulk Assign PUCs for Predicted Products

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#1675]
As a data curator
I want products that have been assigned to PUCs through the model prediction method to still be available through the "Bulk Assign Products to PUCS" method, 
So that I can use the higher validation method (Bulk Assign) to assign products to PUCS  

Recently, large quantities of products were assigned to PUCS using the new predicted model for formulation PUCs.
Now those predicted products do not show up in the "Bulk Assign Products to PUCs" list, since the Bulk Assign method only shows products _with NO PUC assigned._ 
Many of the products assigned via the predicted method were placed in the incorrect PUC. So we want to reassign them through the higher validation level method of Bulk Assign. 
Bulk Assign Curation Page: https://factotum.epa.gov/bulk_product_puc/

Can we indicate whether a product has already been assigned via the 'prediction method' ?
Ideas: new table column indicates predicted products, or ability to filter search to include products assigned through predicted method. 

Definition of Done:
	• Products assigned through the 'prediction method' appear for PUC categorization on the /bulk_product_puc/ page

**Comment by mwfrost** [comment]
The bulk assignment table shown here should only include unassigned products (`.classification_method = None` ) and "AU"-assigned products (`.classification_method = "AU"`) because both of those methods are less reliable than "BU".

**Comment by Sakshi-Handa** [comment]
In definition of done, also include some indication of whether products have been assigned through AU "Automatic" or are unassigned.

**Comment by Sakshi-Handa** [comment]
As discussed in sprint review, additional criteria for completion:

Add columns to display previously assigned PUCs and Classification method
Filter the products to include no assigned PUCs and AU assigned PUCs, from either query by product or by dg/rc.

**Comment by mwfrost** [comment]
The PR includes instructions for demonstrating the ticket with the seed data. To demonstrate the ticket with production data, filter the page for a keyword like "Fuchsia:"
http://127.0.0.1:8000/bulk_product_puc/?q=Fuchsia

Go to the detail view of the first product:
http://127.0.0.1:8000/product/20788/

Use the "Link Product to PUC" page to manually assign a PUC to the product.
http://127.0.0.1:8000/product_puc/20788/

Returning to the bulk_product_puc page, that product no longer appears available for bulk assignment. 

But if you change the assignment method from "MA" to "AU", the product becomes available again.

`UPDATE `prod_factotum.dashboard_producttopuc SET classification_method = 'AU' WHERE (product_id = '20788');`

The PUC that was just manually assigned (and changed to AU) now appears in the "Predicted PUC Assignment" column, and can be overridden with the bulk assignment tool.
