### ISSUE TITLE
Move Data Group CODE Menu

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#1692]
As a data curator, 
I would like to move the location of the Code Menu for creating new data groups,
So that I am more easily able to see all available document type codes when creating a new data group. 

When creating a new data group, curators need to input the 2-digit document_type code as a column in the upload .csv file. 
Currently the menu with all of these codes is located as a dropdown list at the top of the toolbar on the datasource/#/datagroup_new/ page. (CODE Menu in gray.)
Ex. https://factotum.epa.gov/datasource/102/datagroup_new/
It is not obvious where the code menu is located. 
It is also difficult to navigate, as the menu does not scroll. So you are not able to see all of the codes for a given document type. 
It would also be helpful to include the definitions for each code, so curators can know when each code is appropriate to use. 

Definition of Done:
	• Move the Code menu from the toolbar at the top of the datasource/#/datagroup_new/ page to below the 'Create New Data Group…' form (can be below the instructions for Required CSV Headers)
	• Ability to click to expand on each Data group type (composition, chemical presence list, functional use) to see the code table 
	• Include the following columns in each table:
		○ Code (the 2 digit code ex. AC)
		○ Title (the corresponding name for the document type Ex. Academic)
		○ Description (the definition of the document type code. Ex. 'Report, etc. issued by a university')

**Comment by Sakshi-Handa** [comment]
use description located in the admin panel (document type - description) field

**Comment by zachmunzenrider** [comment]
The CODE menu doesn't seem to be loading in my browser. . . .

![image.png](https://images.zenhubusercontent.com/5be47c474f4473195308604f/ca08c07b-7130-4527-9574-90a3b4ddf2f3)
