### ISSUE TITLE
Delete Extraneous Products from Database

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#1695]
I would like to remove 2 products from the database directly because they cannot be removed through the UI, and also check on how they were created. Taylor found 2 artifacts in the database that are not linked to data documents. This affects the Factotum stats page in showing 1 extra product and 2 extra 'Products Linked to PUCs' than we really have. This ticket can serve as documentation for the removal and an investigation into how these products were created. 

From Taylor:
'Product ID: 557841, 571379 are extraneous products which show up in the dashboard_product and dashboard_producttopuc tables. One of them is just a test product that was left over from early development, so not a big deal (although it’s assigned to a list presence doc when that’s not technically possible). The other is concerning because it’s a failure of a “delete product” process where the product was deleted, but the producttopuc record remained. So it could point to a latent error in that process.' 

Definition of Done:
• Check both product IDs to confirm they are artifacts, and can be safely removed from the database.
• Check that products can only be assigned to Composition type data documents
• Check that producttopuc record is deleted when product is deleted
Delete both product records, so that count is removed from the Factotum product statistics page

**Comment by mwfrost** [comment]
This query confirms that all the products in the database are matched to documents in Composition group types:
```
select count(p.id), dgt.code, dgt.title
 from dashboard_product p
left join dashboard_productdocument pd on p.id = pd.product_id
left join dashboard_datadocument d on pd.document_id = d.id
left join dashboard_datagroup dg on d.data_group_id = dg.id
left join dashboard_grouptype dgt on dg.group_type_id = dgt.id
GROUP BY dgt.code, dgt.title;
```

If you run it on the production server and see anything other than a single "CO: Composition" row, it means something has gone wrong.

**Comment by Sakshi-Handa** [comment]
Closing Issue. 
product with Product_id 571379 was deleted, while only the product_to_puc relationship exists for 557841.
