### ISSUE TITLE
Assign Multiple Detected Chemical Flags

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#1708]
As a data curator,
I would like to assign the detected chemical flag to multiple chemical records at once,
So that I can quickly manually assign chemical records as 'detected' or 'not detected'.

The detected chemical flag was created in #1544. It created the chem_detected_flag field and allows for curators to add the detected label to chemical records. Currently we add labels manually to each record. I would like the ability to select multiple chemical records and assign them to detected or not detected (Yes or No). 
I would like similar functionality to what is already implemented with "List Presence Keyword" tagging, where multiple records can be selected and assigned keyword tags. 
Ex. https://factotum.epa.gov/datadocument/1496345/ 
This document has 10 chemical records, with some detected and nondetects as indicated by the LP tags. 
We would like to quickly assign these records by selecting multiple at once, and labeling them with the "yes' or "no" flags. 

This is even more important when there are large amounts of detected chemicals, as in this example with 72 records:
https://factotum.epa.gov/datadocument/1496317/

![list presence keyword tagging.JPG](https://images.zenhubusercontent.com/5f318c2978fa23cbc1a57b71/5b6a0b3b-5ce2-4966-b7a4-bc1daa987783)

Definition of Done:
	• Applies to LM and LP data groups, on the /datadocument/# page
	• Apply functionality to a new modal button, titled "Detected Chemical Flag"
	• Use existing functionality within "List Presence Keywords" 
	• Ability to select "Yes" or "No" or "Unknown" and assign selected chemical records to the chem_detected_flag field
	• Ability to save selections

**Comment by michaelhuffman-gdit** [comment]
Modified requirements after talking with Sakshi

**Comment by mwfrost** [comment]
The product owner has agreed to accept this ticket, with the functionality only applied to List Presence documents. The Literature Monitoring documents will get this new feature on a subsequent ticket.
