### ISSUE TITLE
PUC Reconciliation 

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#1727]
As a data curator
I would like to only see products with Different PUCs assigned through different methods on the /product_puc_reconciliation/ page
So that I can see instances where there are conflicts in the PUCs assigned through different methods. 

Currently there are examples within the Resolve PUC Conflicts table of products that were assigned the same PUC through different PUC Assignment Methods. It looks like the table shows all product IDs with PUCs assigned through more than one Assignment Method. 

Ex. https://factotum.epa.gov/product_puc_reconciliation/
"Ultra Power Plus Laundry Detergent" is assigned to "Cleaning products and household care - laundry and fabric treatment - laundry detergent" through 'Manual' and 'Automatic' assignment. This is good. It shows that the model and our curators are in agreement, and have assigned the same PUC to the product. We don't need to change or reconcile this product, So this product ID does not need to appear on the PUC Reconciliation table. 
Currently, there are 172,000 entries on this table. If we remove these instances where the PUC was assigned consistently between different methods, then hopefully the table will be smaller. 
But there are also entries like Product ID 1843 (wood cleaner), where there are 3 different assignment methods. In this case, the PUCs assigned were not consistent for all three assignment methods. So this product ID should appear on the table, so we can determine which PUC is most appropriate for the product. 

![PUC Reconciliation.JPG](https://images.zenhubusercontent.com/5f318c2978fa23cbc1a57b71/294614ad-36a5-4b62-b023-2aa7fb1d71fa)

Definition of done:
• Applies to the table on the /product_puc_reconciliation/ page
• Only show product ID entries in table when the text in the 'PUC' column is different for each 'PUC Assignment method'.
• When there are 2 different assignment methods (i.e. Manual and Automatic), remove product ID when both PUCS assigned are the same.
When there are 3 or more different assignment methods (i.e. Manual, Manual Batch, Automatic), only remove the product ID when ALL PUCs assigned are the same.

**Comment by mwfrost** [comment]
This refines #1358

**Comment by mwfrost** [comment]
Change the queryset in `views/ajax.py`:

```
    def get_initial_queryset(self):
        dupes = (
            ProductToPUC.objects.values("product_id")
            .annotate(puc_count=Count("puc_id"))
            .filter(puc_count__gte=2)
        )
        qs = ProductToPUC.objects.filter(
            product_id__in=Subquery(dupes.values("product_id"))
        ).order_by("product_id")
        return qs
```
