### ISSUE TITLE
 Access Incomplete QA Groups

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#1728]
There is an issue with accessing QA groups on the Composition QA. I think there was a ticket to resolve this but I'm not sure if it was changed the logic for QA Status. (#1609)

The problem is when a curator is starts working on QA (pressing the "Start QA" button on the page), and completes QA for a few documents. Then when they leave the QA incomplete (without checking all of the documents in the QA Group), they are locked out of the QA Group /qa/compextractionscript/#/ page. The QA Main /qa/compextractionscript/ page says "QA Complete" for that QA Group, even though the "Percent QA Approved" column is less than 100% completed. This is an issue because curators can't get back to the QA page for a specific group because the "Continue QA" button disappears.
For example, this happens whenever there are fewer than 100 documents in a group and the 'Percent QA Checked' column gets above 20%. The QA status should only be "QA Complete" when 100% of the documents in the QA group are approved. 

For Composition QA, If there are less than 100 documents in the QA group, all documents must be QA approved. 
If there are more than 100 documents in a QA group, the QA Group consists of a random 20% of the documents. 
(i.e. if there are 2000 extracted text documents, the QA group has 400 documents that need to be approved. So percent QA Checked reaches 100% when all 400 documents are approved.)

Ex. https://factotum.epa.gov/qa/compextractionscript/ 
For the Extraction Script 'Church & Dwight' 
The "Percent QA Checked" column says only 26% has been completed. But the QA Status says "QA Complete". From the QA Summary it looks like there are 34 documents total, and only 9 have been QA approved. The QA Group needs to have all 34 documents checked, because there are less than 100 total documents in the group. 

Definition of Done:
• Applies to the Composition QA page, /qa/compextractionscript/
The QA Status should show "Continue QA" for groups that have started QA but have less than 100% QA completed in the "Percent QA Checked" column

![church and dwight.JPG](https://images.zenhubusercontent.com/5f318c2978fa23cbc1a57b71/d79fe9c9-ce94-4bdd-a0f2-5c3ae967d9e0)

**Comment by mwfrost** [comment]
@Sakshi-Handa The origin of this problem is the ambiguity in the "Percent checked" metric. We have gone back and forth on what the denominator should be in different places.

In some future ticket, we should clarify that the percentage shown in this table is the percentage **of the randomly-sampled QA Group records,** not the percentage of all the script's extracted text records.
