### ISSUE TITLE
Document and Organize Page Navigation

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#1747]
As a data curator, 
i would like to know what pages are available on factotum
so i can access available pages. 

definition of done:
list of webpages and description of navigation path.

**Comment by michaelhuffman-gdit** [comment]
Wiki page made under the name Web Page Listings

**Comment by mwfrost** [comment]
https://github.com/HumanExposure/factotum/wiki/Web-Page-Listings
