### ISSUE TITLE
Pagination of Chemical Presence Data Documents

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#1773]
As a factotum user
I would like to improve the performance of data document pages
So that I can quickly navigate through chemicals of interest on pages with many chemicals. 

For some data documents with large amounts of chemical records, it takes some time to load the page, and is slow to respond to user input. Most data documents have less than 10 chemicals, so we don’t run into this often. But for the documents with 1000+ chemicals, page performance is impacted. 

Ex. https://factotum.epa.gov/datadocument/1557970/
This chemical presence document has 6000+ chemicals. It takes over a minute to load the page, and it is slow to select the chemical cards and assign keywords. 

Definition of done:
	•Paginate  /datadocument/# page for chemical list presence documents to return 500 chemicals at a time.

**Comment by Sakshi-Handa** [comment]
Discussed server-side pagination, to help with loading of data document pages with large amounts of chemical cards. 
Number of chemicals returned at once is flexible, whatever performs better. 
For the most part, documents will have less than 100 chemicals.

**Comment by zachmunzenrider** [comment]
Sakshi, how would you like to handle the current "Select All/Select None" functionality for paginated sets? It would by far be easiest to have it continue to act on just the cards currently displayed on the page. If we need it to refer to _all_ cards, whether currently displayed or not, that is also doable, but would be a good bit more effort.

![image.png](https://images.zenhubusercontent.com/5be47c474f4473195308604f/08c94c0a-0519-4550-8607-2bd5cbf16227)
