### ISSUE TITLE
Data Groups Page Performance

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#1774]
As a data curator
I would like to improve the performance of the datagroups page
So that I can easily search the list of Factotum datagroups 

https://factotum.epa.gov/datagroups/
The data groups page was recently updated to AG Grid. 
The page is slow to load, and returns an 'page unresponsive' message when attempting to interact with the table. 
It eventually loads after about a minute, and the table functionality works well.  

Definition of done:
Improved performance and responsiveness of /datagroups/ page

**Comment by mwfrost** [comment]
Here's the expensive query that takes too long with production data:
```
SELECT 
    dashboard_grouptype.title,
    dashboard_datagroup.name,
    dashboard_datagroup.data_source_id,
    dashboard_datasource.title,
    dashboard_datagroup.id,
    auth_user.username,
    dashboard_datagroup.downloaded_at,
    dashboard_datagroup.download_script_id,
    dashboard_script.url,
    dashboard_script.title,
    COUNT(dashboard_extractedtext.data_document_id) AS num_extracted
FROM
    dashboard_datagroup
        INNER JOIN
    dashboard_grouptype ON (dashboard_datagroup.group_type_id = dashboard_grouptype.id)
        INNER JOIN
    dashboard_datasource ON (dashboard_datagroup.data_source_id = dashboard_datasource.id)
        INNER JOIN
    auth_user ON (dashboard_datagroup.downloaded_by_id = auth_user.id)
        LEFT OUTER JOIN
    dashboard_script ON (dashboard_datagroup.download_script_id = dashboard_script.id)
        LEFT OUTER JOIN
    dashboard_datadocument ON (dashboard_datagroup.id = dashboard_datadocument.data_group_id)
        LEFT OUTER JOIN
    dashboard_extractedtext ON (dashboard_datadocument.id = dashboard_extractedtext.data_document_id)
GROUP BY dashboard_datagroup.id , dashboard_grouptype.title , dashboard_datasource.title , auth_user.username , dashboard_script.url , dashboard_script.title
ORDER BY dashboard_datagroup.name ASC
```

**Comment by mwfrost** [comment]
![datagroups](https://user-images.githubusercontent.com/201835/106035211-b39a8880-6088-11eb-9a96-792f9b94912e.png)

Maybe the sluggish performance is caused by the AGGrid having to calculate the row height for each record. If we force a common height instead of using`.getPreferredHeightForRow` it will speed up.

**Comment by Sakshi-Handa** [comment]
Page loads <5 seconds. Links take additional time to load. Sometimes gives 'page unresponsive' message.
