### ISSUE TITLE
Functional Use QA Pt 5 (Link QA Pages)

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#1781]
Link all the Functional use pages together

As a product owner, 
I would like to connect all newly created functional use pages
so that curators can easily navigate the FU workflow. 

Definition of Done:
• Add link from the 'QA' menu on nav bar to the 'Func. Use - Ext. Script' Page created in pt 1. #1777
• Add links to the QA Summary and QA group page to the 'Func. Use - Ext. Script' Page
• Add link to the /qa/extractedtext/# page to the QA Group page created in pt 2. #1778

**Comment by fang-yan-csra** [comment]
All the links are in place during development. No further work needed.
