### ISSUE TITLE
 Functional Use Categories Index Page

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#1790]
As a factotum user, 
I would like to see a list of functional use categories
So that I can view and search the available categories and their definitions. 

Similar to the /list_presence_tags/ page listing all available LP keywords, I would like a page that lists the name and definition of all functional use categories. A future ticket will create pages for each functional use category, and this will serve as an 'index page' that will allow users to navigate easily to those pages. 

Definition of done:
	• A new page for Functional Use Categories, displays titles and descriptions 
	• Use Ag Grid package
	• Add a link to /get data/ page, next to 'download functional use categories' button
	• Viewable to both logged-in and guest users

**Comment by mwfrost** [comment]
Add functional use records to seed data
