### ISSUE TITLE
Replace 'Cleaned Functional Use' with 'Functional Use Category'

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#1815]
We are moving away from the 'cleaned functional use' field, and combining with functional use category. 
So we can remove the cleaned functional use field wherever it appears on factotum UI. 

Appears as a requirement for adding cleaned functional use .csv file on the /datagroup/ page

Upload clean functional use data
https://factotum.epa.gov/datagroup/190/

**Comment by zachmunzenrider** [comment]
Sakshi, I wanted to verify that this ticket is NOT calling for cleaned functional use to be removed from the database too, correct? It's only to make it irrelevant to the UI?
