### ISSUE TITLE
Functional Use Table on /chemical/ page

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#1827]
As a Factotum user, I would like to view a functional use summary table on the /chemical/ page
So that I can see all information on functional uses related to a particular chemical 

Ex of chemical page.
 https://factotum.epa.gov/chemical/DTXSID0020232/

Definition of Done:
• Add a new table to the /chemical/# page for 'Functional Uses associated with [chemical]'
• Table Columns include:
	○ Document Type (can be Composition, Chemical presence, Functional Use)
	○ Associated Document (link to /datadocument/ page)
	○ Reported functional use
	○ Harmonized functional use (link to functional use detail page (created in #1825))

**Comment by michael-barbour** [comment]
Added a comment to #1825 for last bullet point linking.  The link to the Functional Use detail page will be added when that ticket is completed.
