### ISSUE TITLE
Search Bulk Assign PUCs by Manufacturer and Brand

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#1846]
As a data curator
I would like to search the table on /bulk_product_puc/ page by the Manufacturer and Brand name columns
So that I can easily categorize products based on these fields

Currently, the search applies to only the product names. I would like to search the other fields, so I can find related products without having to know a specific product name. 
For example, searching 'FISHER SCIENTIFIC' to get all products from that manufacturer. So I don’t need to know every product name, but I know they all belong in the "laboratory supplies" PUC. 

Definition of done:
	• Applies to the search functionality on the /bulk_product_puc/ page
	• Expand the search to query product details for 'Manufacturer' and 'Brand' name, in addition to the 'product name'

**Comment by mwfrost** [comment]
Demo notes: searching for "Bostik inc" will return many records where the search string only appears in the manufacturer field.

`http://127.0.0.1:8000/bulk_product_puc/?q=bostik+inc`

**Comment by mwfrost** [comment]
With the seed data, search "Henkel" to see a Manufacturer hit, and "Reddi" to see a Brand Name hit.
