### ISSUE TITLE
Extraction Complete for Habits and Practices

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#1859]
As a data curator
I would like to designate a manually extracted habits and practices document as "Extracted"
So that I can signify the work has been completed. 

Currently Habits and Practices documents are manually extracted and tagged with PUCs and Demographic information. But there is no way to indicate that the document has completed curation. So I would like to add the ability for curators to manually check off that the document has completed extraction. 

Definition of Done:
• Applies to the /datadocument/ page for Document Type Habits and Practices
• Ability for the curator to manually to indicate that the manual extraction and tagging process has been completed.
• Add a label for this tool, something like "Extraction Complete" 
tool is only available to logged-in users

**Comment by mwfrost** [comment]
For demo:
http://127.0.0.1:8000/datadocument/321111/
