### ISSUE TITLE
Manual Composition QA  Pt 2 (QA Group page)

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#1886]
As a data curator
I would like to view all documents within a Composition Data Group with manually extracted documents that need to complete QA
So that I can access the documents that require QA.

I would like to base this page off of the QA Group page for Composition Extraction Script QA.
Ex. https://factotum.epa.gov/qa/extractionscript/345/

No changes need to be made to the /qa/extractedtext/#/ page, where we check each data document. This page already exists, we just want a different way to organize and manage the QA Groups. 

Definition of Done:
• Create a new page for Manual Composition QA Groups, based off /qa/compextractionscript/#
• Include the same Table Columns:
• Data Group
• Group Type
• Data Document
• Date Updated
• Chemical Records
• QA Checked ( /qa/extractedtext/# page will be the same as for Composition documents)

**Comment by mwfrost** [comment]
A data document's QA page has a breadcrumb navigation chain at the top. Currently the parent page defaults to the Script-based QA page, even if the document was manually extracted. 
Example:
http://127.0.0.1:8000/qa/extractedtext/1496350/

The breadcrumb links are: `Composition /  Manual (dummy) / Benefos 1618`. 

Make sure the document-level QA page links to this new Data Group QA Index.

**Comment by Sakshi-Handa** [comment]
Please verify that the "Go to QA" button on the /datadocument/ page links to the new manual composition QA group page, not the 'manual dummy' group, https://factotum.epa.gov/qa/extractionscript/14/

![image.png](https://images.zenhubusercontent.com/5f318c2978fa23cbc1a57b71/843ff494-298f-40a6-b5cb-e22326eef474)

**Comment by Sakshi-Handa** [comment]
Please also add the 'Chemical Records' column.
