### ISSUE TITLE
Text search is too loose (5 pts)

### ISSUE THREAD

**Issue by mwfrost** [HumanExposure/factotum#190]
The elasticsearch results include too many false positives. The scoring parameters need to be tightened up to permit fewer results.

Test with a search for "ATU4001 AUTORF 6PK SSPR". This returns six results, only one of which has the 4001 code.

**Comment by mwfrost** [comment]
When we get around to this ticket, this article will be a useful guide:

https://wellfire.co/learn/custom-haystack-elasticsearch-backend/

**Comment by dmlyons2** [comment]
Waiting for elasticsearch training and restructure of search
