### ISSUE TITLE
 Add Hover text for Table Columns

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#1922]
As a Factotum User
I would like to see definitions of table columns on the /chemical/ and /puc/ pages
So that I can understand what information is within the table

Definition of Done:
	• Applies to the Tables on the /chemical/ and /puc/# pages
	• Add hover text definitions for the following columns:

Chemical page
		○ Product
		○ Document/Associated Document
		○ PUC
		○ PUC Kind
		○ Classification Method
		○ Data Type
		○ Document Date
		○ Reported Functional Use
		○ Harmonized Functional Use

PUC page
		○ Title
		○ Brand Name
		○ DTXSID
		○ Preferred CAS
		○ Preferred Name
		○ Count

**Comment by michael-barbour** [comment]
What should the hover text say for each one of these?

**Comment by Sakshi-Handa** [comment]
[https://app.zenhub.com/files/99837877/d7ce8309-1f94-4722-949c-f5ef773bc49e/download](https://app.zenhub.com/files/99837877/d7ce8309-1f94-4722-949c-f5ef773bc49e/download)

Here is the hover text for each column in the tables. 
applies to the /chemical/, /puc/ and /functional_use_category/ pages.

**Comment by michael-barbour** [comment]
Per conversation with @Sakshi-Handa.  

Some of the Titles themselves will be cleaned up to match with other tables.

Any classification methods using the two letter "Code" will be replaced with the full name of the method.

The rows that have multiple types will have the first line added as hover text and the descriptions of the specific types will be added as hover text to the rows in a later ticket.

ie.

> Product Category Kind  # This gets added as the title hover text
> 
> ### These get added as cell hover text ###
> Formulation – formulation based consumer products (e.g., liquids, gels, powders etc.)
> Article –a manufactured item which is formed to a specific shape or design during manufacture
> Occupational – specialty products generally intended for industrial or occupational use
> Unknown – PUC kind unknown
