### ISSUE TITLE
Script Upload for Literature Monitoring

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#1943]
As a factotum admin
I would like the ability to upload csv files of extracted data for Literature Monitoring data groups
So that I can display and curate the data in Factotum

Kristin has Literature Monitoring type documents that have been extracted by contractors in the form of a csv file. 
We need a way to import the data into Factotum. 
We can base this upload functionality off of the 'Extraction script upload' for other document types.  

Ex. Literature Monitoring Group 
https://factotum.epa.gov/datagroup/808/

Ex. Chemical Presence Group with the Extracted tab available.
https://factotum.epa.gov/datagroup/383/

![image.png](https://images.zenhubusercontent.com/5f318c2978fa23cbc1a57b71/601cdc86-fdf7-4cbd-a17d-6e02f885ccc8)

Definition of Done:

- Applies to the Upload box on the /datagroup/ page for the Literature Monitoring group type
- Add the ability to upload Extracted text (similar to the Extracted tab for CP documents), requiring an extraction script and csv file upload. 
- Add ability to download a csv template for required fields. (pre fill the data_document_id and data_document_filename columns)
- CSV file upload has the following required fields:

data_document_id
data_document_filename 
doc_date
study_type
media   [this is a general list or description of the media in the document]
QA_flag  [indicates whether ICF completed QA]
QA_who [name of contractor who completed QA]
Extraction_WA [to contain details of the contract and work assignment under which data were extracted]
raw_chem_name
raw_cas
chem_detected_flag
study_location 
sampling_date 
population_description
population_gender 
population_age 
population_other 
sampling_method 
analytical_method 
medium
harmonized_medium
num_measure 
num_nondetect
detect_freq
detect_freq_type [reported or calculated]
statistic_name
statistic_value
statistic_value_type [reported or calculated]
stat_unit
LOD
LOQ

**Comment by mwfrost** [comment]
Sakshi,
Can you specify how the statistics for a record will be uploaded? If a chemical has a min, max, and mean, will the csv include three rows where everything but the stats are duplicated?
