### ISSUE TITLE
Add Fields to Literature Monitoring Data Document

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#1944]
As a Factotum Admin
I would like to add more data fields to Lit Monitoring /datadocument/ page
So that I can display the data in Factotum

Ex. extracted LM document
 https://factotum.epa.gov/datadocument/1555980/
Currently the chemical record displays the chemical name/cas and detected_flag.
Extracted text holds: document date, study type, and media. 
There is extra data that is just extracted into the 'notes' field. 

I would like the LM documents to look more like HHE documents. With more fields in the chemical cards and extracted text. 
Ex. HHE document https://factotum.epa.gov/datadocument/1367747/

Definition of Done:
	• Applies to the /datadocument/ page for Literature Monitoring documents
	• Add the following fields to the chemical card (added in #1943):
**raw_chem_name
raw_cas
chem_detected_flag** *already present for LM chemical card
study_location 
sampling_date 
population_gender 
population_age 
population_other 
sampling_method 
analytical_method 
medium
harmonized_medium
num_measure 
num_nondetect
detect_freq
detect_freq_type [reported or calculated]
statistic_name
statistic_value
statistic_value_type [reported or calculated]
stat_unit
LOD
LOQ

• Add the following fields to the Extracted Text:

**document_date
study_type
population_description
media   [this is a general list or description of the media in the document]** * already present for LM extracted text. 
QA_flag  [indicates whether ICF completed QA]
QA_who [name of contractor who completed QA]
Extraction_WA [to contain details of the contract and work assignment under which data were extracted]

**Comment by Sakshi-Handa** [comment]
After talking to Kristin, I realized we would potentially have multiple 'statistics' for each chemical card. For a single chemical card, there could be a reported mean, median, max, std. dev, etc. But the statistics would vary by document or chemical. 
Can we build the statistics to work more like 'reported functional use', where you can add multiple to a chemical card?
Was also thinking about a way we could just show the main statistics (mean, median, max) on the chemical card, and make the others available through a download. 

Applies to these statistic fields:
statistic_name (ex. mean)
statistic_value (ex. 12)
statistic_value_type [reported or calculated] (ex. reported)
stat_unit (ex. mg/L)

**Comment by michael-barbour** [comment]
> After talking to Kristin, I realized we would potentially have multiple 'statistics' for each chemical card. For a single chemical card, there could be a reported mean, median, max, std. dev, etc. But the statistics would vary by document or chemical.
> Can we build the statistics to work more like 'reported functional use', where you can add multiple to a chemical card?
> Was also thinking about a way we could just show the main statistics (mean, median, max) on the chemical card, and make the others available through a download.
> 
> Applies to these statistic fields:
> statistic_name (ex. mean)
> statistic_value (ex. 12)
> statistic_value_type [reported or calculated] (ex. reported)
> stat_unit (ex. mg/L)

It would be no problem.  It will mean a bit more logic on the card and forms but we have a decent "roadmap" for that logic in the way we've set up functional uses

This ticket is going to be very data focused so a lot of the visual elements will not be in place as the is no LM card, nor is there any LM specific functionality.

**Comment by Sakshi-Handa** [comment]
> ## Extracted Text
> The extracted text we currently use has `qa_checked` (which may work for `qa_flag`) and `qa_approved_by` (which may work for `qa_who`).
> 
> I don't understand what `extraction_wa` is supposed to be. If this is a general text area then it should be no problem to add, but if you're hoping it can be used in meta-data aggregation then we should probably think this through more.

Those new fields we are adding:
QA_flag  [indicates whether ICF completed QA]
QA_who [name of contractor who completed QA]
Extraction_WA [to contain details of the contract and work assignment under which data were extracted]

These fields would already be filled in when the data is uploaded. They are related to the contractor's completion of the work. Just meta data from the work assignment that we want to keep track of. I think its fine if they are simple text fields. I don't think we will be doing much with them. 

I would say we need new fields though. So we can keep this separate from our Factotum QA workflow. At some point, we would probably want to verify the contractor's work with an additional Factotum QA check.

**Comment by michael-barbour** [comment]
After talking to @Sakshi-Handa I realized that I misunderstood the overlap this ticket with #1943.  

This ticket is meant to make the UI elements on the `/datadocument/` page that were added in #1943.  I'm adding a blocker on this ticket for #1943 and moving it back to the to-do pipeline.

**Comment by Sakshi-Handa** [comment]
Here are some specifications for the fields.

Decimal (non-whole numbers):
•	LOD and LOQ - **leave field names as acronyms.**
•	statistic_value
•	detect_freq - **will always be a ratio. it is reported in some studies, or curators calculate it based on given data.** 

Integer (whole numbers):
•	num_measure
•	num_nondetect

Date:
•	sampling_date
Character field limited to specific choices
•	statistic_value_type [reported or calculated]
•	detect_freq_type [reported or calculated]

Character field with hard limits:
•	study_location - 200 characters
•	population_age -  200 characters. **would rather this field be free form text. Age can be reported as age ranges, or descriptive groups (adults, children, etc.)**
•	population_gender - 30 characters **We could standardize this field, to only accept M (Male), F (Female), A (All), O (Other, leaving room for studies of nonbinary individuals etc., in the future)**
•	population_other - 200 characters. **This field would be used for occupational or other population stratifiers we want to retain at the chemical level.** 
•	sampling_method - 200 characters
•	analytical_method - 200 characters
•	medium - 200 characters
•	harmonized_medium - 200 characters **We would like to standardize the values that can go into this field. I will comment the list of harmonized media below.**

•	statistic_name - 100 characters **We would also want to standardize the statistics captured. Would like to expand this later, as needed.**
o	Mean
o	Median
o	Max
o	75th percentile
o	95th Percentile
o	99th Percentile
o	SE
o	SD

•	stat_unit - 30 characters **It would be best to leave this non-standardized. There are many ways to represent the units, so it would be difficult to make a standard list. If it is easy to remove leading/trailing spaces, then we can do that.** 

•	QA_flag  - 30 characters **Include these as character fields with limits**
•	QA_who  - 200 characters
•	Extraction_WA - 200 characters



Text field (for large amounts of text):
•	population_description -  **Would like to leave more room for this field. It should go at the document level as a general description of the study described in the paper.**

**Comment by Sakshi-Handa** [comment]
Here is a list of all the harmonized media that we would like to include. 

indoor dust
soil
ambient air
human blood (whole/serum/plasma)
sediment
surface water
personal air
wildlife (birds)
wildlife (fish)
wastewater (influent, effluent)
groundwater
wildlife (terrestrial invertebrates/worms)
wildlife (aquatic vertebrates/mammals)
vegetation
wildlife (terrestrial vertebrates)
unknown
breast milk
drinking water
food product
human (other tissues or fluids)
indoor air
livestock/meat
product
raw agricultural commodity
skin wipes
urine
wildlife (aquatic invertebrate)
sludge
other-ecological
precipitation
other-environmental
landfill leachate

**Comment by mwfrost** [comment]
For testing: `http://127.0.0.1:8000/datadocument/1555695/`
