### ISSUE TITLE
Move table column captions to field help_text properties

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#1955]
Move the strings used as column captions in ticket #1922 into the help_text properties of their respective fields.

**Comment by fang-yan-csra** [comment]
The hover text on table header could be different for the same field. for example Product on /puc page and on /chemical page are different. So it seems this ticket is not applicable.

**Comment by Sakshi-Handa** [comment]
We can close this ticket. The hover text on each column is specific to that table. So we wouldn't be able to combine them into the same field.
