### ISSUE TITLE
Bulk Download Composition Data

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#1964]
As a Factotum Admin
I would like to make available a bulk download of all Composition related data on Factotum
So that users can get up-to-date data via the application

Definition of Done:
• Add a button to 'Bulk Download Consumer Product Data' on the /get_data/ page 
• Allows users to download a csv file of Composition data, including the following fields
		○ Data Source
		○ Data Document Title
		○ Document Date 
		○ Product Name 
		○ uber PUC (General Category	Product Family	Product Type)
		○ PUC Classification Method
		○ Raw Chemical name
		○ Raw CAS
		○ DTXSID
		○ Curated Chemical name
		○ Curated CAS
		○ Provisional Chemical Curation Flag
		○ Raw Min Comp	
		○ Raw Max Comp	
		○ Raw Central Comp	
		○ Unit Type	
		○ Lower Weight Fraction	
		○ Upper Weight Fraction	
		○ Central Weight Fraction	
		○ Weight Fraction Type

**Comment by mwfrost** [comment]
The output file needs to include the PUC columns

**Comment by mwfrost** [comment]
The PUC Kind should be included as another column, and the three PUC levels should be provided as separate columns.
