### ISSUE TITLE
News on Homepage

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#1983]
As a Factotum Admin
I want to display a section for Latest News on the Factotum homepage
So that I can regularly update to communicate with users about new features, known bugs, etc. 

We want to be able to display recent updates for users, and let them know if things are down. 
A good example of a news page is on the Comptox Dashboard.
https://comptox.epa.gov/dashboard/
I like the way they display the news and how it scrolls. I really like the 'read more news' button, that takes you to a new page that lists all news entries and the change log. We can add and maintain these news entries in the admin panel. 
![image.png](https://images.zenhubusercontent.com/5f318c2978fa23cbc1a57b71/9888f15b-8ab6-413a-ab4b-55133b073553)

Definition of Done:
• Add new section for "Latest News" to the Factotum homepage, https://factotum.epa.gov/. News displays entries with a subject, date and body text. 
• Add a button for "See All News" that links to a new page showing all news entries. 
• News appears for logged-in and guest users
• Ability to add and edit news entries via the admin panel. 
• Ability to add subject, date and body text fields. (similar to comments)

**Comment by mwfrost** [comment]
For demo:
`http://127.0.0.1:8000/admin/dashboard/news/`
