### ISSUE TITLE
 Display Literature Monitoring data on /chemical/ page

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#1988]
As a Factotum user, 
I would like to view summarized literature monitoring data related to a specific chemical
So that I can find studies related to a chemical of interest.

Ex. HHE Document https://factotum.epa.gov/datadocument/1367552/
Ex. LM Document https://factotum.epa.gov/datadocument/1556440/
Ex. Chemical page https://factotum.epa.gov/chemical/DTXSID5027273/

This might require some standardizing of fields between these LM and HHE data group types. 

Definition of Done:
• Add a new table for "Literature Monitoring" as a tab on /chemical/ page
• Table will display Literature Monitoring (LM) and Health Hazard Evaluations (HHE) documents
• Include the following table columns:
	○ Data Type
	○ Document (include a link to the /datadocument/ page)
	○ Reported Medium
	○ Harmonized Medium
	○ Number of Samples (Numeric Measure on HHE)
	○Chemical Detected (yes/no)

**Comment by mwfrost** [comment]
Sakshi,
The `num_measure` and `num_nondetect` attributes appear to be intended as numeric-only fields, and the `ExtractedLMRec` data model enforces this by only allowing numeric values. 

The `ExtractedHHRec` model, though, never prohibited text values in these fields, so there are many cases of unstructured text:
![image](https://user-images.githubusercontent.com/201835/123858140-04ccd380-d8d8-11eb-8974-72a6b17afae9.png)

Do you want to proceed with this ticket's requirement to present both LM and HH rows in the table together, even though their data structures are this different?

**Comment by mwfrost** [comment]
One representative data document:
factotum.epa.gov/datadocument/1367783/#chem-card-5166979

**Comment by Sakshi-Handa** [comment]
Thanks for the examples. I didn't realize it was so inconsistent. We will still want to display the HHE documents along with the other Literature Monitoring documents, but it might require some cleaning up of the HHE model fields first. Also we currently don't have any data in LM documents to display. Maybe we should hold off on completing this ticket until we address the formatting issues. Can we put the ticket back into To Do?

How do you recommend dealing with the multiple comma-separated data points in each field? For example, '0, 8' in the numeric measure. If they were consistently comma-separated, could we separate out what is in each field to display the data on separate rows by media in the /Chemical/ page Summary Table?
