### ISSUE TITLE
Add LM statistic fields

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#1989]
This ticket is a continuation of #1944.
This is focused on adding, displaying, and editing multiple statistics for LM documents. 

Fields:
statistic_name
statistic_value
statistic_value_type [reported or calculated]
stat_unit

Definition of Done:
• Ability to add/delete/edit multiple statistics per chemical via the chemical edit form on the /datadocument/ page for LM type documents
• Display multiple statistics on the chemical card

**Comment by Sakshi-Handa** [comment]
We would also want to standardize the statistics captured. Would like to expand this later, as needed. Here is a list of standard statistics we capture:
o Mean
o Median
o Max
o 75th percentile
o 95th Percentile
o 99th Percentile
o SE
o SD

**Comment by zachmunzenrider** [comment]
Sakshi, would you like the stat_unit value here to use the existing set of unit type data, or does it need its own distinct set of options?

**Comment by Sakshi-Handa** [comment]
> @Sakshi-Handa Sakshi, would you like the stat_unit value here to use the existing set of unit type data, or does it need its own distinct set of options?

I was talking to Fang about it. I think just leave this as a text field. It might be hard to standardize these units, since there can be so many possible options for units. Then we can just enter the text as ' mg/L' instead of trying to assign a code
