### ISSUE TITLE
Error Searching for Symbols

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#2005]
When using the Factotum main search bar, certain symbols such as forward slash /, parentheses ( ), do not work in the search and return a 500 error.
For example, searching for this product: https://factotum.epa.gov/product/669172/
Typing in 'normal/ oily' in the search returns a 500 server error. 

Also not able to search for chemical names with ( ). 
For example '(-)-beta-Pinene' is not searchable.

And some symbols are ignored in the search:  $%&
For example, searching for this product: https://factotum.epa.gov/product/98591/
Typing in 'bath $10' in the search, and it ignores the $
https://factotum.epa.gov/search/product/?q=YmF0aCAkMTA=

**Comment by mwfrost** [comment]
The special characters need to be escaped in `search.py`. Entering `normal\\/ oily` into the search box returns the expected results.
