### ISSUE TITLE
Add Description to Harmonized Medium

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#2006]
As an admin 
I would like to add and edit descriptions to each harmonized medium
So that I display this information in Factotum

The list of Harmonized Media was added to the Literature Monitoring fields in #1944. 

Definition of Done:
- Applies to the admin panel for harmonized medium, https://factotum.epa.gov/admin/dashboard/harmonizedmedium/ 
- Add a field for Description, in which an admin can add descriptive text for each medium.

**Comment by BryanMG957** [comment]
Not blocked code wise. I changed the migration number to follow migration 197 from Fang's ticket
