### ISSUE TITLE
Error Saving LM Card Edits

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#2023]
There is an issue saving edits to the LM chemical card via the /datadocument/ page. 
After adding data to fields in chemical edit form and clicking 'save edits', the entered data is not stored in the edit form and does not appear on the chemical card. 

Ex. LM document
https://factotum.epa.gov/datadocument/1555997/#chem-card-5156463

Definition of Done:
applies to chemical edit form and chemical card on /datadocument/ page for LM documents
ability to manually add and save data through the chemical card edit form, which also appears on the chemical card.

**Comment by mwfrost** [comment]
Somehow, when these two datagroups were populated with their extracted chemical records, there were duplicate `ExtractedComposition` objects created. The code that should update the `ExtractedLMRec` object is instead trying to save changes to the corresponding `ExtractedComposition` object that should not exist. 

This SQL command will destroy all the unwanted `ExtractedComposition` records, leaving only the `ExtractedLMRec` objects:
```
DELETE FROM dashboard_extractedcomposition where rawchem_ptr_id IN (SELECT 
            rawchem_ptr_id
        FROM
            dashboard_extractedlmrec);
```

After running this on my machine, the LM editing worked as expected.

**Comment by mwfrost** [comment]
I think the next troubleshooting step is to upload a new data group of Literature Monitoring records and confirm that they can be updated in the card editor. Do you have a backlog of LM data that can be used to test it? 

If a new csv upload works correctly, we can consider this duplication to be an artifact of the old code, and wipe out the duplicate composition records.

**Comment by Sakshi-Handa** [comment]
Previously, we did not have a method for uploading LM data by script. We would just upload the document pdfs, and curators would manually extract the chemicals into the chemical cards via the editing tools on the /datadocument/ page.

I think the only LM data that can test it would be the new files Kristin would like to upload, the IFC extracted LM data. I dont know if that is ready yet. Could you just test it with 'fake' data for now?

**Comment by mwfrost** [comment]
This helps clarify things, thanks! The old records were added as `ExtractedComposition` objects, but when migration `0196` converted them into `ExtractedLMRec` objects, the migration did not delete the `ExtractedComposition` records -- they remained associated with each of the `RawChem` base class records. I will create a data migration to clean them out, after which the editing will work.
