### ISSUE TITLE
Update Elasticsearch

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#2028]
I would like to ensure we are running the latest version of Elastic so we don’t have any issues conducting searches. 

The current dockerfile specifies version 7.3.1, but the Docker Hub page says that 7.13.3 is the currently supported tag.
https://github.com/HumanExposure/factotum_elastic/tree/dev/elasticsearch

Definition of Done:
Update the Factotum Elasticsearch to the latest version.

**Comment by mwfrost** [comment]
It's at 7.14 now: `https://hub.docker.com/_/elasticsearch`
