### ISSUE TITLE
Update Container Names

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#2042]
As a system admin
I would like to update the names of factotum containers 
So that I can easily understand what each contains, and find the relevant container for troubleshooting issues.  

There are 8 containers for Factotum.
Docker_factotum_1, elasticsearch, etc. 

Definition of Done:
	• Provide summary documentation of each Factotum container 
	• Rename Factotum Containers based on their contents

**Comment by mwfrost** [comment]
The sysadmin would like for every container to be named with `_factotum`
