### ISSUE TITLE
Composition Cleaning QA Pt 3. (QA Summary page)

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#2051]
As a product owner, 
I would like to view the QA summary page for each Composition Cleaning QA group
So that I can view summary statistics, QA notes, audit log, etc. for documents within a QA group.

The summary page can have the same layout as other QA Summary pages. Curators will use the summary page to determine the quality of the cleaning script. 

Definition of Done:
· Create a new Cleaned Composition QA summary page to show QA notes for each document, based on /qa/compextractionscript/#/summary page.
· Include the same summary statistics and table columns as Composition QA Summary page
·  Each QA Summary page is related to a single Composition Cleaning Script QA Group

**Comment by mwfrost** [comment]
@Sakshi-Handa 
As I was preparing this page, I noticed that the Extraction Script QA summary pages show *all* the extracted documents, not just the ones in the QA Group for the extraction script. Is that the appropriate behavior, or should the QA summary page only show the QA Group's subset?

For an example, see the summary page for the "3M" extraction script:
`http://[faxtotum path]/qa/extractionscript/52/summary` 

There are 2189 documents extracted by that script, and the QA Group contains 464.  On the summary page, the table loads all 2189 records. Unless you tell me that we built the page incorrectly, I will replicate that behavior in the new Cleaning Script summary page.
