### ISSUE TITLE
Fix Bulk Composition Download

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#2055]
the bulk composition download, on the /get_data/ page is not working. 

https://factotum.epa.gov/dl_co_chemicals/ 
shows 'Composition Data not available yet, please try again later.' 

definition of done:
ability to download bulk composition data file.

**Comment by zachmunzenrider** [comment]
This is occurring because the celery task created in #2009 is somehow failing to actually create the file csv_storage/composition_chemicals.zip. It worked for both Matt and Fang in their local environments, but it's not working in mine.
