### ISSUE TITLE
Refine Search Results

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#2070]
As a Factotum Admin
I would like to make sure searches for specific phrases only returns products with the specific phrase
So that users only see the products they are searching for

With the changes in #2004, placing quotations around search phrases prioritizes the specified keywords. But the search results continue to display anything with related words. 
The issue we noticed was in searching for 'pet shampoo', the product brands that show up were all human shampoo brands. So that would be confusing for users. 
There are also over 16,000 products returned, and past the first few pages they are no longer 'pet shampoos' 
We would like to reduce the number of 'false positive' results.

Definition of Done:
Applies to the Factotum main search bar
When searching by specific phrases, prioritize search results that contain all words in phrase.

**Comment by mwfrost** [comment]
The failure of the search to restrict to a phrase turned out to be caused by the use of single quotes instead of double quotes. #2071 added code to treat single- and double quotes the same.
