### ISSUE TITLE
 Change Comp Cleaning QA Label 

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#2084]
As Factotum Admin 
I would like to remove the 'manual' designation from the composition cleaning QA label
Because there is only one Comp Cleaning workflow for both script and manual extractions. 

Definition of done:
On the Main toolbar under "QA", remove the text "Manually Extracted"  from the Composition Cleaning QA label.  The label should read "Composition - Cleaning Script"

**Comment by mwfrost** [comment]
Fixed on the branch for #2050
