### ISSUE TITLE
 Bulk Assign Raw Category PUC Assignment Column

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#2088]
As a data curator
I would like to know which data group/raw categories entries have already been assigned to PUCs
So that I can easily see what PUCs have been assigned and what entries are missing BA assignments.  

https://ccte-factotum.epa.gov/bulk_rawcategory/
We assign products using the 'Bulk Assign' (BA) PUC classification method by selecting entries from the table and using the "Connect PUCs" button to assign all product entries in a data group with a given 'raw category' to a PUC. 
Note: This is different from Manual Batch (MB) assign, which is also available through the 'Product Count'.  

Definition of Done:
	• Applies to the 'Bulk Assign Raw Category to PUC' tool, /bulk_rawcategory/
	• Add a new column to the table for 'BA PUC Assignment' that indicates what Bulk Assign PUC these products have been assigned to. There should only be one BA PUC assigned to every product for a given datagroup/ raw category table entry.

**Comment by mwfrost** [comment]
@Sakshi-Handa 
The PUC data structure is eccentric - each PUC can have from one to three text attributes describing its place in the hierarchy. There is, unfortunately, no single text field that uniquely identifies a PUC. Do you want the PUCs in this table to be listed as three-field concatenations of `gen_cat`, `prod_fam`, and `prod_type`?

**Comment by Sakshi-Handa** [comment]
> @Sakshi-Handa The PUC data structure is eccentric - each PUC can have from one to three text attributes describing its place in the hierarchy. There is, unfortunately, no single text field that uniquely identifies a PUC. Do you want the PUCs in this table to be listed as three-field concatenations of `gen_cat`, `prod_fam`, and `prod_type`?

Yes, that is fine. Please display the three PUC tiers together in one column.
