### ISSUE TITLE
Search Tab for Harmonized Media

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#2098]
As a Factotum user
I would like to use the main search bar to search for harmonized media categories
So that I can view search results related to my harmonized media of interest

Definition of Done:
	• Applies to the Factotum main search, https://ccte-factotum.epa.gov/search/product/?q=aW5kb29yIGFpcg==
	• Create a new tab for 'Media' along the top of the page, similar to the CP Tag search tab. 
	• Search results in 'Media' tab displays Harmonized Media name and definition, and links to the Harmonized Media detail page.
	• Searching by a keyword, i.e. 'air' should look through harmonized media categories and their descriptions and return all relevant results.

**Comment by mwfrost** [comment]
@Sakshi-Handa 
Adding two wide tabs to the list of search categories at the top has used up the remaining space, and now the `<li class="nav-item">...</li>` elements have wrapped around into a second row. Please add a new ticket if you want us to redesign the navigation tabs to account for how popular that real estate is.

**Comment by mwfrost** [comment]
![image](https://user-images.githubusercontent.com/201835/156251990-1e7f3769-5713-4379-865a-5a31b1886d28.png)
