### ISSUE TITLE
MySQL connector version change

### ISSUE THREAD

**Issue by kbfepa** [HumanExposure/factotum#2114]
Change the `MYSQL_CONNECTOR_VERSION` in `factotum/factotum_elastic` repo to `5.1.49`.

Original logstash error:

```
[2021-10-27T14:39:23,868][INFO ][logstash.agent           ] Pipelines running {:count=>2, :running_pipelines=>[:dashboard, :factotum_ws_logs], :non_running_pipelines=>[]}
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/cronline.rb:77: warning: constant ::Fixnum is deprecated
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    21  100    21    0     0     37      0 --:--:-- --:--:-- --:--:--    37
[2021-10-28T05:30:00,439][ERROR][logstash.inputs.jdbc     ][dashboard][53934cac912a4b4140868c12cd7b5b13a5f9b70deb31350f3d4205e38ce6dd5b]
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
```

**Comment by mwfrost** [comment]
I recommend we discard this ticket. Downgrading the MySQL connector to 5.1.49 is causing problems that I cannot diagnose, and which might be intractable, given the use of Java version 11.0.12 on the logstash container. 

From the MySQL documentation:
https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-versions.html

>MySQL Connector/J 8.0 is highly recommended for use with MySQL Server 8.0, 5.7, and 5.6. Please upgrade to MySQL Connector/J 8.0.

**Comment by mwfrost** [comment]
On November 19, EPA's database admin said we didn't need to downgrade.

**Comment by Sakshi-Handa** [comment]
Closing ticket, decided to continue using current version 8.
