### ISSUE TITLE
Datatables Error

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#2120]
There is a recurring issue on the /PUC/# page tables, where certain tables return this error:
![image (6).png](https://images.zenhubusercontent.com/5f318c2978fa23cbc1a57b71/0ac7063e-c1b2-4e5d-8ede-118e4fe23769)

'DataTables warning: table id=documents - Ajax error. For more information about this error, please see http://datatables.net/tn/7'

For Example, the warning appears on the PUC detail page, when clicking on the 'documents' tab. The table does not load.
https://ccte-factotum.epa.gov/puc/5/

Definition of Done:
- Resolve Datatables warning on /puc/# page

**Comment by mwfrost** [comment]
The AJAX query works when it's just the bare URL:
```
http://127.0.0.1:8000/d_json/?puc=5
```

but when the DataTables parameters are included in the URL, it breaks.

`dashboard.models.data_document.DataDocument.extractedtext.RelatedObjectDoesNotExist: DataDocument has no extractedtext.`

**Comment by mwfrost** [comment]
The error is occurring because `extractedtext.doc_date` is one of the columns, but not every document with a PUC has a related `extractedtext` object. The ajax view is failing when it encounters a data document with no extractedtext.
