### ISSUE TITLE
Create MMDB Summary Database Table

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#2125]
As a product owner
I would like to create a new table in prod_factotum to hold MMDB data 
So that I can surface the data on the Factotum UI.

We would like the dev team to create the table, but it will be populated with data by SCDCD. 
So the table will be 'empty' in the database, but we can provide some sample data for testing. See the attached csv file, 'sample_mmdb_data'.

The required column names and data types are described in the attached word document, "MMDB Factotum Table Field Definitions"

Definition of Done:
Create new database table for MMDB Summary data in prod_factotum
The following fields will be added, (see attached document for more information on data types):
Source name
Data type
Harmonized medium
Reported medium
Reported species
DTXSID
Preferred Name
Preferred CAS
Number of Observations
Detected Sample Count
Chemical Detected 

[https://app.zenhub.com/files/99837877/beced2db-66eb-4685-ac66-86e6a0c1d36c/download](https://app.zenhub.com/files/99837877/beced2db-66eb-4685-ac66-86e6a0c1d36c/download)

[https://app.zenhub.com/files/99837877/b5188082-8db4-4a13-8560-22738de151fe/download](https://app.zenhub.com/files/99837877/b5188082-8db4-4a13-8560-22738de151fe/download)

**Comment by mwfrost** [comment]
Will these records only include curated DSSTOX SIDs? Or can they appear without any SID?

**Comment by Sakshi-Handa** [comment]
> 

Yes, all current MMDB data is curated to DTXSIDs. And future data would be curated to SIDs before being pushed into Factotum. We only want to display data that has been curated to SIDs and harmonized to media categories, so that they can show up on our media and chemical pages.

**Comment by mwfrost** [comment]
"Detected sample count" should be null when the data type is "summary". 
"Number of observations" should be nullable.
