### ISSUE TITLE
Functional Use QA Group Bug

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#2142]
In the Functional Use Extraction Script QA, curators are not able to move to the next document in the QA group via the "Approve" or "Skip" buttons on the /qa/extractedtext/ page. Instead, Factotum adds a new document to the QA group. (I'm assuming it uses documents related to the extraction script). This adds another count to the QA group documents, which makes the percentage of documents in the QA group more than 20%. It also makes it difficult to ever complete QA. 

To recreate:
	• Go to Functional Use Extraction Script QA. https://ccte-factotum-stg.epa.gov/qa/extractionscript/?group_type=FU
	• For 'SpecialChem Adhesives and Polymers' There are 3196 documents in 'QA Group Documents' out of 14995 total Extracted text documents associated with the script. 
	• On the QA Summary, it shows there are 241 Total Approved Documents. https://ccte-factotum-stg.epa.gov/qa/extractionscript/422/summary
	• Then on the QA Group page, there are 2955 documents remaining.  https://ccte-factotum-stg.epa.gov/qa/extractionscript/422/ 
	• Then go to the /qa/extractedtext/ page https://ccte-factotum-stg.epa.gov/qa/extractedtext/1627374/. It says '94 document(s) approved, 5817 documents remaining'
	• Try to Approve or Skip a document.
	• Review the previous statistics. 
		○ Now the QA Extracted text page shows '95 document(s) approved, 5816 documents remaining'
		○ On the Functional Use Extraction Script QA, the count on the 'QA Group Documents' has increased to 3197. 
		○ The QA Summary page shows there are now 242 Approved Documents. 
		○ The QA Group page for Special Chem Adhesives still shows 2955 entries.

So it looks like when you approve or skip a document from the /qa/extractedtext/ page it doesn’t count that towards completing the QA Group. It approves the document, but adds another document to the QA group count. And there is a discrepancy between how many documents are considered approved by the QA Summary (242 documents) vs. the /qa/extractedtext/ page (95 documents). 

Definition of done:
	• Review the statistics/logic for approved and QA group documents for the Functional Use Extraction Script QA.
	• The QA Group documents should consist of a random 20% of the total Extracted Text documents associated with the script.
	• When documents are approved or skipped on the /qa/extractedtext/, the curator should move to the next document in the QA Group.

**Comment by mwfrost** [comment]
*Production note:* The QA summary page for an extraction script exhibits some obscure behavior that was defined in 2020. In particular, the number of documents shown in the table on the QA summary page for Script `422` does not match either the number of records in the script's QA group or the number of records extracted by the script. Instead, it shows all the "valid" extracted documents, meaning all the documents with either a QA Note or a raw chem record with an audit log. 

`factotum-stg.epa.gov/qa/extractionscript/422/summary/table`

Reference ticket:
https://github.com/HumanExposure/factotum/issues/1348
