### ISSUE TITLE
Raw Category Assignment Bug

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#2164]
There is an issue with the raw category PUC assignment (BA Assignment). https://ccte-factotum.epa.gov/bulk_rawcategory/
When a curator assigns a PUC to an entry on the raw category table, it removes all associated product entries on the linked Product Count page. i.e. https://ccte-factotum.epa.gov/bulk_product_puc/?dg=208&rc=Personal%20Beauty%20Care%20Product

This page linked to the Product Count refers to a different assignment method. This is the Manual Batch assignment, with a filter applied to show products for a certain data group and raw category. When a Raw Category is applied, the products disappear from the Manual Batch table as 'already associated with a PUC'. So they are not available in the Manual Batch search. https://ccte-factotum.epa.gov/bulk_product_puc/
Even if a PUC  is assigned via raw category, we still need to be able to assign those same products via the Manual Batch method, since it is a higher level classification method. 

Definition of Done:
	• When a Raw Category is assigned via /bulk_rawcategory/ , products should not be removed from the linked Manual Batch assignment page, /bulk_product_puc/?dg=208&rc=Personal%20Beauty%20Care%20Product
	• Let's rename the page title of /bulk_product_puc/ to 'Manual Batch Assign Products to PUCs', to prevent future confusion.

**Comment by mwfrost** [comment]
This is actually a change to the requirements specified in an old ticket:
https://github.com/HumanExposure/factotum/pull/1688

From that ticket:
```
The bulk assignment table shown here should only include unassigned products (.classification_method = None ) and "AU"-assigned products (.classification_method = "AU") because both of those methods are less reliable than "BA".
```
The new required behavior is for the table to include unassigned, AU-assigned, and BA-assigned product-to-PUC combinations.
