### ISSUE TITLE
BA Assigned products not appearing on Products Table

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#2172]
There is an issue viewing Bulk Assign Raw Category (BA) products on the Products Table tab on the /chemical/, /puc/#, and /functional_use_category/# pages.
I believe this is a new issue, appearing since #2088 was completed. Previous BA assignments were working correctly. 

For example. 
on the products tab of the chemical page. 
https://ccte-factotum.epa.gov/chemical/DTXSID2021319/
the product 'zep formula 300'  appears as Automatic assignment to
"Home maintenance - degreaser".
But when you click on the product detail, the UberPUC assignment is BA Assignment to "Cleaning and safety - cleaning products - industrial degreaser"
The 'zep formula 300' product doesn't show up on the PUC page for Industrial Degreaser. Which we would want, since that is the UberPUC assignment.
It looks like the PUC appears on the product page as BA assigned to industrial degreaser, but it is treated on the product tables as if there is only the automated assignment.

Definition of Done:
BA assigned products should appear as a higher classification method than AU assignment on Product Tables visible on the /chemical/, /puc/#, and /functional_use_category/# pages.

**Comment by mwfrost** [comment]
Some PUC assignments have been added without the system catching them and updating the `is_uber_puc` attribute for the product ID. 

The solution has two parts: 
1. Identify the place where new `ProductToPUC` objects were created without the `update_uber_puc()` method being run on the product.
2. Establish a bulk routine, maybe in celery, that will guarantee fresh uberpucs every day.

**Comment by mwfrost** [comment]
Query to identify all the misassigned ones:
```
SELECT 
	ptp.product_id AS product_id,
	ptp.puc_id AS puc_id,
	ptp.classification_method_id AS classification_method_id,
    is_uber_puc,
	cm.rank AS rank,
	 (
			SELECT MIN(cmsub.rank)
			FROM 
				dashboard_producttopuc ptpsub
			LEFT JOIN dashboard_producttopucclassificationmethod cmsub ON cmsub.id = ptpsub.classification_method_id
            WHERE ptpsub.product_id = ptp.product_id
            GROUP BY ptpsub.product_id
    ) as min_rank,
    cm.rank =  (
			SELECT MIN(cmsub.rank)
			FROM 
				dashboard_producttopuc ptpsub
			LEFT JOIN dashboard_producttopucclassificationmethod cmsub ON cmsub.id = ptpsub.classification_method_id
            WHERE ptpsub.product_id = ptp.product_id
            GROUP BY ptpsub.product_id
    ) as should_be_uberpuc
	FROM
		dashboard_producttopuc ptp
	LEFT JOIN dashboard_producttopucclassificationmethod cm ON cm.id = ptp.classification_method_id
	WHERE is_uber_puc <> (cm.rank = (
			SELECT MIN(cmsub.rank)
			FROM 
				dashboard_producttopuc ptpsub
			LEFT JOIN dashboard_producttopucclassificationmethod cmsub ON cmsub.id = ptpsub.classification_method_id
            WHERE ptpsub.product_id = ptp.product_id
            GROUP BY ptpsub.product_id
    ))
    ORDER BY product_id, rank
    ;
```

**Comment by mwfrost** [comment]
A query that updates any misassigned uberpucs:
```
UPDATE prod_factotum.dashboard_producttopuc ptp
INNER JOIN 
(
    select ptp.id,
    (cm.rank =  (
                SELECT MIN(cmsub.rank)
                FROM 
                    prod_factotum.dashboard_producttopuc ptpsub
                LEFT JOIN prod_factotum.dashboard_producttopucclassificationmethod cmsub ON cmsub.id = ptpsub.classification_method_id
                WHERE ptpsub.product_id = ptp.product_id
                GROUP BY ptpsub.product_id
                )
        ) as should_be_uber_puc
    FROM prod_factotum.dashboard_producttopuc ptp
        INNER JOIN dashboard_producttopucclassificationmethod cm ON cm.id = ptp.classification_method_id
)  ptp_fixed 
on ptp.id = ptp_fixed.id
SET ptp.is_uber_puc = ptp_fixed.should_be_uber_puc
```

**Comment by mwfrost** [comment]
Continued diagnosis:

In the example above, the "AU" assignment was the uberpuc according to the `is_uber_puc` attribute of the `ProductToPUC` record. Assigning the "BA" PUC on top of the prior assignment should have updated that field, but it did not.

**Comment by mwfrost** [comment]
Noted in meeting of Feb 1: batch-assigned products are not getting the metadata that should be assigned
