### ISSUE TITLE
place media folder contents onto dev, stg (backup)

### ISSUE THREAD

**Issue by kbfepa** [HumanExposure/factotum#2180]
`/media` directory is large (>>30GB), and isn't backed up anywhere. This data should be copied over to dev and staging, so that:
(1) Dev and Staging deployments have access to this data, in turn best mimicking production deployment
(2) Dev and Staging servers can act as a backup for this data

Do we want to back it up somewhere else as well? (Clowder?)

**Comment by Sakshi-Handa** [comment]
Closing issue, copies of media files now available on dev and stage.
