### ISSUE TITLE
set logstash pipeline schedule to 15 minutes after deployment

### ISSUE THREAD

**Issue by kbfepa** [HumanExposure/factotum#2181]
TODO: still needs to be flushed out - ask Matt about it.

Instead of setting to 1:30AM, could there be a bit of string manipulation to dynamically set the `REINDEX_SCHEDULE` ? to `current_time + 15 min`?

=> There are many times when we want the index set immediately, but having them run more frequently than once a day would be wasteful.

**Comment by hausman-gdit** [comment]
Hmm, I remember when I was first using docker only in the CLI I relied heavily on a `make` file. Since the cron job is set in the `.env` or in the yaml file maybe we could just script an edit to the file itself on spinup?
