### ISSUE TITLE
Messaging upon AU PUC Removal

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#2220]
Relates to recently completed #2173, for removing AU PUC predictions via csv upload. 
The upload works well, when we upload a csv with a blank puc_id, Factotum removes the AU PUC assignment from the related product_id with incorrect PUC assigned. 

But upon upload, the tool returns a message to the curators summarizing changes made. The messaging is not showing that pucs were removed, returning 'undefined PUC assignments added, undefined updated, undefined deleted.'

Definition of done:
- applies to AU PUC upload tool, /upload_predicted_pucs/
- after uploading csv file, the confirmation message should alert users of AU PUC assignments removed.

**Comment by Sakshi-Handa** [comment]
[predicted puc upload test single 3_22_22.csv](https://github.com/HumanExposure/factotum/files/8325989/predicted.puc.upload.test.single.3_22_22.csv)
[predicted puc upload test 3_22_22.csv](https://github.com/HumanExposure/factotum/files/8325990/predicted.puc.upload.test.3_22_22.csv)

**Comment by mwfrost** [comment]
When this ticket was first written, I added an experimental branch that someone could use to continue the work. 

https://github.com/HumanExposure/factotum/commit/7ba79a15c72894e01780b5c0ca159a461189bbb7
