### ISSUE TITLE
Tagset Filtering

### ISSUE THREAD

**Issue by hausman-gdit** [HumanExposure/factotum#2257]
**Describe the bug**
Render/query failure?

Related to #2242 

**To Reproduce**
1. Go to 'list_presence_tag/412/'
2. apply filter
3. nothing / 500

Dev:
`500 - Bad Request - Line is too large (6312 > 4094)`

Local:
![image](https://user-images.githubusercontent.com/74921039/166005733-5244bb81-918a-4198-9e35-861c674d4b8c.png)

**Expected behavior**
The keyword set selected will be applied to  filter the contents of the `Sets` and `Documents` tabs.

**Desktop (please complete the following information):**
 - OS: RHEL/Win10
 - Browser chrome, ff

**Additional context**

**Comment by Sakshi-Handa** [comment]
Closing issue, resubmitted as #2261
