### ISSUE TITLE
Add data group (8 pts)

### ISSUE THREAD

**Issue by dmlyons2** [HumanExposure/factotum#23]
As a data collector,
I want to add a data group,
so that I can later register and upload records into a data group.

On the [Data Source Show](https://balsamiq.cloud/sadlf/psb72/r56D3) page, there should be a 'New data group' button. Pressing this button opens the 'add data group' web form (no mock-up). On this web form should be fields for the data collector to enter:
  - title of the data group (required, 100 characters max), defaults to name of data source with numeric increment (e.g. Data Source_1)
  - Option to select name of person who did the download from a pre-populated list of application users (default to currently logged in user) (required)
  - date of data download (required)
  - Github URL to download script (not required)

When user submits the completed form successfully, user will be automatically brought to the newly created '[Data Group Show](https://balsamiq.cloud/sadlf/psb72/r465A)' page. At this time, the Data Group Show page will only include the fields on the upper portion of the mock-up (the text based fields). The table at the bottom of the Data Group Show page will not yet be present, since no records have been registered at this point. At this point, for the buttons on the Data Group Show page, the 'Register Records' button will be enabled, all other buttons on this page will be disabled. The 'CSV template' underneath 'Register Records' button will be enabled, the 'registered_records.csv' link above the 'Register Records' will be disabled

**Comment by mwfrost** [comment]
Incrementing the number at the end of the default name can be tricky. If a user creates two data sources, then deletes the first, the default value of the second one created was 2. Adding another data group this way will use "2" again because there's only one existing data group under the data source. The alternative is to increment the highest primary key instead of the count.
