### ISSUE TITLE
Bug in statistics column in LM download

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#2315]
In the recent ticket #2289, we added a download for the LM datadocument.
I was checking on stage, it looks like there is a bug in the 'stat's column. The download is combining all of the statistical values reported for the same 'chemical name' into one column. 
So in the example file, when two chemical records have the same 'raw chemical name', the 'stats' column combines the reported statistical values for each record and reports them twice on each row. 

i.e. https://ccte-factotum-stg.epa.gov/datadocument/1555997/#chem-card-5156465 
There are two records for 'decane' and the csv shows each record on its own row, but is displaying the statistics "Mean" and "LOQ" in the stats column for both records. Could  this be because it is combining records based only on the 'chemical name' column?

Here is the example csv file: [ex LM data download .csv](https://github.com/HumanExposure/factotum/files/8933733/ex.LM.data.download.csv) (I'm not sure the download is available anymore, since we rolled it back)

This is a screenshot of what it looks like on stg. 
![image.png](https://images.zenhubusercontent.com/5f318c2978fa23cbc1a57b71/f9cb6e74-adc3-4358-a49f-a6dba8d0c7de)

Definition of Done:
• Applies to the LM document download
• Each chemical record should have its own row in the document, and should only display the statistic associated with that record. 
• I would like to change the display of this data, so that each section of the 'statistical values' has its own column. (i.e. 4 columns for the statistic name, value, unit and stat_type) 
• If there are multiple statistics associated with a single chemical record, display each statistic on its own row, duplicating the other chemical information.

**Comment by Sakshi-Handa** [comment]
Also this is a more drastic example, a download from the 3M document:
https://ccte-factotum-stg.epa.gov/datadocument/1643104/

[2013_data_summary_report_chemicals_20220616.csv](https://github.com/HumanExposure/factotum/files/8933745/2013_data_summary_report_chemicals_20220616.csv)

Note that there are multiple 'Mean' and "LOQ" values reported within each row in the csv. However, each of these values is represented on a separate chemical record on the /datadocument/ page.

**Comment by leogi22** [comment]
Yes, they are aggregated by 'raw chemical name', the value that in the testing seemed the natural way to represent it. I'll change that to leave it on each row basis
