### ISSUE TITLE
create linker table from product to product category (13 pts)

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#232]
As Damien the Decision Maker
I want to have the ability to assign multiple PUCs (product categories) to a product
so that I can record a product categorized into a PUC through multiple methods.

Problem: In the future, there will be multiple ways to assign a PUC (product category) to a product. Currently, the PUC assigned to a product is stored within the product table, allowing for only one PUC assignment per product.

Please pull the prod_cat_id (and associated fields, see below) out of the existing product data model. A new data model will be created (product_to_puc) which will be the linker between the existing product and productcategory data models.

There is a 1 to many relationship between the existing product data model and the new product_to_puc data model.
There is a many to many relationship between the new product_to_puc data model and the existing productcategory data model.

**The new product_to_puc data model will contain the following fields**
Fields moving out of product data model (these fields all exist in the current product data model, and will be moved out of the product data model to live in the new product_to_puc data model)
   - prod_cat_id
   - puc_assigned_script_id
   - puc_assigned_time
   - puc_assigned_usr_id

In addition, the product_to_puc data model will contain the following new fields:
  - product id (link to id field in product data model)
  - classification method (this refers to a value from a pick list of classification methods, see below; all existing data will have the value 'Manual')
  - classification confidence (decimal(6,3), all existing data will have the value '1')

**Classification method**
There are 2 different methods which will be used to classify products into pucs. We do not expect the classification methods to change often thus we don't need to have this implemented as editable options in the admin interface. Options for pick list of classification method are:
   1. Manual - what we currently have implemented, manual assignment of a product category to a product. 
  2.  Auto - 'automatic' assignment of a product category to a product, done using a machine learning classifier model (coming soon!)

Re. Changes to implementation in the application - when a PUC associated with a product is displayed, if only one PUC is assigned to a product, that PUC is displayed. If more than one PUC is assigned to a product, the manually assigned PUC is displayed (i.e. manual trumps auto). 

Definition of Done:
1. product_to_puc data model exists and contains above defined fields
2. puc related fields are moved out of the product model and into the new product_to_puc data model
3. current PUCs assigned to products are maintained (data migration)
4. change name of productcategory data model to puc

Test: confirm that method returns the proper primary PUC

**Comment by Daveahern** [comment]
@kdionisio We're reviewing the work I've done on this issue and @debboutr  has raised some questions regarding returning the "uber" PUC for a product.

Right now, I've implemented it such that if there is a single Manually assigned PUC it returns that preferentially.
If there is not a single Manually assigned PUC, then if there is a single Auto assigned PUC, it returns that.

In any other case it returns nothing.  We don't have any rules on what to do if there is no Manual PUC and more than one Auto PUC.  My assumption is that handling multiple Auto assigned PUCs will come later.

We are also operating under the assumption that there may be only one (or zero) Manually assigned PUC.

**Comment by kdionisio** [comment]
@dahern this is fine, thank you! You are correct that at this point we are
assuming there would be maximum of one manually assigned PUC and/or one
auto PUC. We will handle multiple manual PUCs and/or multiple auto PUCs at
a later time. Thanks!
