### ISSUE TITLE
Analyze entire test suite

### ISSUE THREAD

**Issue by kbfepa** [HumanExposure/factotum#2380]
Currently, there are outdates tests in our test suite, and some may need updates. This is a ticket to test the entire test suite (every module) and analyze the results.

To Do/Acceptance Criteria:
- Run every test module (also MMDB)
- Identify failing tests for each, and populate a table that includes (module, test name, failure point/assertion) information for each failure. If can be easily done, identify source of failure too.

**Comment by hausman-gdit** [comment]
### 60659f dev branch - Overview

- **Integration**: failures=2, errors=3
- **Functional**: failures=9, errors=1
- **Unit**: failures=1

`all_tests_curated_kh.txt` => all results with some lengthy bits removed
`foo_bar_raw.txt` => the 'raw' copy paste.  

[all_tests_curated_kh.txt](https://github.com/HumanExposure/factotum/files/9427178/all_tests_curated_kh.txt)
[integration_raw_kh.txt](https://github.com/HumanExposure/factotum/files/9427179/integration_raw_kh.txt)
[unit_raw_kh.txt](https://github.com/HumanExposure/factotum/files/9427180/unit_raw_kh.txt)
[functional_raw_kh.txt](https://github.com/HumanExposure/factotum/files/9427181/functional_raw_kh.txt)

**Comment by leogi22** [comment]
Integration: failures=4, errors=8
Functional: failures=7, errors=1
Unit: failures=1
[all curated.txt](https://github.com/HumanExposure/factotum/files/9438224/all.curated.txt)

**Comment by kbfepa** [comment]
(Currently working out issues with integration tests, will update that later)

- Functional: failures=18,** errors=5 (out of 330)
- Unit: failures=1, errors=1 (out of 78)


[functional_raw_kbf.txt](https://github.com/HumanExposure/factotum/files/9471277/functional_raw_kbf.txt)
[unit_raw_kbf.txt](https://github.com/HumanExposure/factotum/files/9471281/unit_raw_kbf.txt)

**Comment by hausman-gdit** [comment]
@leogi22 Can you check for me that your updated seed data has been checked in?

**Comment by hausman-gdit** [comment]
@kbfepa @leogi22 I've aggregated the results, should we do a little chit chat about it sometime?
[Test Matrix_partial.xlsx](https://github.com/HumanExposure/factotum/files/9479194/Test.Matrix_partial.xlsx)
