### ISSUE TITLE
Register documents (13 pts)

### ISSUE THREAD

**Issue by dmlyons2** [HumanExposure/factotum#24]
This ticket relies on completion of ticket #23 

As a data collector,
I want to be able to register documents associated with a data group
so that I can later upload files associated with each document.

The '[Data Group Show'](https://balsamiq.cloud/sadlf/psb72/r465A) page should include
- the name of the data source
- Description of data source
- Downloaded by
- Date Downloaded
- Link to Git URL where scraping script is stored

Prior to adding the first data group, the only buttons/links enabled on the Data Group Show page are:
- link to download .csv template for registering documents (link below the 'Register Documents' button on the mockup)
- Register Documents button

.csv template for registering documents will include the following columns in this order (names of columns do not need to exactly match the below, can be changed, e.g., to 'filename'):
- filename of pdf (required)
- title of pdf (required) (e.g. product name, if no title of pdf available, title is the file name of pdf)
- preliminary product category (not required)
- URL to the pdf (not required)

When user selects the register documents button, user should be prompted to upload a single .csv file, in the format indicated above, with completed rows. Each row represents one data document.

After successful upload of the 'register documents' .csv file, the 'register documents' button will be disabled and the 'upload documents' button will be enabled. 'Successful' upload is defined as checking to ensure each cell in the file is formatted appropriately/as expected. When uploading the completed template, column headers will still be included/should be expected.

After successful upload of the 'register documents' .csv file, the table at the bottom of the 'Data Group Show' page will be created, populated with one row for each document in the register documents file which was just uploaded.

After successful upload of the 'register documents' .csv file, a link will appear to  download a 'registered_documents.csv' (link which appears above the 'register documents' button in the mockup). This .csv file will be identical to the .csv file which was uploaded by the user when documents were registered, with the addition of a column listing the unique file identifier the application has assigned to the document.

**Comment by kdionisio** [comment]
@debboutr commented in slack on 12/1/2017:
Anyone have an opinion about registering a csv upon the creation of a *datagroup*? Is there a case where we would want a *datagroup* created w/o records registered? This is how it currently is, but it might make sense to do the file upload (`register_records.csv`) and deliver the csv template when we create/edit the *datagroup*?

Also, I'm assuming that the records associated w/ a *datagroup* will only be registered once, but then `.pdfs` uploaded later to be matched and extracted, will there be a case where we want to append to registered records? or would that just be done through the creation of a new *datagroup*?

**Comment by kdionisio** [comment]
@debboutr 
I think this is fine, I do not see a reason why a user would need to create a data group prior to registering the records/documents. So, you can move forward with implementation such that the documents are registered at the same time the data group is created.

We would NOT have the case of appending to a data group with additional records - if you have additional documents to register, those will be entered/registered as a new data group.

**Comment by mwfrost** [comment]
When creating a new Data Group, the Extraction Script needs to have "https://" or "http://" at the beginning of the URL. If the user supplies a url like `github.com/HumanExposure/MSDS_scraper_script.rmd` without the prefix, then the Data Group show page displays that link as a local relative link to `http://127.0.0.1:8000/datagroups/github.com/HumanExposure/MSDS_scraper_script.rmd`
