### ISSUE TITLE
Fixing formatting issues due to OneEPA Template

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#2416]
We recently added the OneEPA header/footer and styling to Factotum. This has caused some formatting issues that need to be addressed before we deploy changes to the production application. 

Things to Fix:
	• Need more space between bottom of the Factotum page (usually tables) and the OneEPA footer
	• The QA and Comment button in the nav bar show up as black rather than blue. 
	• For the Logged in User: The internal search bar is really small, bc of all the other tabs.
	• On the datagroup page, there is an empty row at the bottom of the documents table
           https://ccte-factotum-dev.epa.gov/datagroup/355/
	• On the product page, the linked document cuts off
           https://ccte-factotum-dev.epa.gov/product/251282/
	• On the data document page, the spacing is off between the chemical and CAS on the right-hand chemical list 
           https://ccte-factotum-dev.epa.gov/datadocument/1372995/#
- error pages
- 'active' element state
- collapse the EPA header

**Comment by hausman-gdit** [comment]
Sakshi, can you upload a screenshot of the search box issues?
> • For the Logged in User: The internal search bar is really small, bc of all the other tabs.

**Comment by Sakshi-Handa** [comment]
Here are some screenshots of the issues: 

![image.png](https://images.zenhubusercontent.com/5f318c2978fa23cbc1a57b71/e1466183-3cef-4333-be4d-12c2c9391f9f)
The search bar might just be small bc I'm using my laptop screen. Also, its fixed when I zoom out (90%), bc all the tabs shrink a bit. 

![image.png](https://images.zenhubusercontent.com/5f318c2978fa23cbc1a57b71/73f82382-6818-485e-b6a7-b71721551717)
The data group table row is not a big deal. it looks like it might just be part of the table formatting?

![image.png](https://images.zenhubusercontent.com/5f318c2978fa23cbc1a57b71/5e846962-aae0-4add-84a9-284deae37b0c)
The product page is a priority to fix, bc a user can't access the datadocument page.

![image.png](https://images.zenhubusercontent.com/5f318c2978fa23cbc1a57b71/9192e47d-0284-4925-b78e-e2ec7ca205b8)
Its hard to tell which CAS number belongs to which chemical name.
