### ISSUE TITLE
upload/download extracted text functionality specific to data group type

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#242]
Dependent on completion of #239 

As the Product Owner
I want to limit the options available for extracted text upload on the Data Group Detail page
To streamline the application and reduce confusion for data entry staff

On the Data Group Detail Page (http://factotum.epa.gov/datagroup/27) the user options related to download/upload of extracted text (and templates) should be specific to the data group type to which the data group belongs. For example, if the data group has type 'Composition,' the download/upload extracted text functionality should be appropriate for composition data. 

Definition of Done: Extracted text template and extracted text format expected for upload on data group detail page should be appropriate for the data group type the user is looking at.

**Comment by zachmunzenrider** [comment]
I propose we make the grouptype of any given datagroup immutable. Once you've created a group of a given type, it needs to stay that type permanently. This would mean making the group_type field uneditable on the update form.

**Comment by zachmunzenrider** [comment]
I also think this ticket is a good opportunity to refactor the various column lists to one specific variable/location, which will make future changes more straightforward
