### ISSUE TITLE
Error loading table on QA Summary page

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#2431]
Getting an error on certain QA Summary pages, and the table never loads.

https://ccte-factotum.epa.gov/qa/chemicalpresencegroup/728/summary/

DataTables warning: table id=document-table - Ajax error. For more information about this error, please see http://datatables.net/tn/7

![image.png](https://images.zenhubusercontent.com/5f318c2978fa23cbc1a57b71/ec74bd1b-7b68-4f73-bd30-a03c7a030146)

It might be bc there are too many chemical records in this document (2.7k)?
I think so, bc i found the same issue in the Drugbank group, and these documents also have 1k+ chemicals. 
https://ccte-factotum.epa.gov/qa/chemicalpresencegroup/836/summary/

**Comment by leogi22** [comment]
The page does load up in 60 seconds for 728 and 93 seconds for 836

**Comment by leogi22** [comment]
After my fix the page now loads in 5 seconds and 15 seconds respectively!!!

**Comment by Sakshi-Handa** [comment]
> After my fix the page now loads in 5 seconds and 15 seconds respectively!!!

Wow!

**Comment by leogi22** [comment]
Praise the Lord!
