### ISSUE TITLE
upload extracted text for habits and practices data documents (13 pts)

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#244]
Dependent on #239 which creates data group types

As Karyn the curator
I want the ability to upload extracted text for habits and practices related data documents
So that I can link this data to PUCs

We have a new data group type ('Habits and Practices') for which we will be uploading data documents. We need the ability to upload the extracted text for data documents with a data group type of habits and practices.

Extracted text for Habits and Practices data documents will include pieces of data which can fit into the current/existing extractedtext data model, and new pieces of data specific to H&P (analogous to how we have MSDS data which goes into the extractedtext data model, and then additional data which goes into the extractedchemical data model).

Extracted H&P data which will be uploaded but can fit into the existing extractedtext data model:
- identifier for data document (required)
- doc_date (not required)

Extracted H&P data which will be uploaded and needs new fields (i.e., the 'extractedchemical' data model but for H&P data). There will be a one to many relationship between the current extractedtext data model and this new extractedHandP data model. There will be a one to many relationship between the new extractedHandP data model and the existing PUC data model.
- product surveyed (text, max 50 characters - this is the exact product used to get the data, for example, a study looking at use of glue gave us information on use of 'Hot melt adhesive glue') (mandatory)
- PUC (from the PUC data model, following on the above, this is the product category which we have linked the above product to, e.g., we may link all specific glues to a 'glue' PUC)
- mass (decimal(12,5)) (not required)
- units for mass (text, max 40 characters) (required IF mass is populated)
- frequency (decimal(12,5)) (not required)
- units for frequency (text, max 40 characters) (required IF mass is populated)
- duration of use (decimal(12,5)) (not required)
- units for duration of use (text, max 40 characters) (required IF mass is populated)
- prevalence (text, max 200 characters) (not required)
- notes (open text field) (not required)
- updated at (required)
- created at (required)

Definition of done:
- data model exists to store habits and practices extracted data
- ~~functionality exists in the application to upload habits and practices extracted data when the data group type is habits and practices (also includes downloadable template for habits and practices extracted text)~~

**consult below link for examples (on page 3 of the document linked, the table titled 'relevant data records' is an example of habits and practices extracted text data). In our case, 
- the 'data source' column from that table is a data document (in our case would be identified by the data document id)
- the 'type of product' column from that table is the 'product surveyed' I detailed above (i.e., the more descriptive name of the actual product the study looked at)
- the product category identified at the top of the page (e.g. 1. P.AC.010.029 arts and crafts adhesive-spray) is representative of a product category from our PUC data model, which would be associated with every entry in the 'relevant data records' table

https://github.com/HumanExposure/SHEDSHTRPackage/blob/master/Documentation/Source_variable_inputs.pdf

Test: ability to create Habits and Practices record in new extractedHandP data model; ability to link extractedHandP record to multiple PUCs

**Comment by zachmunzenrider** [comment]
A few questions came up working on this ticket:

1. Pretty sure the references to the productcategory data model are referring to the PUC data model, but would like confirmation

2. For each unit field (mass, frequency, duration), the ticket specifies that "if mass is not null, this field cannot be null." I think this is a typo, and that each unit is required if its corresponding field is not null. Please confirm.

3. The "product surveyed" field is specified as a text field, and I've coded it as such. Should this be instead a foreign key to the product table? Or do we not necessarily have a known matching product at the time the record is created?

4. The ticket states, "There will be a one to many relationship between the new extractedHandP data model and the existing productcategory data model." I think the ticket means to say the opposite: that there can be many extractedHandP records mapping to one productcategory record, and I've coded accordingly. Is this correct?
