### ISSUE TITLE
CP Tagset filter Refinement

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#2444]
I was testing the CP tagset filter on stage. It works in the majority of cases, but I realize it ignores certain documents, that have multiple different tagsets at the chemical level. (i.e. the document has different chemicals tagged, some with detect, others with non-detect) By ignore I mean, there is no filter corresponding with these documents. This results in a difference between the document count in the table and the sum of the documents covered by the tagset filters. 

Here is an example:
https://ccte-factotum-stg.epa.gov/list_presence_tag/421/

![image.png](https://images.zenhubusercontent.com/5f318c2978fa23cbc1a57b71/c61ac748-9bad-4305-9faf-ee7aad9663bc)
in the documents table, there are 8 documents in which 'wastewater' appears as a tag. 

![image.png](https://images.zenhubusercontent.com/5f318c2978fa23cbc1a57b71/f2e0d3ed-a815-4d0b-8bb5-b98bb6465f69)
But on the filter above, the related documents count adds up to 7 documents.  

The missing document is https://ccte-factotum-stg.epa.gov/datadocument/1371479/
Presence and Distribution of Wastewater-Derived Pharmaceuticals in Soil Irrigated with Reclaimed Water Table 2, which has these tags appearing somewhere in the document
 [detected ; nondetect ; pharmaceutical ; wastewater]

On the /datadocument/ page, there are chemicals tagged with either [detected ; pharmaceutical ; wastewater]
or [nondetect ; pharmaceutical ; wastewater]
![image.png](https://images.zenhubusercontent.com/5f318c2978fa23cbc1a57b71/3ef4d796-0e77-4a9c-9f2b-e9eebf89ef17)

I would like CP tagset filter to show this missing document under both the [detected ; pharmaceutical ; wastewater]
and the [nondetect ; pharmaceutical ; wastewater]. 

Similarly on the /chemical/ page, https://ccte-factotum-stg.epa.gov/chemical/DTXSID2020006/
![image.png](https://images.zenhubusercontent.com/5f318c2978fa23cbc1a57b71/2ac69982-0eff-4957-a2fb-660b0fc7b752)
there are 27 CP documents, while the tagset filter adds up to 26. It is missing a filter for the [nondetect ; pharmaceutical ; wastewater], for the document 'Presence and Distribution of Wastewater-Derived Pharmaceuticals in Soil Irrigated with Reclaimed Water Table 2'
![image.png](https://images.zenhubusercontent.com/5f318c2978fa23cbc1a57b71/0ef1d054-af0b-4c64-b443-eddc8a87473b)

**Comment by leogi22** [comment]
after implementing the above, the total count of all tagsets will still not match the total count of the documents since we are adding the document to potentially several tagsets and not jsut one
