### ISSUE TITLE
502 Error when Uploading Products via script

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#2448]
The curators have reported getting a 502 error when uploading products via script through the UI. 

They are able to submit the script, but the page times out at some point, and ends up showing a 502 error. Some of the products have been uploaded. 

Note: This only occurs on Production. I was able to upload products to stg and dev with no errors. 

![image.png](https://images.zenhubusercontent.com/5f318c2978fa23cbc1a57b71/e0aeb7ff-7049-4633-8655-4e42f26ae2ef)

Ex. https://ccte-factotum.epa.gov/datagroup/60/
Go to the 'Products' tab. add the attached product csv file. 

[hp 1_2 create products.csv](https://github.com/HumanExposure/factotum/files/9842029/hp.1_2.create.products.csv)

**Comment by leogi22** [comment]
with parallelization, able to bring upload time from 5 mins to 40 s!
