### ISSUE TITLE
Add Help Text to Product Page

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#2449]
As a Factotum Admin,
I would like to add the hover helptext for the fields on the Product detail page.
So users can know what each field represents. 

Ex. https://ccte-factotum.epa.gov/product/584583/

Definition of Done:
Applies to the product/#/ page
I would like help text to appear for all labels on the page, including PUC labels, Attributes, and Product fields. (will add descriptions below)

**Comment by kbfepa** [comment]
We've got all kinds of hover text in various places now, are any of them repeated? If so, it would be worth consolidating their definitions in one file so that we can keep it DRY.
