### ISSUE TITLE
Add test coverage for extracted text upload functionality

### ISSUE THREAD

**Issue by mwfrost** [HumanExposure/factotum#249]
Write a test that uploads a table of valid ExtractedText objects and add it to the test suite. The test should confirm that the uploaded file uses all the same columns as the template uses (use `raw_chem_name` instead of `chem_name`, for example), and it should include empty cells for the nullable fields (like `doc_date`).

Related issues:
https://github.com/HumanExposure/factotum/issues/246
https://github.com/HumanExposure/factotum/issues/247
https://github.com/HumanExposure/factotum/issues/248

**Comment by kdionisio** [comment]
work should be done in #246 and #247
