### ISSUE TITLE
download chemical list ( 5 pts)

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#252]
As Brian the chemical curator
I want to download a list of chemical names and CAS that have not yet been assigned a DTXSID
so that I can complete chemical curation (i.e., register the chemicals in the DSSTox database)

Definition of Done:
User should have the ability to download a .csv file which includes any raw_cas and raw_chem_names which do not yet have an SID assigned
- should pull from all raw_cas and raw_chem_name fields
- csv to download should include the raw cas, raw chem_name, and a unique identifier that will allow the data to be pushed back in to Factotum once the SID has been assigned (assignment of SID will be done outside of the application)
- download can be accessible from the Get Data page

**Comment by kdionisio** [comment]
Please speak with Kathie about a slight modification to this ticket - we have since realized there may need to be a cap on number of chemicals included in a single download due to the number of records we have.

**Comment by mwfrost** [comment]
@kdionisio As it is currently set up, the `DSSToxSubstance` model only links to `ExtractedChemical`, not `ExtractedFunctionalUse` or `ExtractedListPresence`. It sounds from this ticket like you want to be able to match DSSTox SIDs to all three of the models. Has that ever been specified in a ticket?

Given my understanding of this ticket and the redundant nature of those three data models, we need to create a new abstract class called `RawExtractedChem` that stores the `raw_cas` and `raw_chem_name` values. Then the three `Extracted...` models will inherit those attributes, and the `RawExtractedChem` model will also manage the link between the raw data and the DSSTox records.

This is a fairly large change to the codebase, so I welcome any comments or advice.

**Comment by kdionisio** [comment]
@mwfrost oooohhhhhhh that is interesting. And very good to know. And not good. Yes we definitely need all of the various models that include raw_cas and raw_chem_name to link to DSSToxSubstance. I'd have to go back to the tickets where we created the ExtractedFunctionalUse and ExtractedListPresence models to see what was specified. But regardless if it is not set up that way it needs to be done now. We can talk Monday if you'd like, if you feel this is a big enough change to warrant an additional ticket of it's own.

**Comment by mwfrost** [comment]
I'd like to set up a separate ticket, yes.

*Refactor Extracted... Models to Share "Raw Chemical" Attributes*

All the models that currently include `raw_chem_name` and `raw_cas` should inherit those properties from a new abstract base class called `RawChemical`. The models that will share this inheritance currently include `ExtractedFunctionalUse`, `ExtractedChemical`, and `ExtractedListPresence`. The new abstract class will manage the association between these raw chemical attributes and their "curated" records in the `DSSToxSubstance` model.

**Comment by kdionisio** [comment]
@mwfrost should I just close this ticket and rewrite a new one indicating what I *need*, and then you all can figure out how to make that work with the recent changes? It seems some of the details I wrote in the above is no longer accurate/needed due to the changes you made to the models and how this type of data is stored.
