### ISSUE TITLE
testing - get percent checked (2 pts)

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#257]
to replace one part of test_scoreboard (from functional_tests_rollback.py)

new test to cover nav bar as a whole, checking to make sure links in nav bar work

**Comment by zachmunzenrider** [comment]
I've refactored these tests, among other things, to use the lxml package as an alternative to Selenium. Everything that Selenium was being used for in these tests was HTML scraping, which we can do more quickly with lxml. I added it to my environment using Anaconda. (When I tried to install it with pip I got some dependency errors; YMMV)
