### ISSUE TITLE
Approving all ExtractedText objects in a QA Group results in an error

### ISSUE THREAD

**Issue by mwfrost** [HumanExposure/factotum#276]
After a user approves the last ExtractedText object in a QA group, the view attempts to route to a nonexistent page.

### To reproduce the unexpected behavior

From http://127.0.0.1:8000/qa/, click "Begin QA" on a ExtractionScript's row in the table, click the QA Checked = False button for the first document in the QA Group. Click  "Approve" on every Extracted Text object it presents. After the final approval, the page throws an error.

### To fix

Handle cases where the ExtractedText object's `next_extracted_text_in_qa_group()` method returns zero.

**Comment by mwfrost** [comment]
I think I have fixed this, but I need to write tests against it.

**Comment by dmlyons2** [comment]
Dave and Kathie will write test and close ticket

**Comment by dmlyons2** [comment]
Test ticket is #368
