### ISSUE TITLE
Review 'on_delete=models.xxx' model usage

### ISSUE THREAD

**Issue by zachmunzenrider** [HumanExposure/factotum#293]
All users of the factotum should have confidence that deleting an object doesn't result in unintentional deletion of other records.

The factotum models currently have 25 foreign key attributes set to "on_delete=models.CASCADE". This means that if one of those foreign keys were to be deleted (intentionally or by accident), then all the records linking to that key would be automatically deleted as well. This could result in a loss of data.

![image](https://user-images.githubusercontent.com/33101677/42585331-4e0c4a0c-8503-11e8-921d-65263677c4b1.png)

There are another 5 attributes set to "on_delete:models.PROTECT:

![image](https://user-images.githubusercontent.com/33101677/42585609-1a022014-8504-11e8-90f2-e43be58fc150.png)

CASCADE: Cascade deletes. Django emulates the behavior of the SQL constraint ON DELETE CASCADE and also deletes the object containing the ForeignKey.

PROTECT: Prevent deletion of the referenced object by raising ProtectedError, a subclass of django.db.IntegrityError.

SET_NULL: Set the ForeignKey null; this is only possible if null is True.

SET_DEFAULT: Set the ForeignKey to its default value; a default for the ForeignKey must be set.

**Comment by dmlyons2** [comment]
Please put some specifics in this ticket. For Example: If a user deletes a data source the user would expect that all data groups and data documents and extracted text and etc would be deleted.
