### ISSUE TITLE
Download pdf documents (5 points)

### ISSUE THREAD

**Issue by dmlyons2** [HumanExposure/factotum#30]
Dependent on #25 

As a data curator,
I need to download all pdf documents in a data group
so that I can perform text extraction to obtain information from pdfs.

From the '[Data group Show](https://balsamiq.cloud/sadlf/psb72/r465A)', there will be  button to 'Download Documents.'  When a user clicks this button, this will trigger a download of a .zip file which contains all .pdf documents contained within that data group.

At this point, the .pdf documents will be named with their unique UUID filename.

.zip files do not need to be stored indefinitely, can be cleared periodically from system.

**Comment by kdionisio** [comment]
@dmlyons2 
Do some testing for the above ticket, testing speed of download dependent on number of documents (e.g. how long to zip and download 500 vs. 100 documents).
