### ISSUE TITLE
Functionality to input H&P data (13 pts)

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#300]
As Dot the Data Collector
I need to be able to enter Habits and Practices related data into Factotum
So that the information can be stored and linked to other PUC related data

In #244 (complete) the data models to store Habits and Practices related data were created. We now need to implement functionality to enter the H&P data into the application.

Desired workflow:
1. Dot registers and uploads data documents in a data group of type 'Habits & Practices' (this fits in our current workflow, no work needs to be done)
2. After data documents have been registered in a 'Habits & Practices' data group, Dot should have the ability to manually input H&P related data (e.g., via a webform), related to each registered data document. Keep in mind that a single data document may have multiple 'sets' of H&P data related to it.

Definition of Done:
Functionality exists to enter H&P related data within the application.
 - H&P data which is input should be linked to a specific data document
 - user should have ability to input all user populated fields (i.e., not the 'created at' and 'updated at' fields) from the Habits & Practices data model created in #244 
 - user should be able to link input data to one or more (already created) PUCs from the PUC data model (e.g., similar to how a PUC is selected when a user assigns a PUC to a product, except in this case we need to be able to select >1 PUC)

**Comment by mwfrost** [comment]
When the user inputs Habits & Practices data, are those values stored in the `ExtractedHabitsAndPractices` data model, or will there be another data model to store the human-entered data?

At one point, it was explained to us that the `ExtractedChemical` model stores just the initially loaded form of the data, and the more refined chemical data is stored as DSSTox objects. Am I remembering this right? Is there a comparable draft/final paradigm at work for the H&P data?

**Comment by kdionisio** [comment]
The human entered data will be stored in the Extractedhabitsandpractices data model.

As discussed on stand-up on 7/23/2018, when linking to enter data for a specific data document in a data group of type Habits and Practices, user will first be brought to a web entry form where they can enter the meta-data for the data document. Fields available on this web entry form should be:
- title (datadocument model)
- organization (datadocument model)
- document_type_id (field is in the datadocument model....can this be a drop down menu of the options in the documenttype model, which have the corresponding group_type_id for the habits and practices data group?)
- doc_date (extractedtext model)
- extraction_script_id (I don't need this field but I think you said it is required? You can either put it on the web form as a drop down list selection as we normally do for selecting the extraction script, OR you can default this to a dummy 'Manual' extraction script which I can register now, since these are all being manually extracted)

If it is a problem to have both fields from the datadocument and extractedtext model on this same web form let me know.

**Comment by debboutr** [comment]
@kdionisio the top 3 attributes above will have come into the DB through the "register_records.csv", so I think all we will need to add is the 'doc_date' if you want to just let me know what the 'title' or 'pk' of the dummy extraction script that you make. Unless you want to have the ability to edit the DataDocument attributes we could do that, but it would probably make more sense to make it flexible to all DataDocuments, not just stuck in here where I am trying to make the ExtractedText object that all the HabitsnPractices will be linked to. For now I'll just make the form with the date and a datepicker on it, but if you don't think this will work we can talk later.

**Comment by kdionisio** [comment]
@debboutr Good catch, yes the first three fields can be entered through registered records. We can talk more on stand-up.
I registered the dummy extraction script in Factotum. It is id = 14 in the 'script' data model
