### ISSUE TITLE
eliminate date format check for doc_date (3 pts)

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#308]
Currently there is an inconsistency in the doc_date field in the extractedtext model. The doc_date field is a character field, however when uploading extracted text the code checks to make sure the data being uploaded to the doc_date field is in YYYY-MM-DD format. Please remove this check so that doc_date can be uploaded in any free text format. This flexibility in uploading doc_date is necessary because doc_date refers to the date on a data document, which may be present as, for example, Month-Year. 

Also change the doc_date field in the extractedtext model to be max 25 characters

Definition of Done:
1. Extracted text upload no longer forces data to be in a specific date format
2. Ability to upload doc_date data with up to 25 characters

Test: be able to enter arbitrary character date string (e.g. Nov 1984) for the doc_date field when you upload extracted text

**Comment by debboutr** [comment]
remove/change test in `test_extracted_text.py` w/ this tix.
