### ISSUE TITLE
Summary metrics by chemical report (20 pts)

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#312]
Dependent on #312

As a consumer of the data stored in Factotum
I want to access a report of summary metrics by chemical of interest
So that I can use the summary metrics in my own research.

Reports will be accessible from a 'Get Data' page (created in #322). For mock-up of the new 'Get Data' page, see 1st slide in the mock-up attached. Specific text to be included on the Get Data page is shown in the Mock-up.

For the 'Summary metrics by chemical' report (1st block on the 1st slide of mock-up), user should be able to download a template CSV (template provided in attachment), and then upload a CSV containing a list of DTXSIDs of interest (example of upload file provided in attachment). Upon uploading, the user is able to download a CSV file containing the summary metrics by chemical for the list of DTXSIDs of interest.

The report will provide back the list of DTXSIDs which were uploaded (as rows in a CSV) along with a number of different metrics for each DTXSID (as columns of the CSV). Columns of the CSV should include (with column name in parentheses): 
- DTXSID (this should be identical to the list of DTXSIDs uploaded by the user) ("DTXSID")
- Number of PUCs the chemical is associated with (where 1 PUC = 1 entry in the puc data model) ("PUCS.n")
- Number of data documents the chemical is associated with ("datadocs.n")
- Number of data documents with weight fraction data that the chemical is associated with (where a data document with weight fraction data is defined as a data document which has associated records in the extractedchemical model which have either raw_min_comp, raw_max_comp, or raw_central_comp populated) ("datadocs_w_wf.n")
- Number of products the chemical is associated with (where product is defined as an entry in the product data model) ("products.n")

Note chemicals of interest will be identified by their DTXSID, accessible through the 'sid' field in the dsstoxsubstance model. Thus only extractedchemical data which has been linked to the dsstoxsubstance model will be used to populate the report.

File name of the report should include the date the report was generated.

Definition of Done:
1. Ability to download CSV template from reports page
2. Ability to upload CSV containing a list of DTXSIDs of interest
3. Ability to download the 'Summary metrics by chemical' CSV report (populated with data), with date generated in the filename
4. Ability to download the data dictionary (data dictionary file provided in attachment)
5. Text related to summary metrics by chemical report exists on Get Data page (see top box of slide 1 of mockup for text)

[Reports.zip](https://github.com/HumanExposure/factotum/files/2205804/Reports.zip)

Tests: test should exist for each metric to make sure that metric is being created correctly

**Comment by mwfrost** [comment]
Can we make this two tickets? One for the Get Data page and another for this report?
