### ISSUE TITLE
Product Page: PUC Info and Assign PUC (5 pts)

### ISSUE THREAD

**Issue by dmlyons2** [HumanExposure/factotum#313]
Currently the product page (http://factotum.epa.gov/product/1783) as an example, shows:

Product Use Category
PUC Assignment Script
PUC Assigned By
PUC Assignment Date

The desired behavior is to only show this if the fields are not null.

If there is not an assigned PUC
I would like to be able to assign one from this page
If there is an assigned PUC I would not have the ability to assign one.

From Matt's comment below: this is the desired behavior for assignment of PUC, with the exception that when the 'submit' button is pushed on the PUC assignment page, user will need to be redirected back to the product page they had just come from (this behavior of the submit button is different from the behavior of the submit button when you are on the PUC assignment page through the 'link products to PUCs' part of the application). When user is returned to the product page, they should then see the above fields related to the PUC which was just assigned.

Note all of the above should be based on the manually assigned PUC (there is an option to have an auto assigned PUC but for now we are just dealing with manually assigned PUC).

Test: 
a) if product does not have assigned PUC, does 'assign PUC' button exist? 
b) if product does have assigned PUC, data is present in view
c) if product does not have assigned PUC, data is not present in view.

**Comment by mwfrost** [comment]
Does the ticket require the PUC assignment to be internal to the product detail page?

The quickest way to add this functionality would be to simply add a link in the page to `http://127.0.0.1:8000/product_puc/[pk]` where `[pk]` is the id of the Product. If the assignment must happen in the product detail/CRUD page, then we can refactor and duplicate the logic from the `product_puc` assignment page.

**Comment by kdionisio** [comment]
I would be fine with Matt's suggestion above re. linking to another page to do the PUC assignment.
