### ISSUE TITLE
Product Page: Edit Product (5 pts)

### ISSUE THREAD

**Issue by dmlyons2** [HumanExposure/factotum#314]
From the product page (http://factotum.epa.gov/product/1783)
I would like the ability to edit:  

Title, brand_name, size, color, short and long description, manufacturer, model_number

Functionality can exist in the form of an 'edit' button in upper right which brings you to a web form with editable fields

**Comment by mwfrost** [comment]
This and ticket https://github.com/HumanExposure/factotum/issues/315 both apply to the `product_detail.html` template. They should probably be done in series rather than concurrently.
