### ISSUE TITLE
View extracted Habits and Practices data (13 pts)

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#317]
As a user of exposure model input parameters
I want to view extracted Habits and Practices data related to a specific PUC
So that I can make decisions on input parameters for exposure modeling

On the 'Get Data' reports page (created in #312 , also see page 1 of mockup), retrieval of Habits and Practices data will be a second option for 'getting data.'

User should have the ability to select a single PUC of interest. Same functionality as implemented via the text box on this page: http://factotum.epa.gov/product_puc/4

When user selects a single PUC of interest, user is brought to a page where they can view all extracted Habits and Practices data related to the PUC (see page 2 of mockup for example layout and specific text to be included on page).

On the page, user will see a card (e.g., [bootstrap cards](https://getbootstrap.com/docs/4.1/components/card/)) for each data document belonging to a data group of type Habits and Practices (id for grouptype model = 4) which is associated with the PUC selected.

For each applicable document, within the card, user will see:
- the title of the data document, where the title is a link taking the user to the original data document
- product_surveyed
- mass along with mass_unit (e.g. if mass = 4, mass_unit = gm, user sees 'mass: 4 gm')
- frequency along with frequency_unit (similar to above)
- duration along with duration_unit (similar to above)
- prevalence
- notes (dependent on space available, notes could be visible, or notes could be viewed as a [bootstrap 'collapse' component](https://getbootstrap.com/docs/4.1/components/collapse/), where, within the card, the user sees the word 'Notes' and then only sees the actual text of the notes when they click on the collapsed component)

Cards can be tiled on the page as appropriate (e.g. if 4 data documents associated with my PUC of interest, user may see a 2 x 2 grid of cards, where each card displays the above data as it relates to the data document).

Definition of Done:
1. Ability to select single PUC of interest via text box search of PUCs
2. Above is accessible via the 'Get Data' page created in #312 
3. Specific data fields returned are as described above in bullet list
4. Results are only returned for data documents belonging to a data group of type Habits and Practices and associated with the PUC of interest

[Factotum_Reports_Mockup.pptx](https://github.com/HumanExposure/factotum/files/2205816/Factotum_Reports_Mockup.pptx)

Test: displayed habits and practices cards match values returned by ORM queries

**Comment by mwfrost** [comment]
Building a modular PUC-selection widget will also help with https://github.com/HumanExposure/factotum/issues/313
