### ISSUE TITLE
QA - Home page for QA of extracted text data (13 Points)

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#35]
Dependent on #44 

As Karyn the Curator
I want to view a summary of completed QA for extracted text data
So that I can assess what QA work remains and complete said work

[QA Home page mockup](https://balsamiq.cloud/sadlf/psb72/rDD7C)

Within the nav bar of the factotum application, add a new link for 'QA.' When you click on the QA link, you will be taken to a 'home page' for the QA portion of the application.

 For the purposes of QA, data documents will be grouped **based on the script which was used to do the text extraction**. Specifically, this is the script which is listed as associated with each data document when the extracted text is uploaded, identified as the 'extract_script' field in #32. Note this grouping of data documents by extraction script may, but is not required to be, related to the data source and data group to which the data document belongs.

On the QA home page, there will be a table listing all extraction scripts which have been identified within the application (this would be the unique entries in the 'extract_script' field in #32).  For each extraction script listed in the table, we should see the total number of documents in the QA group associated with that extraction script (see #44 for definition of QA group) and a '% QA'ed' statistic, showing the % of documents in that QA group which have been 'approved' with a QA check. When viewing the table, the default should be that any extraction scripts where <20% of associated documents have been QA'ed are visible on the table, and any extraction scripts where >=20% of associated documents have been QA'ed are 'hidden' (similar to how, in GitHub, any 'closed' issues are defaulted to hidden when you view 'issues', as in https://github.com/HumanExposure/factotum/issues). In GitHub these issues are identified as 'closed' and there is an option to view the 'closed' issues if the user desires. Similarly in factotum, the scripts where >=20% of associated documents have been QA'ed will default to 'QA complete', and will be hidden from view. However there should be an option for Karyn to view the scripts identified as 'QA complete.'

Associated with each unique extraction script (whether the script is identified as 'QA complete' or 'QA needed'), there should be a button 'Begin/Continue QA'. If any user has NOT previously done QA on any of the documents associated with that extraction script, the button will read 'Begin QA.' If any user HAS previously begun QA on any of the documents associated with that extraction script, the button will read 'Continue QA.' Note that 'beginning QA' can be defined as having clicked once on the 'Begin QA' button, even if no QA was successfully completed.

Definition of Done:
1. A QA Home Page  
2. A link in the nav bar to the QA Home page
3. A Table on the QA Home page
4. A button for each row in the table that will take you to #36 (Not Implemented Yet)

**Comment by debboutr** [comment]
from above...
> the scripts where >=20% of associated documents have been QA'ed will default to 'QA complete', and will be hidden from view. However there should be an option for Karyn to view the scripts identified as 'QA complete.'

How does a Script hold the state of `QA complete`? we just have `qa_begun` T/F

_We don't currently have the functionality of hiding any Scripts that have >=20% documents QA'd_

but, this ticket says it is dependent on #44, which is what I'm working on now. Is the idea that we just want to get to a point of having 20% of `ExtractedText` records QA'd for the data in them to be trustworthy?
