### ISSUE TITLE
Connect elasticsearch test_index to test_local_factotum during tests

### ISSUE THREAD

**Issue by mwfrost** [HumanExposure/factotum#350]
Elasticsearch is using a test-specific index called `test_index` for searches inside tests, but the index is still being populated from the `local_factotum` development database, not the `test_local_factotum` database that is created for testing. All the updates to `test_index` should be using the data in `test_local_factotum`

**Comment by kdionisio** [comment]
hold until after elastic search transition

**Comment by mwfrost** [comment]
Advice on setting up three `settings/` files for dev and testing environments:

https://django-elasticsearch-dsl-drf.readthedocs.io/en/0.17.4/advanced_usage_examples.html#settings

It presumes the use of this approach:

https://medium.com/@ayarshabeer/django-best-practice-settings-file-for-multiple-environments-6d71c6966ee2

**Comment by mwfrost** [comment]
An article that @dmlyons2 found: https://dev.to/jeffreymfarley/mocking-elasticsearch-5goj
