### ISSUE TITLE
error message if product surveyed field is blank (3 pts)

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#352]
On the Habits and Practices data input page (http://factotum.epa.gov/habitsandpractices/263994), please show an error message if a user tries to save data while the product surveyed field is blank. (Currently, if the user tries to save data while the product surveyed field is blank, nothing happens).

Test: developer's choice!

**Comment by debboutr** [comment]
@kdionisio it seems like what is currently on `dev` will require this field. 
![sureveyed_error](https://user-images.githubusercontent.com/7052993/44102762-5103cdbe-9f9f-11e8-9f56-65dfcb37eb85.png)

If there is no data entered into the form before saving, the record will not be made and an error will not be created, there would have to be other data entered in the form for the validation error to be created.

Are you able to get the attached error on a HabitsNPracticesForm?
