### ISSUE TITLE
error when clicking 'assign PUC' button (1 pt)

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#369]
When you click on the 'assign PUC' button from this page: http://factotum.epa.gov/category_assignment/8 the user sees an error instead of going to the page where you can assign a PUC.

Request Method: | GET
-- | --
http://factotum.epa.gov/product_puc/819
2.0.6
NameError
name 'ProductPUCForm' is not defined
/data/code/factotum/dashboard/views/product_curation.py in assign_puc_to_product, line 127
/home/dlyons/anaconda3/envs/factotum/bin/python
3.6.4
['/data/code/factotum',  '/home/dlyons/anaconda3/envs/factotum/lib/python36.zip',  '/home/dlyons/anaconda3/envs/factotum/lib/python3.6',  '/home/dlyons/anaconda3/envs/factotum/lib/python3.6/lib-dynload',  '/home/dlyons/anaconda3/envs/factotum/lib/python3.6/site-packages']
Tue, 7 Aug 2018 11:23:30 -0400

**Comment by kdionisio** [comment]
Error was noticed by developer and issue was already fixed. 

Ticket is to write a test that page loads (status code 200).

**Comment by mwfrost** [comment]
Suggestion to modify `tests/functional/test_nav_bar.py` to make it a suite of comprehensive URL tests

**Comment by kdionisio** [comment]
Closing because error/bug appears to have been fixed when completing related tickets in the Urial sprint.
