### ISSUE TITLE
add url field to datagroup model (3 pts)

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#373]
As Dot the Data Collector
I want to be able to store the url associated with a specific data group
so that I can efficiently access this information in future query requests

Currently the user is able to store a url associated with a data source (dashboard_datasource.url). Please also add a url field to the dashboard_datagroup model (varchar(150), not required). User should be able to enter this information when creating a new data group (i.e., on this page add a field for entering the url: http://factotum.epa.gov/datagroup/new).

Definition of Done:
1. url field exists in dashboard_datagroup model
2. user can enter the data group url on the create data group page (http://factotum.epa.gov/datagroup/new)
3. data group url appears on the data group detail page (http://factotum.epa.gov/datagroup/6)

Test: post request that updates the URL field of a data group

**Comment by dmlyons2** [comment]
Unable to migrate on production data. I have merged dev into this branch, solved merge conflicts and the migration throws the error `django.db.utils.OperationalError: (1054, "Unknown column 'product_category' in 'dashboard_datadocument'")`
