### ISSUE TITLE
reroute user back to data group detail page after editing data group details (3 pts)

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#385]
Currently when a user hits 'submit' on the data group edit page (http://factotum.epa.gov/datagroup/edit/37), they are returned to the data group list page (http://factotum.epa.gov/datagroups/). Please change so that instead they are returned back to the data group detail page (http://factotum.epa.gov/datagroup/37)

Definition of Done:
User is returned to data group detail page after saving edits to the core data group information.

Test: see comment below

**Comment by debboutr** [comment]
```    def test_data_sources_link(self):
        found = resolve('/datasources/')
        self.assertEqual(found.func, views.data_source_list)```
