### ISSUE TITLE
Position of New Data Group button (1 Point)

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#41]
As Kathie the Product Owner,
I want the 'Add New Data Group' button on the Data Source Detail page to appear above the column headers for the table.
So that the application has a consistent look and feel.

**Comment by mwfrost** [comment]
I moved the "Add New Data Group" button into that spot above the far right column, thinking it was useful to have all the CRUD elements closer together. I will take this ticket next week and revert it to the standard location.

**Comment by kdionisio** [comment]
@mwfrost  No problem, my main motivation here is for the placement of buttons to be consistent across pages. If you think it's preferable I'm ok with the opposite of the above, that is moving the 'New Data Source' button on the Data Source listing page down into the column header portion of the table (i.e., the same place you moved the 'Add New Data Group' button to)
