### ISSUE TITLE
display extracted text + data for 'chemical presence list' data group type (5 pts)

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#413]
**Dependent on completion of #393**

On the data document view page (http://factotum.epa.gov/datadocument/1224), extracted text displayed will depend on the data group type. Display of extracted text data from certain data group types was detailed in #393 .

For data group type 'Chemical presence list', please display:

- From extractedtext model, display following fields (all fields should have ability to be edited by the user, with the exception of extraction script)
  -  prod_name
  - doc_date

- From chemicalpresencelist model, display following fields (all fields should have ability to be edited by the user)
  - raw_cas
  - raw_chem_name

**Comment by mwfrost** [comment]
In the course of doing this ticket's work, I'm adding a `code` field to the `GroupType` object. This will be a short code used to perform conditional logic on data groups - an alternative to comparing long strings. 

Unfortunately, django doesn't allow `unique=True` on a character field, so we cannot enforce the uniqueness of the codes.

The `GroupType` object was previously added in migration 0049. I have moved it to 0066.

**Comment by debboutr** [comment]
django does allow unique=True on CharField, check how you have `null` and `blank` defined

[https://docs.djangoproject.com/en/2.1/ref/models/fields/#unique](https://docs.djangoproject.com/en/2.1/ref/models/fields/#unique)

also, you should probably hold off on this ticket until I get done w/ the one I'm currently working on which is where the `ExtractedPresenceList` model is getting migrated in

**Comment by mwfrost** [comment]
@kdionisio , should the Extracted Text section of the Data Document detail page look different when the data group is a Chemical Presence List? The _parent_ objects have a different model type, with type-specific fields like "Cat Code," "CPCat Code," and "Description CPCat." Should those appear in the box under "Extracted Text"? And should they be editable?

**Comment by debboutr** [comment]
tests to write: 

- `/qa/extractedtext/pk` view needs to always have `chem-control` in it's fields for `toggleChemicalEdit` fn
- unit test the `get_extracted_models` and `create_detail_formset` functions
