### ISSUE TITLE
Refactor Extracted[x] object models

### ISSUE THREAD

**Issue by mwfrost** [HumanExposure/factotum#420]
The different object models that are related to ExtractedText might be better off inheriting a common data model.

These models are: `ExtractedChemical`, `ExtractedFunctionalUse`, `ExtractedHabitsAndPractices`, and the forthcoming `[ExtractedChemicalPresence](https://github.com/HumanExposure/factotum/issues/416)`.

**Comment by mwfrost** [comment]
Documentation on how abstract base classes work:

https://docs.djangoproject.com/en/2.1/topics/db/models/#model-inheritance

**Comment by kdionisio** [comment]
completed as #626
