### ISSUE TITLE
combine 'save' buttons on data document view page (2pts)

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#433]
For data group type Composition:
On the data document view page, there currently exists a 'save' button for each individual 'extracted chemical' entry. Please combine, and display only one 'save' button for the entire 'extracted chemical' section (thus the save button would apply to changes for all extracted chemical entries).

For data group type Habits and practices:
Similar to above, please combine so there exists only one save button for the entire 'extracted habits and practices' section.

Definition of done:
One save button for 'extracted chemical' section (data group type Composition) or for 'extracted habits and practices' section (data group type Habits and practices)

**Comment by dmlyons2** [comment]
no test required

**Comment by debboutr** [comment]
this is done in @mwfrost `413` ticket
