### ISSUE TITLE
bug in register records (5 pts)

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#436]
When trying to register records, I receive the following error:

CSV column headers are incorrect for upload. ['filename', 'title', 'document_type', 'product', 'url', 'organization'], should read ['filename', 'title', 'document_type', 'product', 'url', 'organization']

It is not apparent to me what the difference is in the column headers that I am using vs what the application is saying I need to use, so I'm not sure what to fix to resolve the error.

**Comment by debboutr** [comment]
We altered list of filenames when we removed `product` from the register here:
[https://github.com/HumanExposure/factotum/commit/7ba6b9fde4db4125c215e81881753d3607a75650#diff-7c32c55792dc6645cb40c1a327b4c5c9](https://github.com/HumanExposure/factotum/commit/7ba6b9fde4db4125c215e81881753d3607a75650#diff-7c32c55792dc6645cb40c1a327b4c5c9)
but the template loads that same list statically in it's contents, and that wasn't updated.
