### ISSUE TITLE
QA - Creation of QA group (13 Points)

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#44]
As Karyn the Curator,
I want to group data documents into QA groups
So that data documents are ready for QA of extracted text data.

When Karyn pushes the 'Begin QA' button for a unique extraction script on the QA home page (button created in #35), this triggers creation of a 'QA group.'

A QA group is defined as a group of 20% of data documents associated with a unique extraction script. Each extraction script is associated with a single QA group. The documents included in the QA group are randomly selected by the application when a user first starts QA for that unique extraction script (i.e., when they push the 'Begin QA' button on the QA home page).

The application should 'remember' which documents it has assigned to be within the QA group so that Karyn can complete the QA at multiple time points (i.e., QA for a full QA group may not be completed in a single sitting).

Upon hitting the 'Begin QA' button, user is brought to a page with a table listing the data documents that have been assigned to that QA group.

**Comment by debboutr** [comment]
if we grab 20% of documents associated w/ a script, I think we should have a minimum number i.e if we have 100 documents, we would first grab 20, then we would grab (80x0.2)=16, then we would grab (64x0.2)=13, but we would never get to zero. So what would be a good minimum size for a QA group do you think?

**Comment by kdionisio** [comment]
Do you mean minimum size for a QA group in that above MIN documents, the entire set of data documents associated with the extraction script is pulled as the QA group? If so, I would say 20=MIN. So, if less than 20 data documents are associated with a specific extraction script, then *all* data documents associated with that extraction script are included in the QA group.

**Comment by debboutr** [comment]
to be clear, `DataDocuments` are not related to an extraction script until there is an `ExtractedText` object created for them, this is a 1:1 relationship. 

It is likely assumed that this QA process won't begin until the Extracted Text has been uploaded, but if there are any documents that don't have extracted text, they won't be included in the grouping. And likewise, if the `extracted` attribute is set to True on the DataDocument, that doesn't necessarily mean that it will get pulled in, though the way it is currently being managed will produce the result we want.

It is possible, as is shown in our seed data, that we can have a `DataDocument` w/ the extracted attribute set to False, but having an associated ExtractedText object that it will still get pulled in to the QA group. 

It seems like it might be simpler to store the `matched` and `extracted` fields on the `DataDocument` as a boolean checking whether or not the associated record exist in the DB. For instance, if the DataDocument has an associated ExtractedText record, then the table in DataGroup detail would show the green checkmark in the extracted column, seems a little DRYer and then we won't have to manage that field in DataDocument. And similarly, if the PDF exists in the FileSystem, the matched column would go to green too.

This will take a little overhaul on what we have, but I think we weren't able to know how all of these things were going to get put together in the process, so what is there seemed to be the most straight forward at the time.
