### ISSUE TITLE
display associated curated chemicals on data document page

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#444]
As a user of Factotum
I want to see associated curated chemicals when viewing information about the data document
So that I can assess whether the chemical curation is complete, and if the chemical assignment is correct

Definition of Done: On the Data document view page (http://factotum.epa.gov/datadocument/153139/), please display the following fields from the dsstoxsubstance model alongside the appropriate entry for extracted chemical:

true_cas (Label as 'True CAS', perhaps place next to 'Raw CAS' in each box)
true_chemname (Label as 'True chemical name', perhaps place next to Raw chemical name in each box)
sid (label as DTXSID)

*Note the true_cas, true_chemname, and sid fields should *not* be editable

Test: if extracted chemical object has related curated chemical object the curated chemical object displays in the card

**Comment by mwfrost** [comment]
Kathie, the data model allows multiple DSSToxSubstance records to relate to a single ExtractedChemical object. Assuming this is the expected behavior, should the ExtractedChemical card now have a nested series of zero-to-many DSSToxSubstance forms? That will get pretty crowded.

**Comment by mwfrost** [comment]
Should we really be allowing many DSSToxSubstance records per ExtractedChemical record? The old ticket #149 reads as if the relationship should be one-to-one, like between ExtractedText and DataDocument. There is currently nothing to prevent multiple DSSToxSubstance records sharing a common ExtractedChemical foreign key. I just tested it by adding a record to the seed data.

**Comment by kdionisio** [comment]
@mwfrost this relationship between DSSToxSubstance and ExtractedChemical may be set up this way due to a workflow we envisioned previously. We have changed how we are going to do things but perhaps never change the relationship accordingly. The relationship between a DSSToxSubstance record and an ExtractedChemical record will be one-to-one. So I guess this is something that needs to be changed? Let me know if that goes beyond the scope of this ticket (or is something that needs to be fixed before this ticket is done?)

**Comment by mwfrost** [comment]
@kdionisio Thanks for confirming. I think that yes, this change deserves its own ticket, upon which this ticket is now dependent. 
Whether we change the relationship between `DSSToxSubstance` and `ExtractedChemical` depends on whether `DSSToxSubstance` might be related to other types of extracted records. It might be too late to replace the entire `DSSToxSubstance` model by simply adding four new attributes to the `ExtractedChemical`model, but if that approach _would_ work, it provides some guidance as we set up the one-to-one relationship.

**Comment by mwfrost** [comment]
On second thought, I would prefer to do the work under this ticket. Adding the new fields to the data document detail page will be low-effort once we enforce the one-to-one relationship.
