### ISSUE TITLE
implement check for unique filenames when registering records (3 pts)

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#445]
As Dot the Data Collector
I want Factotum to check for duplicate filenames when registering records in a Data Group
So that I do not cause errors when uploading the data documents.

When registering records (by uploading the 'register records csv') I accidentally included a filename twice in the register records.csv file. The record was registered twice, but then an error was thrown when I attempt to upload the matching data documents.

Definition of Done:
- When user is creating a data group and uploading the 'register records.csv' form, application should check that the 'filename' column in the register records.csv does not have any duplicate filenames.
- If there are duplicate filenames in the register records.csv, user should see an error and register records .csv should not be accepted.

Test:

**Comment by Daveahern** [comment]
@kdionisio a point of clarification: when the issue says "does not have any duplicate filenames" is it your intention that the system check only within the register_records.csv file or across all data documents?

**Comment by kdionisio** [comment]
@Daveahern it should only be necessary to check for duplicates within the register_records.csv file. We *know* we have duplicate filenames across data groups already.

**Comment by Daveahern** [comment]
@kdionisio perfect, thank you!
