### ISSUE TITLE
error when uploading extracted text (2 pts)

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#446]
Upon attempting to upload extracted text to a data group of type 'Composition', I encounter the following error:

TypeError at /datagroup/72/
'raw_category' is an invalid keyword argument for this function

I have included a column titled 'raw_category' in the extracted text file I am attempting to upload; note the template I downloaded included the 'raw_category' column as well.

**Comment by kdionisio** [comment]
Includes the extracted text file for upload which is causing the problem, also includes the register records file if needed.
[Home Depot MSDS Extract.zip](https://github.com/HumanExposure/factotum/files/2446726/Home.Depot.MSDS.Extract.zip)

See @mwfrost note in slack on 10/4/2018 10:31 am

**Comment by debboutr** [comment]
couple things I've found so far, we have been returning the `get_abstract_filename` into the `data_document_filename` in the template which I've fixed locally. Also, the `unit_type` was designed to come in as an integer value of the pk for the specific `UnitType` that it is, so the value of "weight fraction" in that column that you have attached won't work as we have designed it. The code we have also goes under the assumption that there will be a value in that column so if it is left blank `""` it will error as well.

> WOW! these 5300 extracted text records take a long time to load! YIKES

I was just able to upload the csv once I changed the `unit_type` column to the integer 1 to represent a UnitType pk.

One thing that may be cause for concern here is the encoding in the CSV that you have attached. When I loaded it, I had to specify [`encoding = "ISO-8859-1"`](https://en.wikipedia.org/wiki/ISO/IEC_8859-1). 

So it'd be good to know how you wrote out the csv initially to reproduce the error. I can't be certain that this is the root of the problem, but for now is probably the best place to look.

**Comment by debboutr** [comment]
@kdionisio can you try loading with this file, all data is the same, so it should fail on `unit_type` now. Does it make sense to make that field non-nullable and just use `Unidentified` where it is null or would that fall under another category? Anyway, all I did was read the file in using the encoding code above and then write it out again, so this will tell us a little more. the error is popping up on the first line w/ `data_document_id` of `267816` which in excel comes in as row 103. Let me know how this works out, this is how I was able to get the upload to succeed..._along w/ switching `unit_type` to integers_


[error_check.zip](https://github.com/HumanExposure/factotum/files/2479992/error_check.zip)

**Comment by kdionisio** [comment]
Issue resolved, unit_type was not coded properly in the extracted text upload file. Therefore there are no code changes which need to be made related to this ticket, thus no associated pull request is needed.
