### ISSUE TITLE
investigate scraping of Home Depot data (5 pts)

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#447]
As Kathie the Product Owner
I want to investigate how to obtain public data from the Home Depot website
So that I can expand the scope of my product related data to include more home improvement and building material products.

Investigate potential to systematically scrape the Home Depot website for product data (including product related fields such as product name, manufacturer, size, UPC, description, image, etc., in addition to any SDS/MSDS that may be linked to the product), including the potential for an automated script that constantly checks the website for updates. Possibilities include scraping data and dumping into a 'staging' database from which we could populate Factotum, or pushing data directly into Factotum. (Note Dave L. has implemented something similar for the Walmart website so may be able to lend insight).

As an example, see the following page:
https://www.homedepot.com/p/Rust-Oleum-Specialty-29-oz-Countertop-Coating-Tint-Base-246068/202820906

A number of pieces of information could be scraped from this web page to fill in the product model. The pdf SDS is also linked from this page, which could be downloaded.

Definition of Done:
Rough proposal for how to implement this related to Factotum.

**Comment by debboutr** [comment]
[**here is a link to the script that I've written to scrape HOME DEPOT**](https://gist.github.com/debboutr/3073a23b734fa05374dd9357f13acfc1)

**Comment by debboutr** [comment]
the script above gathers ~600,000 separate product URLs from Home Depot, the next step will be to call each of those and gather data about each one.
