### ISSUE TITLE
QA - Creation of text extraction QA check page (13 Points)

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#45]
**Issue dependent on completion of #44** 

As Karyn the Curator
I want to check the extracted text data for a data document against the 'raw' data (e.g., the .pdf MSDS)
So that I can check to make sure the extraction script worked correctly

[QA Check page mockup](https://balsamiq.cloud/sadlf/psb72/r0EF1)

When Karyn selects the 'Begin QA' or 'Continue QA' button (buttons created in #35) she should immediately enter into the QA process for the appropriate QA group (QA group created in #44).

Karyn will be cycling individually, and manually, through each of the data documents within the QA group. Within the factotum application, Karyn should see the extracted text data that was uploaded for the data document in the QA group ('extracted text' is defined as the fields listed in #32). This extracted text does NOT need to be editable, just viewable. A separate window should appear displaying the associated data document itself (i.e., displaying the .pdf file), so that Karyn can visually inspect the .pdf file and compare against the extracted text data.

On the QA check page, in addition to seeing the extracted text data associated with a data document, there should be an 'Exit' button and a 'Skip' button.

The Exit button should exit Karyn out of the QA process and return her to the QA home page.

The Skip button should bring Karyn to the next document in the QA group that has not yet been approved (i.e., the next document awaiting approval). If all documents in the QA group have been approved, Karyn should see a message 'Congratulations, QA complete!" instead of seeing another document. At this point the only button enabled will be the 'Exit' button.

On the QA check page, the user should see the status of their progress of QA within that QA group (i.e., 'X documents approved, Y documents remaining').

**Notes: Fields being viewed should be coming from the extractedtext and extractedchemical models. When we refer to 'Product' or 'Product name' for this ticket, we are referring to the 'title' field from the extractedtext data model.

Also note that #46 will follow completion of this ticket, see #46 to see where we are headed!

**Definition of Done**
QA check page exists, and will include:
- Visual representation of extracted text data
- Appearance of additional window displaying the associated .pdf data document
- Progress of approval for QA group (# documents with completed QA vs. # 'to do')
- 'Exit' button
- 'Skip' button

**Comment by mwfrost** [comment]
From the ticket:

> The Skip button should bring Karyn to the next document in the QA group that has not yet been approved (i.e., the next document awaiting approval). If all documents in the QA group have been approved, Karyn should see a message 'Congratulations, QA complete!" instead of seeing another document. At this point the only button enabled will be the 'Exit' button.

Is there a particular order for cycling through the documents? If not, it will default to the ID number.

**Comment by kdionisio** [comment]
There is no particular order for cycling through the documents so using the ID to order them is fine!
