### ISSUE TITLE
no ability to input H&P data (1,000,000 pts)

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#462]
Functionality implemented in #300 to input Habits & Practices data has disappeared. I believe on this page: http://factotum.epa.gov/datagroup/61/ there used to be a button allowing a user to input H&P data related to a data document. That option is now gone.

Note the above functionality is *only* applicable when group type is 'Habits and practices'

**Comment by debboutr** [comment]
[problem!](https://github.com/HumanExposure/factotum/commit/05cda8969c65fa4090f1c8877efd74f0bd788277#commitcomment-30921776)
