### ISSUE TITLE
Bulk assign products to PUCs (13 pts)

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#476]
**Do #481 first**

As Karyn the curator, 
I want the ability to bulk assign products to PUCs from search results
So that I can quickly assign PUCs  to products.

Through the new data curation nav bar link (created in #475), a user will have the ability to enter a process for 'Bulk assigning products to PUCs.' On the bulk assign products to PUCs page, the user will be able to do a search. The search will return *only* products (no data documents) that have not yet had a PUC assigned, and will display product title, brand name in a tabular form.

Definition of Done
1. 'Bulk assign products to PUCs' is an option accessible from the Data curation nav bar drop down (data curation nav bar drop down created in #475 )
2. Search returns only products (no data documents) that have not yet had a PUC assigned
3. Search displays product title and brand name in a tabular form, where product title is a link to the product page
4. Search results allow user to select (e.g. tick box) multiple products and assign all products selected to the same PUC
5. When user batch assigns a PUC to products, the relevant fields in the producttopuc model must be populated for each product
  -created_at/updated_at
  -classification_method (MB for manual batch, see #481 )
  -puc_assigned_usr_id (currently logged in user)
6. search results return max of 50 results

**Comment by zachmunzenrider** [comment]
Team agrees that elacticsearch is the way to go
