### ISSUE TITLE
error when attempting to download all PDF documents

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#479]
The 'download all PDF documents' button on the data group page (http://factotum.epa.gov/datagroup/50/) is not working.

Error is: [Errno 2] No such file or directory: 'no_path_found'

**Comment by debboutr** [comment]
If DataGroup's were renamed to use the UUID, the name of the zip file likely wasn't renamed as well which would mean we would have the UUID for the folder name and then the slug name for the zip filename. We don't currently look for this when creating the path to it
