### ISSUE TITLE
add classification_method options to producttopuc model(2 pts)

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#481]
In the producttopuc model, there exists a field called 'classification_method.' Currently the options available for this field are MA for manual assignment and AU for automated assignment. Please add an option RU for  rule based assignment and MB for manual batch assignment.

Hierarchy of preference for uber PUC, if multiple PUCs are assigned to a product:
1. MA
2. MB
3. RU
4. AU

Definition of Done: Options RU and MB exist for classification_method in producttopuc model

No test needed.

**Comment by debboutr** [comment]
More might need to be added to the **`Product`** method **`get_uber_product_to_puc`** for functionality to be complete, but I put in  a [PR](https://github.com/HumanExposure/factotum/pull/501#issue-225204616)
