### ISSUE TITLE
display curated chemical information on data document page

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#483]
On the Data document view page (http://factotum.epa.gov/datadocument/254864/), the user can currently view the extracted chemical information. User would also like to view the associated curated chemical information.

Definition of Done:
On the data document view page, user sees the following fields from the dsstoxsubstance model alongside the appropriate entry for extracted chemical
  - true_cas
  - true_chemname
  - sid

**Comment by debboutr** [comment]
this is a duplicate of #444
