### ISSUE TITLE
records registered even with error

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#489]
When registering records in a new data group (from here http://factotum.epa.gov/datasource/38/datagroup_new/), if there is an error shown when attempting to upload the register records csv (e.g., incorrect column header), the records are still registered, and the data group is still created. 

Definition of Done:
When a user sees an error when registering records, the data group should not be created and the records should not be registered.

**Comment by debboutr** [comment]
@kdionisio is there a chance that you tried to register, got an error, then fixed the csv and just hit refresh??

_this is a situation where i could think that this could happen, the error might have remained in the context on a refresh_

**Comment by kdionisio** [comment]
clsing issue because it is  being taken care of in #659
