### ISSUE TITLE
clean up white space in raw cas/raw chem name

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#526]
Currently, there exist entries in the raw cas/raw chem name fields (dashboard_rawchem model) where white space exists before and after the value in the field (leading and trailing white space).

Definition of Done:
1. For all existing data in the raw_cas and raw_chem_name fields remove leading and trailing white spaces
2. When new extracted data is uploaded leading and trailing white spaces should be removed before the raw_cas and raw_chem_name fields are populated

**Comment by debboutr** [comment]
make empty migration for `.strip()` ing these fields
