### ISSUE TITLE
refinements to qa check page

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#529]
On QA check page (http://factotum.epa.gov/qa/extractedtext/155284/), the 'extracted text info' box is always editable, but edits in this box can only be saved when the 'edit composition records' button is 'on' (so it is irrelevant to be able to edit the fields when edit composition records button is 'off')

Also, in the header box, the Document Type is not able to be modified

Definition of Done:
- Make 'extracted text info' box only editable when 'edit composition records' button is on (this is same functionality as the 'extracted chemical' info, which is only editable when 'edit composition records' button is on.
- 'Save edits' button should only be visible/enabled when the 'edit composition records' button is 'on'
- In the header box, allow user to change the Document Type (however only document types allowed are those which are children of the data group type to which the document belongs)

**Comment by mwfrost** [comment]
An idea for this page, inspired by Rick's work on the data document detail page: 

What if each editable form were made modal? So rather than clicking the button that toggles editing off and on and then going from form to form, then saving edits and seeing what failed to validate, you instead clicked a button that opened a modal form specific to the UI element that you clicked?

**Comment by mwfrost** [comment]
@kdionisio This page has never supported the ability to edit the data document record, so I have to do some up-front planning about how to integrate this new functionality.
Is it okay if the extracted data editing remains separate from the data document editing? I would prefer to channel the data document edits into their own popup form that ask the user to either save or commit before returning to the QA page. Validating the data document edits alongside all the potential extracted data edits would get complicated.

**Comment by kdionisio** [comment]
@mwfrost hmmm ok...and yes I agree with you that to be cleaner in terms of separating true QA (i.e. fields that *need* to be QAed) from just 'edits we are doing during the QA process because it is convenient' it would be good to separate these two things. I am fine with  your proposal of channeling data doc edits into their own pop-up form or similar.

**Comment by mwfrost** [comment]
@kdionisio As with the DataDocument edits, would it also be acceptable to separate edits to the ExtractedText parent object from the edits to the child records?

For example, if a user is performing QA on a set of CPCat list presence records, there would be one button to click that opens the CPCat attributes up for editing (Doc date, Cat Code, Description CPCat, CPCat SourceType), but editing the child records would use the current combination of buttons to make multiple changes and save them.

**Comment by kdionisio** [comment]
@mwfrost Yes that would be fine!

**Comment by mwfrost** [comment]
New requirement:
All form fields should be displayed in a certain order, to be specified by @kdionisio 

Details of how to sort fields:
https://stackoverflow.com/a/34502078/197321

**Comment by kdionisio** [comment]
Desired order of fields on QA page:
- Raw chemical name
- Raw CAS
- Raw minimum composition
- Raw central composition
- Raw maximum composition
- Unit type
- Reported functional use
- Ingredient rank
