### ISSUE TITLE
populate title field when bulk creating products

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#530]
When user uses the 'bulk create products' button on the data group page (http://factotum.epa.gov/datagroup/72/), currently the 'title' field in the 'product' model is populated as 'unknown'

Definition of Done:
- When 'bulk create products' button is used, 'title' field in the 'product' model should be populated with the 'prod_name' field from the extractedtext model, IF that field is not null. If prod_name is null, then the 'title' field in the 'product' model should be populated with the 'title' field from the 'datadocument' model
- if prod_name is null and product.title is populated with datadocument.title, add a code in to the value of product.title to identify that the product.title field was populated in bulk (add 'stub' at end of title or something)

**Comment by debboutr** [comment]
line 146 from `views/datagroup.py`
```
        for doc in docs_needing_products:
            product = Product.objects.create(
                                    title='unknown',
                                    upc=f'stub_{stub}',
                                    data_source_id=doc.data_group.data_source_id
                                    )
```
