### ISSUE TITLE
limits on when extraction script appears for QA (2 pts)

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#534]
Currently on the QA summary page (http://factotum.epa.gov/qa/), all scripts of type 'EX' (i.e., extraction scripts) are listed, regardless of whether they actually have extracted text associated with them. 

Definition of Done:
Extraction scripts should only be listed on the QA page (i.e., should only be eligible for QA) when there is extracted text associated with the extraction script.

**Comment by mwfrost** [comment]
The seed data includes several data groups with the "Unidentified" group_type. Please change these to "Composition"

**Comment by kdionisio** [comment]
not going to implement this
