### ISSUE TITLE
delete extracted chemical record malfunctioning (5 pts)

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#537]
On the QA page for a data document's extracted text, there is a tick box to 'delete' an extracted chemical record. When the tick boxes are selected and the user hits 'save' nothing appears to happen on the screen (the chemical records are still present). However if the user exits out of the process and returns to the same QA check page, the records are then gone.

Definition of Done:
If 'delete' box is ticked on QA page (http://factotum.epa.gov/qa/extractedtext/155219/), then upon hitting save button those chemical records with 'delete' ticked should disappear from the display

**Comment by mwfrost** [comment]
I reproduced this on my dev environment.
