### ISSUE TITLE
lock down data group type (3 pts)

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#538]
After registering records, data group type should be locked down and should never be allowed to be changed by the user. If data group type is changed the system will break, because of other dependencies on data group type.

Definition of Done:
Data group type is non-editable once records are registered in the data group.

**Comment by debboutr** [comment]
would this include the admin interface as well? so you would never have the ability to edit GroupType after the `datasource/<int:pk>/datagroup_new/` view?

**Comment by kdionisio** [comment]
@debboutr yes, I think it needs to be true that even through the admin interface we have group type locked down....we have too many subsequent data models and workflows which are dependent on data group type so I think if we allow for data group type to change we'll cause all sorts of problems with existing data
