### ISSUE TITLE
unit type null when no composition data

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#539]
Currently, unit_type is a required field when uploading extracted text data for data group type composition. However, this results in records where unit_type is populated but raw_min_comp, raw_max_comp, and raw_central_comp are all null.

Definition of Done:
- unit_type should only be a required field when raw_min_comp, raw_max_comp, or raw_central_comp is populated
- if all three above named fields are null, then unit_type should be null

**Comment by mwfrost** [comment]
@kdionisio We have the "Unknown" unit type. Is that a separate thing from this absence of a unit type because there is no composition data? Or should the unit type be assigned as "Unknown" when a record is imported with no raw_min_comp, etc.?

**Comment by kdionisio** [comment]
@mwfrost You are correct. Unit type should be null if raw_min_comp, raw_max_comp, and raw_central comp are ALL null. Unit type would be required/populated (either with 'unknown' or with another value) if one of the three comp fields is populated. Thus if one of the three comp fields are populated, user should be required to enter a unit type, but one of their options for unit type is 'unknown'
