### ISSUE TITLE
Enforce unique ProductToPUC relationships (3 pts)

### ISSUE THREAD

**Issue by zachmunzenrider** [HumanExposure/factotum#541]
Create a more robust and well defined constraint on the ProductToPUC relationships

Limit to one PUC assignment per product for 'manual' type of PUC assignment

**Comment by kdionisio** [comment]
@zachmunzenrider how does this relate to the ticket #614 you are currently working on? They appear to be overlapping pieces of work?

**Comment by zachmunzenrider** [comment]
I had quite forgotten about this! Yes, this does seem to overlap with the changes I made to this newer ticket.

Are you ok with saying, for now at least, that there should be no more than one PUC assignment per product for any single classification method? That's what I'm implementing in 614. We can refine it later if we find it doesn't cover all situations.

**Comment by kdionisio** [comment]
@zachmunzenrider Yes, I think that's how it should be, for now at least.

**Comment by kdionisio** [comment]
closing because this is being covered in #614 currently being completed in Grasshopper sprint
