### ISSUE TITLE
WF type null when composition fields are null

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#545]
When uploading extracted text, the user is required to select weight fraction type (e.g. reported vs. predicted) from a drop down prior to uploading the extracted text.

Definition of Done:
Weight fraction type field is only populated for records where at least one of raw_min_comp, raw_max_comp, or raw_central_comp is not null. When all three composition fields are null, weight fraction type field should be null.

**Comment by mwfrost** [comment]
The ticket that created the `wf_type` field specified "Reported" as the default value. Should that be applied in cases where it's missing?
