### ISSUE TITLE
add extracted text for individual data document (8 pts)

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#546]
If extracted text does not exist on a data document page (http://factotum.epa.gov/datadocument/268991/), currently the user sees the message 'Extracted text doesn't exist' in the 'Extracted Text' box.

Definition of Done:
If extracted text does not exist, user should have ability to manually enter extracted text. This would occur via
- Button 'Enter Extracted Text' would be visible in the 'Extracted Text' box on the data document page, if no extracted text exists for that data document
- Pressing button would create a new 'extracted text' record
- User would be brought to this page http://factotum.epa.gov/qa/extractedtext/ where they would be able to enter the extracted text data associated with that data document (prod_name, rev_num, doc_date). qa_checked and qa_edited fields should default to 0, and created_at and updated_at fields should be populated. User should be required to select an extraction script from a drop down (same functionality as exists when user uploads and extracted text csv on a data group page and is required to select an extraction script from a drop down).
- User would also have ability to enter extractedchemical data (if data group type is composition). OK if user needs to save above extractedtext data, and then enter extractedchemical data in a second step. extractedchemical data user can enter should be same as what you see on the qa/extractedtext page (i.e. raw_cas, raw_chem_name, raw_min_comp, raw_max_comp, unit_type_id, report_funcuse, ingredient_rank, raw_central_comp, weight_fraction_type_id)

**Comment by mwfrost** [comment]
Would this involve uploading a csv file, or manually entering data?

**Comment by kdionisio** [comment]
re. Matt's comment above, I am thinking manually entering the data (e.g. via web form) since this is to allow for entering one-off documents when you come across a document which is not yet extracted.

**Comment by kdionisio** [comment]
May need to rewrite/close this after #694 and #677 are completed

**Comment by kdionisio** [comment]
rewritten as #757 and replaced by that ticket due to changes made since this ticket was originally written
