### ISSUE TITLE
remove data group type code from DD page

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#552]
As the product owner, 
I would like to remove the data group type code from the data document page header
Because the application user does not need to know the data group type code, and this is taking up real estate on the page.

Definition of Done:
- data group type code field does not exist on data document page

**Comment by mwfrost** [comment]
Change the displayed Data Group Type to be a single field with a title-code combination, like "Composition (CO)"

**Comment by kdionisio** [comment]
will be taken care of as part of #879, full scale data doc page redesign
