### ISSUE TITLE
load in SIDs

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#558]
As a factotum chemical curator
I want the ability to load in a curated list of chemicals
so that I can populate the RID, SID, true cas, true chem name fields in the associated chemical models in bulk

In #252 we implemented the ability for the chemical curator to download a list of raw chem records that do not yet have an SID assigned.

Definition of Done:
1. Ability for chemical curator to upload a csv of curated raw chem records for storage in factotum. File being uploaded would populate the following models/fields:
- external ID identifying the raw chemical record in question (as provided in the download from #252) (raw chemical ID)
- RID (raw chemical RID)
- SID (DSSToxLookup sid)
- true chemical name (DSSToxLookup true_cas)
- true CAS (DSSToxLookup true_chemname)   
  
2. If the SID does not already exist, create a new record in DSSToxLookup for that SID
3. If the SID already exists in DSSToxLookup, overwrite the existing true CAS/true chemname for the existing record with the true CAS/true chemname in the new .csv upload
4. If an RID already exists for the raw cas/raw chem name pair, overwrite the existing RID with the RID in the new .csv upload
5. once the DSSToxLookup record is created link back to RawChem.dsstox

**Comment by mwfrost** [comment]
Other potential conflicts: 

What happens when an uploaded SID is already in the DSSToxLookup table but the existing True Chem Name or True CAS doesn't match what's being uploaded?
