### ISSUE TITLE
Underscore in CharField indexes is not treated as a literal

### ISSUE THREAD

**Issue by mwfrost** [HumanExposure/factotum#559]
A search for "stub_207" does not prioritize the record with that exact UPC value. Instead, it returns over 1800 evenly-scored results, based on the "stub" search string. Changing the product's UPC to "stub-207" and then searching for that string works properly. 

Haystack must be using the underscore as a special character in its query. Rather than resolving this bug, it could be used as a test case for a future haystack-free search implementation.

**Comment by kdionisio** [comment]
to be addressed when change is made to elastic search
