### ISSUE TITLE
edits to bubble plot (8 pts)

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#568]
In the d3 bubble plot of Products linked to PUCs on the Dashboard page (http://factotum.epa.gov/), the number of products represented should be carried up to the higher levels of the  hierarchy.

Definition of Done:
1. Please add a basic legend next to/above/below the plot. Legend should represent the color associated with each Level 1 PUC (so legend will only include the level 1 PUCs, i.e., ~10-12 entries on the legend).
2. Bubbles representing Level 1 and Level 2 PUCs should include the number of products in any more refined PUCs. e.g., the Level 1 PUC for personal care products should include the number of products directly assigned to Personal care products + # products assigned to personal care products -  hair styling + # products assigned to personal care products - hair styling - hair color + # products assigned to personal  care products - hair styling - awesome hair styling products etc etc

**Comment by debboutr** [comment]
@kdionisio I'm guessing this would also change the ouptut that we have in the CSV download for PUCs on the get data page? I'd imagine we also want to have the `num_prods` field output the numbers that are associated in the hierarchy like mentioned in #2 above?
