### ISSUE TITLE
More than one QA group causing error

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#579]
When hitting the 'Continue QA' button (http://factotum.epa.gov/qa/) for the Walmarts MSDS (Extract) extraction script QA group, following error was seen:

MultipleObjectsReturned at /qa/extractionscript/12/
get() returned more than one QAGroup -- it returned 4!

This occurred when a student was working on QA for this QA group, then accidentally closed a window. Upon attempting to reenter QA for this group, this was the message seen.

**Note error is also happening with the Home Depot extraction script.

**Updated to note - I checked the prod DB and confirmed that for these two extraction scripts there are multiple QA groups associated with each one. There should only be one QA group associated with each extraction script. Are we able to figure out why/how there were multiple QA groups created for a single extraction script, so that we can prevent this from happening again? Also, what is the best way to resolve this while not corrupting the DB? Note that the two scripts where we have this issue do not have any QA completed so if we wipe the QA group (for those two scripts only) and start over that is OK.

**Comment by mwfrost** [comment]
These SQL commands should assign all the extracted text records within each set of duplicates to a single QA Group:

`UPDATE dashboard_extractedtext SET qa_group_id = 4 WHERE qa_group_id IN (SELECT id from dashboard_qagroup WHERE extraction_script_id = 12);`

`UPDATE dashboard_extractedtext SET qa_group_id = 2 WHERE qa_group_id IN (SELECT id from dashboard_qagroup WHERE extraction_script_id = 9);`

Then the extra QA Groups can be deleted:

`DELETE FROM dashboard_qagroup  WHERE extraction_script_id = 12 AND id <> 4;`

`DELETE FROM dashboard_qagroup  WHERE extraction_script_id = 9 AND id <> 2;`

**Comment by mwfrost** [comment]
How to reproduce the error in a dev environment:

Find a datadocument/extractedtext record without an associated QA group:
```
SELECT * from dashboard_extractedtext 
where extraction_script_id 
NOT IN (SELECT extraction_script_id from dashboard_qagroup)
AND qa_group_id is null
;
```
Note that both the Script and the DataDocument models have foreign key relationships to the QA Group model. 
Document 156051 is associated with ExtractionScript 6.
Go to that document's detail page:
`http://127.0.0.1:8000/datadocument/156051/`

Click the "QA" button to go to the ExtractedText QA page:
`http://127.0.0.1:8000/datadocument/qa/extractedtext/156051/`

Note that a new QA Group object has been created in the database, but the `qa_begun` attribute for Script 6 has not been set to `True`. So if you open the Script's QA page, the view creates a new, duplicate, QA Group with `extraction_script_id` of 6.

`http://127.0.0.1:8000/qa/extractionscript/6/`

**Comment by mwfrost** [comment]
Proposed solution, per Slack conversation:

Move this code into its own `create_qa_group()` function:

```
    qa_group = QAGroup.objects.create(extraction_script=es)
    
    if len(doc_text_ids) < 100:
        texts = ExtractedText.objects.filter(pk__in=doc_text_ids)
    else:
        random_20 = math.ceil(len(doc_text_ids)/5)
        shuffle(doc_text_ids)  # this is used to make random selection of texts
        texts = ExtractedText.objects.filter(pk__in=doc_text_ids[:random_20])
    for text in texts:
        text.qa_group = qa_group
        text.save()
    es.qa_begun = True
    es.save()
```

The `create_qa_group()` function should accept two variables: a required Script and an optional DataDocument/ExtractedText ID. If the ExtractedText ID is passed to the function, the function must check to see if that record is among the randomly selected ones in the new QA group. If not, it must be appended.

**Comment by mwfrost** [comment]
When we compose tests for this new functionality, please include each of the following scenarios:

- Clicking "QA" on a data doc with an already-existing QA Group
- Clicking "QA" on a data doc with no existing QA Group

Things to test for: 
- as soon as a QA Group has been created from a data document detail page, its entry in `/qa/` should use a "Continue QA" button rather than a "Begin QA" button.

**Comment by mwfrost** [comment]
What should happen when a user clicks "Begin QA" on an Extraction Script with zero ExtractedText records? Should the button be disabled?

**Comment by debboutr** [comment]
this is a good question, I'd think it would be good to disable the button if not all datadocuments have been extracted, but the Script would have to look in all assoc'd DataGroups docs, something like this
```
all([d.extracted for g in script.datagroup_set.all() for d in g.datadocument_set.all()]) 
```
maybe we don't even list `scripts` who haven't had all their groups extracted in the table??

**Comment by dmlyons2** [comment]
> 
> Then the extra QA Groups can be deleted:
> 
> `DELETE FROM dashboard_qagroup WHERE extraction_script_id = 12 AND id <> 4;`
> 
> `DELETE FROM dashboard_qagroup WHERE extraction_script_id = 9 AND id <> 2;`

Ran the two DELETE queries per @kdionisio message on slack. 3 rows affected on query 1 and 2 rows on query 2.
