### ISSUE TITLE
add model properties for BooleanFields where possible

### ISSUE THREAD

**Issue by debboutr** [HumanExposure/factotum#597]
add `@property` to DataDocument model for the `extracted` attribute and similarly to the Script model for the `qa_begun` attribute. 

This will prevent these attrs from being out-of -sync in the DB as well as the seed data.

The boolean fields that we have in the models are:
```
dashboard/models/extracted_text.py:18:    qa_checked = models.BooleanField(default=False, verbose_name="QA approved")
dashboard/models/extracted_text.py:19:    qa_edited = models.BooleanField(default=False, verbose_name="QA edited")
dashboard/models/script.py:27:    qa_begun = models.BooleanField(default=False)
dashboard/models/data_document.py:18:    matched = models.BooleanField(default=False)
dashboard/models/data_document.py:19:    extracted = models.BooleanField(default=False)
dashboard/models/qa_group.py:14:    qa_complete = models.BooleanField(default=False)
```
If any of these could be moved into a model property, it might be worth considering as well.

**Comment by mwfrost** [comment]
I've opted to only remove the `DataDocument.extracted` field on this ticket. It was the one that caused the most trouble.
