### ISSUE TITLE
apply assumed attributes

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#600]
For certain PUCs, attributes may be 'assumed' to apply to EVERY product assigned to that PUC. e.g., for the lawn fertilizer PUC, we would assume that the 'outdoor' attribute is assigned to every product within that PUC.

Definition of Done:
1. Way for product owner to assign 'assumed' attributes for a PUC. An assumed attribute will be one or more of the 'associated/allowed' attributes for the PUC. 
2. The assumed attribute will automatically be assigned to every product assigned to that PUC (both for existing data, and for new data).
3. Within the application (e.g. on a given product page), a user should not be allowed to 'de-select' any assumed attribute for a given product.

**Comment by debboutr** [comment]
if there is an attribute assigned to a PUC and we consider that attribute to be `assumed`, meaning it would be automatically assigned w/ a Product and also not able to be unassigned to that Product. Will you ever want that given attribute to be linked to another PUC, but not be assumed? _hope this makes sense_
`a_puc` -> tag('outdoor') -- assumed=True
`another_puc` -> tag('outdoor') -- assumed=False

**Comment by kdionisio** [comment]
@debboutr This situation is absolutely going to happen!

lawn fertilizer PUC --> tag('outdoor') -- assumed = True
paint PUC --> tag('outdoor') -- assumed = False, BUT allowed = True (i.e. outdoor is an 'allowed' attribute for the paint PUC, which a user can select for a given product if it applies)
