### ISSUE TITLE
dynamically view number of products assigned to a PUC

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#601]
As a data curator
I want to easily, dynamically view the number of products assigned to a PUC
So that I can track my progress as I complete product categorization, and so that I can see which PUCs still need products assigned.

Definition of Done:
Easy way to quickly, repeatedly reference up-to-date numbers of products assigned to PUCs

**Comment by mwfrost** [comment]
@kdionisio Kathie, would it work if the product count appears as a new column in the table here?
`factotum.epa.gov/admin/dashboard/puc/`

**Comment by kdionisio** [comment]
@mwfrost unfortunately no...only admins are able to access that admin panel, and it is really the students (non-admins) who need this info.

**Comment by mwfrost** [comment]
Confirmed with @kdionisio that this ticket entails the creation of a new view to display PUCs
