### ISSUE TITLE
Update ProductToPuc classifications and constraint

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#614]
Enforce uniqueness on ProductToPuc product/puc/classifiation_method

Also write test for ticket #603, ensuring that bulk-applied ProductToPuc relationships get categorized as MB, not MA

Note that the test_bulk_product_puc_post test will result in 2 records, one with MA and one with MB. That's apparently OK, as long as MB is getting properly applied for the bulk action

**Comment by zachmunzenrider** [comment]
Zach [2:53 PM]
@Kathie I discovered that our ProductToPuc model is allowing multiple records of the same Product/PUC combination. I'm applying a fix to it now but would like a little guidance: First, is it ever okay to have duplicates, if they have different classification methods? Secondly, while we prevent this from happening in the UI now, it's possible to bypass the UI through the admin console, etc. Would you like for this to fail silently or cause an error?

Kathie [2:56 PM]
This may need a short discussion to be sure we are covering the basis, but a few quick responses for now
A product can have multiple PUCs assigned IF each PUC was assigned with a different classification method

Zach [2:59 PM]
OK, the situation I found, 2 records with the same Product/PUC combination but different classification methods (MA and MB, in this case) isn't necessarily a problem, as long as we are aware of this possibility in the UI and handle it

Kathie [3:00 PM]
Yes we actually need this to be the case
