### ISSUE TITLE
DataGroup get_zip_url method not finding zip file

### ISSUE THREAD

**Issue by debboutr** [HumanExposure/factotum#617]
we're getting an error when trying to download all pdf documents at `http://factotum.epa.gov/datagroup/50/`

 this is a tough one to detail w/o being able to see the file structure. There are also a lot of moving parts to this based on the fact that we are trying to manage the DataGroup folder being labelled w/ a UUID or the old method which was to slugify the title by adding `_` where there were spaces. We also have a Charfield in the `zip_file` attribute of the DataGroup, which should maybe be what we use to access this files location? else, if we are going to just use the `fs_id` to name, keeping this attr could just be redundant.

**Comment by mwfrost** [comment]
This is covered in issue #479
