### ISSUE TITLE
PUC tags/attributes not required

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#618]
As the product owner
I want the ability to store PUCs that are not associated with any attributes/tags
So that I can accurately store all product categories

In the admin panel, it is required to select at least one 'PUC Tag' for each PUC. However, a PUC may be associated with 0 PUC Tags. 

Definition of Done:
- a PUC should *not* be required to have an associated PUC Tag

**Comment by debboutr** [comment]
this is not currently on production, but is fixed in `inchworm`'s branch, so can be closed.
