### ISSUE TITLE
search for data document by raw chemical record ID

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#621]
As Brian the chemical curator
I would like to see information about the data document where a raw chemical record was pulled from
So that I can better deduce the chemical that the ingredient name is actually referring to

Definition of Done:
1. Ability to search by raw chemical record ID; user also needs ability to indicate whether id is from the dashboard_extractedchemical table, the dashboard_extractedlistpresence table or from the dashboard_extractedfunctionaluse table
2. Search should return the data document page which the raw chemical record is associated with (for any given extractedchemical or extractedfunctionaluse record there should be only one associated data document)
3. Option to 'Look up raw chemical record' can be another option in the 'Data curation' nav bar link

**Comment by mwfrost** [comment]
The ticket includes this requirement:
>  user also needs ability to indicate whether id is from the dashboard_extractedchemical table, the dashboard_extractedlistpresence table or from the dashboard_extractedfunctionaluse table

Does this still apply, now that all three of those types of data have become subclasses of RawChem? Would the same RID appear across the three subclasses of RawChem data?

**Comment by kdionisio** [comment]
no longer needed
