### ISSUE TITLE
Refactor Extracted... Models to Share "Raw Chemical" Attributes

### ISSUE THREAD

**Issue by mwfrost** [HumanExposure/factotum#626]
All the models that currently include `raw_chem_name` and `raw_cas` should inherit those properties from a new abstract base class called `RawChemical`. The models that will share this inheritance currently include `ExtractedFunctionalUse`, `ExtractedChemical`, and `ExtractedListPresence`. The new abstract class will manage the association between these raw chemical attributes and their "curated" records in the `DSSToxSubstance` model.

## Definition of Done

- `ExtractedFunctionalUse`, `ExtractedChemical`, and `ExtractedListPresence` no longer store the raw extracted chemical attributes in their models. 
- All the curated `DSSToxSubstance` records can be queried together via the new abstract base class.

## What is the test(s)
A method that creates a new link between an `ExtractedFunctionalUse`, `ExtractedChemical`, or `ExtractedListPresence` object and a DSSToxSubstance record should accept as its input an object of any of the three `Extracted...` classes.

**Comment by mwfrost** [comment]
I think if these raw chemical models are going to inherit the `raw_chem_name` and `raw_cas` fields from the new `RawChem` base class, there should be one `RawChem` record that corresponds to not-curated chemicals. The equivalent of leaving the current fields null.

**Comment by kdionisio** [comment]
@mwfrost Let me know if this doesn't make sense!! I can also do a quick CompTox Chemical Dashboard tutorial if that would be helpful (that's where much of this originates from). Thank you!!

Notes for implementation:
- Every extracted chemical record (i.e., every record of raw cas/raw chem name) will be assigned a unique RID (note that *we* can not mint RIDs, those are only going to be given to us at a later date by colleagues). Raw cas/raw chem name pairs will not be unique in our data, however raw cas/raw chem name/RID triplicates *must* be unique (every raw chem name/raw cas *record* is assigned it's own RID)

- Every RID gets mapped to an SID. The RID to SID relationship is a many to one relationship. Also, the RID to SID mapping can change!

- The true cas/true chem name/SID triplicate is ALWAYS the same - true cas, true chem name, and SID are *synonyms* for each other. So we really could just be storing the SID and not storing the true cas/true chem name, but this would then require all users to refer to the chemical by an SID

**Comment by mwfrost** [comment]
### Implementation and Testing Instructions

`this is a working draft, subject to frequent change`

The steps involved in this change are the following:

Create a new RawChem model to serve as a base class for ExtractedChemical, ExtractedFunctionalUse, and ExtractedListPresence (the "ExtractedX." models here). Add a record with "Undefined" values to serve as the default.

Populate the new model by inserting the raw_cas and raw_chem_name values from any existing ExtractedX records into the newly created table, along with keys to identify each record's original source object and its original primary key. 

Create a new referential link from each of the ExtractedX tables to the RawChem table. This starts as a nullable foreign key, but will later become the non-nullable OneToOneField, or "pointer," that django uses to manage one-to-one relationships. The data migration command populates this field by joining the ExtractedX table's id to the RawChem table's temporary source id field.

Create a new referential link from the DSSToxSubstance model to the RawChem model. The id field will be dropped from each ExtractedX table, so the OneToOneField that links DSSToxSubstance to ExtractedChemical must instead point to the RawChem table's id. As with the ExtractedX tables, this key will initially be a nullable ForeignKey, but will become the non-nullable OneToOneField.

With the RawChem table populated and the new referential links in place, rename the old raw_cas and raw_chem_name fields to raw_cas_old and raw_chem_name_old in all three ExtractedX models. 

#### Testing Steps

- Check out `dev`, delete your schema, then load the seed data:
-- `python manage.py loaddata 00_superuser 01_lookups 02_datasource 03_datagroup 04_PUC 05_product 06_datadocument 07_script 08_extractedtext 09_productdocument 10_extractedchemical 11_dsstoxsubstance 12_habits_and_practices 13_habits_and_practices_to_puc 14_product_to_puc 15_extractedfunctionaluse 16_extractedcpcat 17_extractedlistpresence 18_puc_tag`

Then checkout the `626` branch, and once you're in the branch, specify the pre-migration commit by running `git checkout 00000x`. Migrate to the corresponding migration, which is `00xx_xxxxxxx`.

- Run the data migration script `move_raw_chem_values` to create the new RawChem records, assign ForeignKey links from the ExtractedX models to them, and link the DSSToxRecords to RawChem records.

Checkout the final commit by running `git checkout 00000x` and sync the schema by running `manage.py migrate`

Run the tests and try the interface.

**Comment by mwfrost** [comment]
@debboutr  Model inheritance is implemented through a `OneToOneField` join. The `rawchem_ptr` field starts out as a `ForeignKey`, then a migration converts it to a `OneToOneField`. If you just add a base class to an existing model, django will add a field like `rawchem_ptr` but it won't be able to populate it until you crosswalk everything back from the newly created base class IDs.
