### ISSUE TITLE
Normalize DSSToxSubstance table

### ISSUE THREAD

**Issue by mwfrost** [HumanExposure/factotum#627]
## Create a lookup table of distinct DSSTOX substances

The current `DSSToxSubstance` model links DSSTOX-specific fields to an `ExtractedChemical` record to which a Record ID (RID) has been assigned. The DSSTOX fields currently store duplicating values. Instead of duplicating the storage of every authoritative DSSTOX substance attribute, the table should characterize the many-to-one joins between extracted chemical records (objects that inherit from `RawChem`) and the canonical set of DSSTOX records. The DSSTOX attributes include SID, true_cas, and true_chemname. 

## Definition of Done

The relationship between a "raw" chemical record and its "curated" DSSTOX attributes is mediated by a one-to-many join.

## What is the test(s)

All existing code still functions as before, with the new relational behavior abstracted through methods and properties on the `RawChem` objects

Please include a test that creates *and then indexes* DSSToxSubstance objects that relate to all three types of ExtractedX records. The current search index fails to account for DSSToxSubstance objects that link to ExtractedFunctionalUse, for example. ( See `https://human-exposure.slack.com/archives/C9H1SKA07/p1548801411008400` )

Rick's proposed solution for backwards-compatibility:
```
    @property
    def extracted_chemical(self):
        if hasattr(self.rawchem_ptr,'extracted_chemical'):
            return self.rawchem_ptr.extracted_chemical
        if hasattr(self.rawchem_ptr,'extracted_functionaluse'):
            return self.rawchem_ptr.extracted_functionaluse
        if hasattr(self.rawchem_ptr,'extracted_listpresence'):
            return self.rawchem_ptr.extracted_listpresence
```

**Comment by mwfrost** [comment]
The seed data added to this branch should contain DSSToxSubstance records that match all types of ExtractedWhatever records

**Comment by mwfrost** [comment]
@kdionisio 
These records in the existing 'DSSToxSubstance' table will cause trouble when we try to collapse them into `DSSToxLookup`:
```
DTXSID1020194   10043-35-3  Boric acid
DTXSID1020194   10043-35-3  Boric acid (H3BO3)
DTXSID4020749   4247-02-3   Isobutylparaben
DTXSID4020749   2/3/4247    Isobutylparaben
DTXSID4028460   68391-01-5  Quaternary ammonium compounds, benzyl-C12-18-alkyldimethyl, chlorides
DTXSID4028460   68391-01-5  Benzyl-C12-18-alkyldimethylammonium chlorides
DTXSID6023232   56-87-1 Lysine
DTXSID6023232   56-87-1 L-?Lysine
DTXSID8020676   9000-01-5   Gum arabic
DTXSID8020676   1/5/9000    Gum arabic
DTXSID9023126   71-00-1 Histidine
DTXSID9023126   71-00-1 L-Histidine
DTXSID9023203   61-90-5 Leucine
DTXSID9023203   61-90-5 L-Leucine
```

"2/3/4247    Isobutylparaben" and "1/5/9000    Gum arabic" are obviously cases where Excel's notorious date formatting function ran off the leash. Fixing the CAS for those records should resolve this. The other instances need to have their True Chem Name values standardized.

**Comment by kdionisio** [comment]
@mwfrost 
On the date issue - ARGH. No matter what we do to try to prevent this it still seems to crop up.

For all of the above records, I am actually fine with you just dropping the SID/true cas/true chem name for these records (so deleting the above fields). I would also drop the RID for these records. Then that just means they'll get cycled back through the system as 'raw cas/raw chem names that don't have an SID assigned and need to be curated,' which will force us to reassign these and clean them up.

**Comment by kdionisio** [comment]
correct, that is fine. we'll just resolve the conflicts by removing these SIDs and remapping the raw cas/raw chem
