### ISSUE TITLE
method for grouping PUCs

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#633]
As a product owner, 
I would like a way to group PUCS into larger categories by 'type' of the PUC (e.g., by each PUC having a type code)
So that I can easily separate different types of PUCs for categorization, or for data analysis.

e.g., our current set of PUCs are all for 'formulations of consumer products'; I will soon be loading another set of PUCs that are all related to articles, another set for building materials, and another set all related to products used in occupational settings. I'd like a way to easily distinguish between these 3-5 sets of PUCs.

Definition of Done:
- Ability to assign each PUC, from within the admin panel, into one of 3-5 'types' of PUCs
- PUC types to create: unknown, formulations, articles, occupational
- PUC type is required for each PUC
- newly created PUCs can have a default PUC type of unknown
- existing PUCs with a 'created_at' date prior to Jan 1, 2019 can be assigned to the 'formulations' PUC type
- existing PUCs with a 'created_at' date after Jan 1, 2019 can be assigned to the 'occupational' PUC type

**Comment by debboutr** [comment]
PUC has a many-to-many relationship w/ Product, so would we want to enforce the `type` of PUC that a Product can be linked to? or are any fair game for linking?

**Comment by kdionisio** [comment]
@debboutr this is a good question, but the answer is probably the latter, any are fair game for linking. Mostly because we typically would not know a priori which 'type' of PUC a product would be assigned to (e.g., some products from Walmart and Home Depot would be assigned to a 'formulation' PUC, some would be assigned to a 'building material' PUC). I'm sure there would be some sources where the products are so specific that we would know the type of PUC the products would be assigned to, but typically we would not.

We would more use this for things like data searching or faceting (i.e., give me all products including chemical A that are formulations vs. products including chemical A that are building materials). It will also be used when we subset data out to create the input files for our models (only weight fractions from formulation PUCs need to go into our exposure models, but building material PUC data may be needed for another model).
