### ISSUE TITLE
exit button on qa page gives error

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#636]
The exit button on the QA page (http://factotum.epa.gov/qa/extractedtext/1365100/) for a CO group type is giving a 'Page not found (404)' error. 

Definition of Done:
Exit button on QA page for CO group type returns user to this page http://factotum.epa.gov/qa/extractionscript/

**Comment by mwfrost** [comment]
@kdionisio On `dev`, the Exit button on that page should link to `http://127.0.0.1:8000/qa/compextractionscript/52/`, a URL that uses the new path specified in ticket #1034. 
1034 has not been merged into Production, though, so your setup will still use the old system. I _think_ this will be resolved when dev gets merged in. I loaded the Production data set into dev and it works fine.

**Comment by kdionisio** [comment]
resolved in 1034
