### ISSUE TITLE
restrict data document type codes to be unique

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#637]
When entering a new data document type in the admin panel, user specifies a 2 letter 'code' to reference this data document type.

Application currently allows user to enter a two letter code which is already in use (in dashboard_documenttype.code). This seems to be contradictory to the idea that the code is used to uniquely reference the type of data document!

Definition of Done:
Restrict document type code to be unique.

Note it is unclear to me if document type codes need to be unique across all document types, or just need to be unique within each data group type (currently there do exist duplicate document type codes across data group types,, however they are unique within data group type).

**Comment by mwfrost** [comment]
This has led to a condition where many documents have a `document_type_id` foreign key to a record in `dashboard_documenttype` where the code is correct, but the group_type parent of the document_type record does not match the document's own group type.
```
select dd.id, dd.document_type_id, 
dt.id as dt_pk, dt.code, dt.title, dt.group_type_id as doctype_grouptype_id,
gt.id as actual_group_type_id, gt.code as actual_group_type_code, gt.title
 from dashboard_datadocument dd 
left join dashboard_documenttype dt
on dd.document_type_id = dt.id
left join dashboard_datagroup dg 
on dd.data_group_id = dg.id
left join dashboard_grouptype gt
on dg.group_type_id = gt.id
where dt.group_type_id <> dg.group_type_id
;
```
