### ISSUE TITLE
Change Cleaned Composition Data workflow to match new schema

### ISSUE THREAD

**Issue by mwfrost** [HumanExposure/factotum#640]
Issues #502 and #504 implemented a workflow that involved downloading a raw composition data table and then uploading a cleaned version of it. 

The records in that table use the old `ExtractedChemical.id` primary key. That key has been deprecated in favor of the primary key from the Extracted Chemical's `RawChem` base class instance.

**Comment by kdionisio** [comment]
already taken care of
