### ISSUE TITLE
Remove Ingredient model

### ISSUE THREAD

**Issue by mwfrost** [HumanExposure/factotum#642]
The Ingredient data model is redundant: its attributes can be attached to the ExtractedChemical model.

**Comment by mwfrost** [comment]
All the tests in `dashboard.tests.functional.test_clean_comp_data_upload` will need to be updated.

**Comment by kdionisio** [comment]
@zachmunzenrider  Is this now being incorporated into #1106?

**Comment by althuser** [comment]
Yes! I didn't realize this was already a ticket! I still need to add the promised comment to #1106
