### ISSUE TITLE
Update all SID-driven queries to operate across all Extracted[X] objects

### ISSUE THREAD

**Issue by mwfrost** [HumanExposure/factotum#649]
The changes to the data model made in tickets #626 and #627 moved the SID attribute out of the DSSToxSubstance model, which had previously been related directly to ExtractedChemical model, and into the RawChem model, which ExtractedChemical inherits the SID from. 

Several queries, especially on the `get_data` page, used the SID value as a filter or grouping key for aggregation. Those queries joined DSSToxSubstance to ExtractedChemical, then traversed other relationships, for example:

ExtractedChemical ➡️  ExtractedText ➡️  DataDocument ➡️  Product ➡️  PUC

Ideally, those queries will now be generalized to apply to all the Extracted[X] objects that inherit from the RawChem parent model. In the example above, the ExtractedListPresence model cannot follow the same join path, because each is related to an ExtractedCPCat parent object rather than an ExtractedText object. 

Checklist of objects that should be included in these operations:

*ExtractedText*
- ExtractedChemical
- ExtractedFunctionalUse

*ExtractedCPCat*
- ExtractedListPresence

The ExtractedHabitsAndPractices model is not included here, since it does not inherit from RawChem.

**Comment by kdionisio** [comment]
no longer needed
