### ISSUE TITLE
custom QA group and QA page for data group type CP

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#670]
As the Factotum product owner
I have a need to customize the QA workflow for data documents in data group type CP
So that I can complete QA according to our project QA plan

Definition of Done:
For all data groups of data group type CP, 
- every data document of this data group type will be QA'ed (each data document forms it's own QA group)
- QA group does NOT need to be created for extracted script identified by dashboard_script.id=29
- on the QA page (http://factotum.epa.gov/qa/extractedtext/155284/), a random 10% of the extracted chemical records associated with that data document should be represented, with a max of 30 chemicals represented
- on the QA page (http://factotum.epa.gov/qa/extractedtext/155284/), the raw CAS and the raw chemical name fields are the only fields which need to appear (i.e., the  raw min comp, raw max comp, unity type, ingredient rank, etc etc fields normally represented on this page do not need to appear)

**Comment by debboutr** [comment]
if the DataDocument acts as the QAGroup, when the ExtractedText record is made for the DD it should also instantiate the QAGroup record?

Do we anticipate that CP records will all be extracted by registration through a CSV? Would we potentially add more to a document through the DD detail view?

If we don't consider an extraction script, at what point and on what page would we begin the QA process? If all chem records come in through CSV registration we can create QAGroup upon successful upload, link to QA would be in the DD detail view already, but if not, that's another can of worms...

**Comment by debboutr** [comment]
the way I'm thinking of this being implemented is to add a BooleanField to the `ExtractedListPresence` model and then at the datadocument detail page up in the div w/ the document fields add in a QA button that would either say Begin QA , or, Continue QA. This button would link to a url of it's own that would flag the random (10%/max30) `extractedListPresence` records to True or if the have already been flagged w/ the BooleanField
```
def flag_qa_list_presence(request,pk):
    if not ExtractedListPresence.objects.filter(extracedtext_id=pk, qa_field=True).exists():
        # do the logic to find random 10% or 30 records and set qa_field = True
    return redirect('extracted_text_qa', args=[pk]))
```
Then, the ParentForm would stay the same in the QA view, but the ChilldFormset would have to be given the queryset of children where only the ones w/ the "qa_field" is True. _this field can be better named, but I'm using just to illustrate._

Then the approval updates really all happen in the `ExtractedCPCat` record which inherits `ExtractedText`, so upon approval those fields can be updated.

Upon approving QA w/ this group type the user would be redirected back to the datadocument detail page where they would now see a disabled QA button that would say QA Complete, or the like next to the script, that would be disabled.

there are a lot of other considerations with this ticket, I know. These are the steps that I would start with if I were working on it.  @zachmunzenrider I'd like to hear how you're thinking of tracking the child records through QA

**Comment by debboutr** [comment]
We have been using a script called "Manual (dummy)" thus far in our process to connect ExtractedText records to which identifies that it was created manually, QA will never be performed on this script like it will be for others so we will want to exclude this Script from the queryset that is returned in the `/qa/` view to prevent a QAGroup being created and documents being associated.

for this particular group type `CP` the QA process will be specific to each document and will be initiated from there, not the script.

**Comment by debboutr** [comment]
@kdionisio would you want 10%  of 20 ListPresence records, i.e. 2 random? or are you should we QA all child records until we get to 30 and then start just to randomly pick out 30 from all the child records?

**Comment by kdionisio** [comment]
@debboutr good question. Does the below clarify?

If a document has <=300 child records, then QA a random 10% of the records
If a document has >300 child records, QA a random 30 records

**Comment by debboutr** [comment]
A document has < 300, let's say 100, we would then select 10%. Or 10 of those records? I'm thinking we always want 30 unless there are less than 30 child records, then we would just want all. Otherwise, we just take a random subset of 30 from the total, that being `.all()`

**Comment by kdionisio** [comment]
@debboutr yes, I see your reasoning Rick, and I am fine with this.

To be honest, ultimately the final decision isn't up to us - it's up to what our QA manager will agree to. So essentially I am going to propose to him whatever we implement in Factotum, but there is the possibility we'll have to change this dependent on what he ultimately approves.

**Comment by mwfrost** [comment]
This could be a variable, right? If there is any possibility that the sample size might change, then we need to record with each QA group what its sample count was. In a few years, if you decide to use a 15% sample, you will probably need to know which QA groups were approved under the old 10% regime.

**Comment by kdionisio** [comment]
very good point and idea Matt! But I wonder if that is going beyond the scope of this initial piece of work? Maybe I should ticket that change for the future.

**Comment by mwfrost** [comment]
It's definitely outside the scope of the ticket.

**Comment by mwfrost** [comment]
@kdionisio 

Kathie, 
Rick and Zach and I are thinking ahead to when we build in the Approval steps for the ExtractedCPCat and ExtractedListPresence objects (and similarly for the ExtractedHHDoc and ExtractedHHRec objects). Once you identify the QA sample set inside an ExtractedCPCat document, will each ExtractedListPresence record be individually reviewed and approved? Or will the reviewer look at all the randomly-selected QA records and click Approve for the entire document at once?

**Comment by kdionisio** [comment]
@mwfrost This is  a really good question and perhaps we should discuss briefly. Theoretically we are approving QA for the document as a whole if we look at and approve a subset of the child records associated with that document. However, if we do QA approve the document as a whole, we will then have child records which are noted as 'approved' but may actually be wrong since eyes may not have been laid upon that individual child record. This then messes with our overarching idea that something which has been QA approved must _definitely_ be correct. For that reason, preference is probably to QA approve each individual child record rather than the entire document in these cases, but I'm open to discussion on this and see how doing so might complicate the QA tracking process immensely.

**Comment by mwfrost** [comment]
Thanks, Kathie. Approving ExtractedListPresence records will indeed make the QA process more complicated, but it would maintain procedural symmetry with the QAGroup/ExtractedText process.

**Comment by mwfrost** [comment]
See ticket #597 for some relevant ideas
