### ISSUE TITLE
extracted data for new data group type - model

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#676]
As a Factotum data curator
I have a need to store extracted data for a new data group type
so that I can integrate a new data type into the Factotum application for ease of priority data record identification

New data group type code = HH

For each data document within a data group type of HH, fields that need to be stored are:
Fields that have a 1:1 relationship with data document...
- filename of the data document (already accounted for in data document model?)
- title of the data document (already accounted for in data document model?)
- date of the data document (already accounted for in data document model?)
- HHE report number (madatory, alphanumeric, max 30 characters)
- study location (not mandatory, alphanumeric, max 50 characters)
- NAICs code (not mandatory)
- Date of sampling (not mandatory, max 75 characters)
- population_gender
- population_age
- population_other
- occupation (max 75 characters)
- facility (max 75 characters)

Fields that will have a many:1 relationship with data document....
- raw cas
- raw chemical name
- media (max 30 characters)
- sampling method (open text)
- analytical method (open text)
- num_measure (alphanumeric, max 50 characters)
- num_nondetect (alphanumeric, max 50 characters)

Definition of Done:
Test that will create the model and check for mandatory fields

Example reports which we are extracting data from:
[HHE_3.pdf](https://github.com/HumanExposure/factotum/files/2861896/HHE_3.pdf)
[HHE_0.pdf](https://github.com/HumanExposure/factotum/files/2861683/HHE_0.pdf)

.csv with example extracted data from the two above reports (this is a bit messy but should help give you an idea)
[dataextraction.zip](https://github.com/HumanExposure/factotum/files/2862019/dataextraction.zip)

**Comment by mwfrost** [comment]
@kdionisio Kathie, is an extraction script being recorded with each one of these HH documents?

**Comment by kdionisio** [comment]
@mwfrost Yes, but it is just a ‘dummy’ script because I think we require an
extraction script to be associated. Data extraction is being done manually
so there isn’t a true extraction script being applied. All HH reports (and
only HH reports) are being associated with an ‘HH report dummy extraction
script’.

**Comment by kdionisio** [comment]
I think I reference the extraction script in the related ticket (677?)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kdionisio** [comment]
@mwfrost I just realized something ...in terms of required functionality...data group type HH does not *need* to be associated with an extraction script since the data documents are being extracted manually. But it is ok if we just associate these docs with a dummy extraction script if that’s easiest due to current set up. Perhaps this should have been my original comment!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mwfrost** [comment]
Is there a particular Document Type that the Data Documents related to HHE Reports will have?

**Comment by kdionisio** [comment]
@mwfrost No....I would probably create a new document type for the HHE reports (they don't really fit any of our existing document types). All HHE reports fitting this data model would have the same document type. Not sure if that is the info you need but let me know if there are other questions!

**Comment by mwfrost** [comment]
@kdionisio Thanks, we will think about whether to add that document type as a migration or just assume that someone will create it in the admin panel

**Comment by kdionisio** [comment]
@mwfrost Yeah, typically I just add them in the admin panel but just let me know. If it helps I can do that today. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mwfrost** [comment]
I will add both the data group type and the document type as a migration that first checks to see if they exist
