### ISSUE TITLE
extracted data for new data group type - webform

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#677]
As a Factotum user, after creating a data group of data group type HH
I would like the ability to enter extracted data manually for each data document
So that I can enter data into Factotum as reports are being read and extracted individually by a user

Definition of Done:
From the data group index page (http://factotum.epa.gov/datagroup/) for a data group of type HH, I am able to navigate to a form that allows me to enter extracted text fields associated with each data document

User input to the `population_gender` field should be constrained to the choices of "Male," "Female," or "Both." This may involve an edit to the model's field definition.

Test: 
If data document has been uploaded, there is a navigation element to get to the form to enter extracted text and/or if the data document has not yet been uploaded, no navigation element exists.

**Comment by mwfrost** [comment]
@kdionisio Do I understand correctly that a csv file will be uploaded to populate the *data documents* in a data group of type HH, but there is no csv upload to create the *extracted text* equivalent?

**Comment by kdionisio** [comment]
@mwfrost correct. A 'registered records' csv will be uploaded to register each of the data documents (same process/workflow/functionality that already exists). But there is no 'extracted text' csv to be uploaded. The documents will be manually extracted one by one so a webform type functionality for data entry for one data document at a time seems most useful.

**Comment by mwfrost** [comment]
@kdionisio Thanks. This is the first such instance of manually entering extracted data for a document, right? Will there likely be others?

**Comment by kdionisio** [comment]
@mwfrost It is not actually! Habits and Practices data documents are set up to be manually extracted and input via webform.

Yes, it is certainly likely there will be other data documents in the future that will be manually extracted also.

**Comment by mwfrost** [comment]
@kdionisio Great. I will try to build a generalized solution for manual data entry.

**Comment by mwfrost** [comment]
@kdionisio The data document detail view includes some conditional logic that excludes the "Products" card when the document's data group is "Habits and Practices." We now have other data group types that will not link products to the documents, right? This new HH document type, for example?

**Comment by kdionisio** [comment]
@mwfrost
Correct the HH doc type also does not link to products!

**Comment by debboutr** [comment]
@kdionisio what are the fields that you will want to have in the HH child form? I have 

- raw_cas
- raw_chem_name

are there others you want in the card for the HH children?

**Comment by kdionisio** [comment]
Are you referring to the web form data entry page for docs in data group type HH? If so then all of the fields listed in #676 would need to be present.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by debboutr** [comment]
this issue was completed along with issue #694. KABOOM!
