### ISSUE TITLE
view already assigned attributes on bulk att. assignment page

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#685]
As a data curator working in Factotum,
I want to be able to view previously assigned attributes/tags for each product in the bulk_product_tag table
So that I do not repeat work by reassigning tags to products which already have those tags assigned.

Definition of Done:
On http://factotum.epa.gov/bulk_product_tag/ page, user should be able to see already assigned attributes for each product

**Comment by zachmunzenrider** [comment]
Can someone help me out on the status of this ticket? I had worked on this ticket, then Rick approved it, then Dave moved it back to In Progress, and now Matt has assigned himself to it.

**Comment by mwfrost** [comment]
I assigned myself to review it. I'll revisit it and see where we stand.
