### ISSUE TITLE
create confidence level for extraction scripts

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#687]
As a product owner,
I want the ability to assign a confidence level to each extraction script
So that I can utilize this categorization of confidence level of the associated extracted text objects in other functionality in the application

Definition of Done:
- Ability to assign, within admin panel, a confidence level to each registered script of type 'EX' (i.e., extraction scripts only, does not apply to download scripts). 
- Confidence level will be represented as an integer from 1-100 inclusive
- When an extraction script is registered, the default confidence level is 1
- Confidence level is a required field for every registered extraction script (can not be null)
- For all extraction scripts that currently exist in the database, set the confidence level to 1

Action item for Kathie: Upon completion of this ticket, Kathie to assign actual confidence level for each extraction script within admin panel

**Comment by mwfrost** [comment]
This looks simple to implement.

One question: is this qualitative confidence index really so fine-grained that you need 100 values on the scale? Is it going to be expressed as a percentage at some point?

**Comment by debboutr** [comment]
if we add this field to the `Script` model both types of scripts, all types would have the field. Would it be okay to just set all scripts w/ the default `confidence` and then likely never it them OR do we want to make a new model (i.e. subclass) to add this field on to only the 'EX' type?? 
```
    TYPE_CHOICES = (('DL', 'download'),
                    ('EX', 'extraction'),
                    ('PC', 'product categorization'),
                    ('DC', 'data cleaning'))
```
It doesn't seem likely that we are going to have thousands of scripts so keeping this new field in the same table along with the others is probably okay?

**Comment by kdionisio** [comment]
I'm fine with the other types of scripts having a field available for confidence level just knowing we will likely never use it, especially if that makes this much easier to implement.
