### ISSUE TITLE
Manually enter extracted text for data group type CP - web form

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#694]
As a data curator working in Factotum
I want to be able to manually enter extracted text for documents belonging to data group type chemical presence list (CP)
So that I can efficiently complete and record manual data extraction

Many documents of data group type CP will need to be manually extracted, thus the desire to have a webform or similar available for manual entry of extracted data for documents of group type CP.

Note: similar to #677 and #546 

Definition of Done:
- Ability to manually enter extracted data directly within Factotum application for a data document of group type CP
- fields available in data entry web form should be all user entered extracted text/extracted chemical fields associated with documents of group type CP

**Comment by debboutr** [comment]
@kdionisio what fields would you want to enter in upon the creation of a new ExtractedCPCat object? we have just been displaying in the card...

- doc_date
- cat_code
- description_cpcat
- cpcat_sourcetype

there is also a `cpcat_code` field that we inherit from ExtractedText that is in the fields of the CSV...

**Comment by kdionisio** [comment]
@debboutr I would want the ability to add/fill in the following fields related to this data group type, specifically:

from dashboard_extractedcpcat:
- cat_code
- description_cpcat
- cpcat_code
- cpcat_sourcetype

from rawchem (or whatever raw chemical model is appropriate where this data is stored):
- raw chem name
- raw cas

from extractedtext
 - prod_name
 - doc_date
 - rev_num
