### ISSUE TITLE
Automated documentation of project

### ISSUE THREAD

**Issue by mwfrost** [HumanExposure/factotum#700]
The last time anyone updated the data dictionary in the wiki was July 2018. We need to maintain documentation as comments in the code, and use an automated solution to publish it. The sooner we start this, the better, since new team members will benefit from the docs.

The `admindocs` application publishes comments as documentation to the admin panel:
`https://docs.djangoproject.com/en/2.0/ref/contrib/admin/admindocs/`

The `sphinx` tool generates HTML doc pages automatically:
`https://madradavid.com/documenting-your-django-application-sphinx/`

Maybe we need a "Documentation" epic.

**Comment by kdionisio** [comment]
yes please yes please. I am happy to help with this in terms of filling things out.
