### ISSUE TITLE
new comp. record not saving on QA page

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#701]
When a user enters a 'new composition record' (e.g. a new chemical) on the QA page (http://factotum.epa.gov/qa/extractedtext/271749/), the new record does not appear to save.

Workflow:
- User selects 'edit composition records' button to make the 'new composition record' fields editable
- user enters values into 'new composition records' fields
- user selects 'save edits'
- rather than seeing the newly entered composition record/chemical as an additional record on the page, the newly entered record disappears into the ether....

** Amended to note that edits to a current composition record also do not save

Definition of Done:
ability to add and save new composition record on QA page, and to save edits to current composition record

**Comment by mwfrost** [comment]
This appears to be another case where the form is being unsuccessfully validated, but the UI is not prompting the user to add the missing values. I just tried adding a Composition record on this page:
`http://127.0.0.1:8000/qa/extractedtext/7/`
The console complained about these missing values, but the UI did not:
```
[{'ingredient_rank': ['This field is required.'], 'raw_central_comp': ['This field is required.']}, {'report_funcuse': ['This field is required.'], 'ingredient_rank': ['This field is required.'], 'raw_central_comp': ['This field is required.'], 'rid': ['This field is required.']}]
```

**Comment by debboutr** [comment]
looks like the `alert-danger` is being added to the fields where there is an error here, but it is difficult to see on the border of the div. 

we probably also need to move the DSSToxLookup records somewhere, maybe a div that overlaps the card at the bottom? I don't believe these are going to be editable fields now, right? `rid` should now be n the `ExtractedChemical` form

**Comment by mwfrost** [comment]
As we discovered in the sprint review, the QA page is failing to save edits now, maybe due to the presence of the related DSSToxLookup records. They DSSToxLookup fields need to be excluded from all the form-processing logic that expects user input.

**Comment by mwfrost** [comment]
In tickets #654 and #627 , we changed the way each extracted record relates to other objects. This has broken the editing functionality on the QA page.

Definition of done:

New selenium tests walk through the process of opening a document for QA, editing a raw chem value that has been curated (linked to a DSSToxLookup record), and saving the edits.
