### ISSUE TITLE
bubble plot for occupational PUCs

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#709]
As a factotum user
I want to view a separate bubble plot for each 'PUC type'
Because the different PUC types represent different types of data which will be evaluated independently

Definition of Done
- new bubble plot should appear on dashboard representing the 'occupational' PUC type (which includes ~1000 PUCs)

**Comment by mwfrost** [comment]
An alternate display for this sort of data:
https://en.wikipedia.org/wiki/Treemapping

**Comment by kdionisio** [comment]
no longer applicable
