### ISSUE TITLE
Refactor Products list page

### ISSUE THREAD

**Issue by zachmunzenrider** [HumanExposure/factotum#712]
The Products list page as currently designed is not scalable. Update this page to accommodate the dataset size expected to exist in production data for products.

This could involve creating a server-side datatable to replace the current client-side datatable. It will probably also involve improving the efficiency of the get_uber_puc functionality.

**Comment by zachmunzenrider** [comment]
Been looking at this discussion of django annotations and querysets for ideas of how to approach this:

https://medium.com/@hansonkd/the-dramatic-benefits-of-django-subqueries-and-annotations-4195e0dafb16

**Comment by kdionisio** [comment]
product list page was removed from application in #798
