### ISSUE TITLE
creation of extracted chemical records even with error in extracted text upload

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#725]
It appears that, when an extracted text file was uploaded for a data group but the user encountered a factotum error during the upload (e.g. XX field too long/too many characters), that extracted chemical records were still created within the database. After the user corrected the error in the extracted text file and reuploaded, this resulted in duplicate, identical extracted chemical records for a single data document.

**Note could check this by looking at the extracted chemical records for the 'Bell Labs' data group on prod. See the date/time stamp to see when the duplicate extracted chemical records for a given data document were created (if the above is the problem, the date/time stamps are likely minutes apart for the duplicate records)

**edited 7/30/2019 to add this issue can also be seen in the  http://factotum.epa.gov/datagroup/506/ data group, or as an example the http://factotum.epa.gov/datadocument/1377017/ data document.

Definition of Done:
Desired behavior would be that if a user attempts to upload an extracted text file and encounters an error, that none of the extracted text or extracted chemicals in the file are pushed to the database (i.e. no extracted text or extracted chemical objects are created)

**Comment by kdionisio** [comment]
@mcovalt Do you think this can be closed due to the revamp of the data group page work?

**Comment by mcovalt** [comment]
It should be fixed, but there are no tests for this. I think it would be a good idea to make a test or two prior to closing it.

**Comment by kdionisio** [comment]
created #1023 to write test on this issue
