### ISSUE TITLE
correct DSSTox statistic on Dashboard page

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#729]
As the product owner
I would like the 'DSSTox Chemicals' box on the Dashboard page to reflect the number of unique SID's existing in Factotum
So that I can assess the chemical scope which our data covers

It is unclear to me how the number in the DSSToxChemicals box on the Dashboard page (http://factotum.epa.gov/) is currently calculated.

Definition of Done:
DSSTox Chemicals statistic on dashboard page should reflect the number of unique SIDs existing in Factotum.

**Comment by mwfrost** [comment]
The current stat is the number of curated RawChem records. It should instead be reporting the number of DSSToLookup records.
