### ISSUE TITLE
adjustments to raw chemical list download

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#732]
As the chemical curator,
I want to be able to prioritize chemicals for curation in the downloaded raw chemical list
So that I can more efficiently complete chemical curation work that is most important

This ticket will modify functionality implemented in #252

Currently in the production version of Factotum, we have >1 million extracted chemical records, and only 172,000 have been curated to an SID. Therefore, when a user uses the 'download chemical list' functionality, they will download a list of ~800,000 chemicals for curation. There is a need to be able to subset this list to allow for easier chemical curation. One way that we can (externally to Factotum) prioritize the list is by data source/data group that the extracted chemical belongs to.

Definition of Done:
- In the download created in #252, add the data group id as an additional column in the downloaded csv

**Comment by mwfrost** [comment]
https://docs.djangoproject.com/en/2.1/howto/outputting-csv/#streaming-large-csv-files
