### ISSUE TITLE
display true chem name and SID on data doc page

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#733]
There appears to be a bug resulting in the true chem name and DTXSID not displaying on the data document page. The fields are displayed on the data doc page, but the fields are not populated.

Example in production: http://factotum.epa.gov/datadocument/133494/
On the above page, the 'true cas' field is populated and displaying data, but the 'true chem name' and 'DTXSID' fields are blank. However, when you query the prod database directly (using the query below), you see that the true chem name and DTXSID fields for this data document *are* populated with data. 

```SQL
SELECT * FROM prod_factotum.dashboard_rawchem t1, dashboard_datadocument t2
where t1.extracted_text_id = t2.id
AND t2.id = 132540
```
```SQL
SELECT * FROM prod_factotum.dashboard_rawchem as t1, dashboard_datadocument t2, dashboard_dsstoxlookup t3
where t1.extracted_text_id = t2.id
AND t2.id = 132540
AND t1.dsstox_id = t3.id
```
Definition of Done:
True chem name and DTXSID fields on data document page should be populated if those fields are populated in the database.

**Comment by mwfrost** [comment]
I think this has been resolved on `dev`. in our seed data, the data document with ID=7 should have a curated chemical, so you should see all three curated attributes on `/datadocument/7/`

**Comment by kdionisio** [comment]
closing because this was resolved as part of the Hornet sprint.
