### ISSUE TITLE
delete document

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#738]
As a Factotum data curator
I would like the ability to delete an individual data document 
So that I can clean up our data if I find a document that is not relevant for our work

Definition of Done:
Ability to delete a data document from the data document page

**Comment by mwfrost** [comment]
This would be good to experiment with:
https://django-model-utils.readthedocs.io/en/latest/models.html#softdeletablemodel

**Comment by mwfrost** [comment]
The delete button should be on the data document detail page.
