### ISSUE TITLE
change field titles on data doc page

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#744]
As the product owner
I would like to change the labeling and position of fields on the data document page (http://factotum.epa.gov/datadocument/133494/)
To make labeling consistent and to group like data

Definition of Done:
- on data doc page, 'True cas:' label should be 'True CAS:'
- on data doc page, 'True chemname:' label should be 'True chemical name:'
- on data doc page, 'Sid:' label should be 'DTXSID'
- Question: re. placement - Is it possible to put the true cas/true chem name fields next to the raw cas/raw chem name fields? if not put under them? Really you'd like to be able to easily compare these when looking at the page.  Also how difficult to link from the SID out to the relevant chemical page on the CompTox Dashboard?

**Comment by mwfrost** [comment]
The lack of `verbose_name` values for our model attributes has been driving me crazy. I added a bunch of them on a previous ticket, then removed them when the scope of the changes seemed larger than what the ticket requested.
The DSSToxLookup model has these fields:
```
    sid = models.CharField(max_length=50, null=False, blank=False, unique=True)
    true_cas = models.CharField(max_length=50, null=True, blank=True)
    true_chemname = models.CharField(max_length=500, null=True, blank=True)
```
Should look like:
```
    sid = models.CharField('DTXSID', max_length=50, null=False, blank=False, unique=True)
    true_cas = models.CharField('True CAS', max_length=50, null=True, blank=True)
    true_chemname = models.CharField('DTXSID', max_length=500, null=True, blank=True)
```

**Comment by kdionisio** [comment]
will be taken care of as part of #865, full scale redesign of data doc page
