### ISSUE TITLE
ability to edit data document title

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#746]
As a factotum user
I would like the ability to edit the data document title from the data document page
So that I can make edits and corrections to the data document title as necessary

http://factotum.epa.gov/datadocument/133494/

Definition of Done:
- ability to edit data document title from data document page
~- ability to edit/change download script from data document page~
(Note it is ok to combine all editing functionality for data document page header into one 'editing' modal/window - just note that the *only* fields in that header which should be editable by the user are the data document title, the data document type, ~the download script~, and the Note)

Updated definition of done 4/11/2019 - strike through added by Kathie, see below comment for explanation

**Comment by mcovalt** [comment]
> ability to edit/change download script from data document page
Should this edit affect only the specific data document being viewed or all data documents within its data document group?

**Comment by kdionisio** [comment]
Eliminating second bullet under definition of done because it would likely cause errors on the data group page (where we display the download script associated with the entire data group) if we allowed for changing the download script for a single data document
