### ISSUE TITLE
record user id for manual data extraction

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#749]
As the product owner,
I would like to know which user completed manual data extraction for a given data document
So that I can ensure data quality by being able to isolate documents extracted by a user if there are problems.

Definition of Done:
For manually extracted data documents, system should record user id of the individual completing the data entry web form (e.g. for HH and CP data group types, which have the ability to enter extracted text manually via webform)

**Comment by debboutr** [comment]
it seems likely that we would either store this user in the `DataDocument` OR `ExtractedText` model. Would it then be assumed that the children were created by the same user? seems right, but it wouldn't necessarily have to be true. Once this field is made, would a `null` value signify that it was automated and a user signify manual entry?

**Comment by kdionisio** [comment]
taken care of in #1128
