### ISSUE TITLE
ability to add >1 product with same title

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#756]
When creating an individual product manually from the data document page, a user is able to create multiple products associated with a single data document if the product names are different, but if the user attempts to create two products with the same title (but different UPC), associated with the same data document, the two products are *not* created.

e.g., on this page (http://factotum.epa.gov/datadocument/282010/), one product was created using the 'create new product' web form. Upon attempting to create a second product with the same name associated with the same data document, the 'create new product' form was completed (http://factotum.epa.gov/link_product_form/282010/) and saved, but a second product was not created (I have confirmed that the product was not created in the database, so this isn't simply a data display issue).

However, on this page (http://factotum.epa.gov/datadocument/281972/), user was able to manually create multiple products associated with the data document (each product had both different UPC and different titles)

Definition of Done:
Ability to manually create >1 product associated with a data document even if the product title/name is the same

**Comment by mwfrost** [comment]
line 100 in product_curation.py:
```
            product, created = Product.objects.get_or_create(title=title,
                                                        data_source_id = ds_id)
```

Should use the UPC for the lookup instead

**Comment by mwfrost** [comment]
Please add a test for this specific use case
