### ISSUE TITLE
manually add extracted text for CO data doc

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#757]
As a Factotum user,
I would like the ability to manually enter extracted text for a data document of data group type CO
So that I can enter data being extracted manually directly into Factotum

If extracted text does not exist on a data document page (http://factotum.epa.gov/datadocument/281992/), currently the user sees the message 'Extracted text doesn't exist' in the 'Extracted Text' box.

Definition of Done:
- If extracted text does not exist, user should have ability to manually enter extracted text (both extracted text for the CO data doc, and extracted chemical records).

**Comment by mwfrost** [comment]
An example HH document where this functionality has already been implemented:
http://127.0.0.1:8000/datadocument/354781/

Example Composition document in the seed data that has not been extracted:
http://127.0.0.1:8000/datadocument/155324/
