### ISSUE TITLE
change statistics in the data sources table

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#758]
As the product owner
I would like to view different statistics in the data sources table
so that I can easily view statistics that more readily inform my decision making as to priorities and work needed in Factotum.

Definition of Done:
- Remove % registered and % uploaded stats from data sources table (http://factotum.epa.gov/datasources/)
- Add # registered to data sources table (should reflect total # records registered in the data source)
- Add # uploaded to data sources table (reflecting total # docs uploaded and matched in the data source)
- Add # extracted to data sources table

**Comment by mwfrost** [comment]
When these are rewritten, please make sure to use aggregations instead of a loop.
```
from django.db.models import Count, Q, F, FloatField, ExpressionWrapper

registered = ExpressionWrapper(Count('datagroup__datadocument') / F('estimated_records'), output_field=FloatField())
uploaded   = ExpressionWrapper(Count('datagroup__datadocument', filter=Q(datagroup__datadocument__matched=True)) / F('estimated_records'), output_field=FloatField())
ds_list    = DataSource.objects.annotate(registered=registered).annotate(uploaded=uploaded)
print(ds_list.query)
```

**Comment by mwfrost** [comment]
SQL activity on the old page:
```
87.95 ms (53 queries including 48 similar )
```
On the new page:
```
44.68 ms (6 queries )
```
This difference is just with seed data. On PROD the difference will be much larger.
