### ISSUE TITLE
StopIteration error on data document page

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#764]
I am seeing a 'StopIteration' error when trying to view the below data document pages.

http://factotum.epa.gov/datadocument/155284/  -- `CO` dg type  { 222 chem records }
http://factotum.epa.gov/datadocument/1372071/  -- `CP` dg type { 188 chem records ]

(Note that on the second URL, page was displaying fine until 'notes' were added and after >150 child records were added)

Definition of Done:
URL above displays appropriate data document page and not an error.

**Comment by dmlyons2** [comment]
@dmlyons2 Change the django.settings DATA_UPLOAD_NUMBER_FIELDS = 1000 default -> change to 5000

**Comment by dmlyons2** [comment]
Changed DATA_UPLOAD_NUMBER_FIELDS = to 5000, then 10000 -> did not solve the problem. To duplicate this error load `production` database and navigate to one of the above links.
