### ISSUE TITLE
QA group not created

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#771]
**Delete extracted text associated with an extraction script (needs to include deleting associated qa gorup)

Selecting the 'Begin QA' button on the QA page (http://factotum.epa.gov/qa/) for the Proctor & Gamble Ingredient Disclosures script (dashboard_script.id = 19) does not assign any documents into the QA group.

I reset the script to 'QA not begun' and tried a second time to no avail.

Also note that QA group creation was successful for another script used within a different data group, but assigned to the same data group type within the same data source.

Definition of Done:
R

**Comment by debboutr** [comment]
how many documents are related to the script you're talking about in the table @ the URL above?

**Comment by kdionisio** [comment]
I believe there are 222 documents associated with the extraction script I am trying to create a QA group for.
