### ISSUE TITLE
Can't edit children twice in QA view

### ISSUE THREAD

**Issue by debboutr** [HumanExposure/factotum#786]
ExtractedChildren can only be edited once with a blank QANotes instance
(Note this is a problem both when editing existing child records and saving >1 time, and when adding >1 new child record on QA page - for the latter, user must enter the new child record, then save edits in order for another blank child record to appear, then enter the second new child record, then save again, causing same error)

**To Reproduce**
1. Go to `qa/extractedtext/<pk>`
2. Edit a child object, then save
3. Edit a child object again, then save

**Expected behavior**
We want to see the QANotes, if added, get carried through the save process when editing child objects

**Screenshots**
![validationQAnote](https://user-images.githubusercontent.com/7052993/55267258-67891d80-523e-11e9-9557-a268dc4684dc.png)

**Additional context**

When a QANote model object is instantiated, which happens upon the GET request in this view, the `qa_notes` field is initially == `None`. The request.POST object that we are instantiating the form with
`notesform = QANotesForm(request.POST, instance=note)`
does not have that field in the form, it is coming specifically from the `extracted_formset_table` form, which doesn't hold the qa_notes input
upon the first save, the `qa_notes` field becomes an empty string `''`, but when saved again this won't pass validation.

Definition of Done:
Ability to edit and save QA form >1 time without seeing an error (including ability to add and save >1 child record without seeing an error)
Note solution should be simplest solution that allows for multiple saves of the QA page without seeing an error, understanding that QA notes will only be saved when the 'approve' button is used, not when the 'save' button is used.

**Comment by mwfrost** [comment]
Something about the control flow in the `qa` view is causing the page to invalidate the document_type attribute after a save. 

The document type shown with a GET request:
![sc_2019417_142645_68.png](https://images.zenhubusercontent.com/5be34a63f724c70c7221c972/9e90f47e-643d-4d75-9782-dbc3d207cff5)

With a POST request:
![sc_2019417_142633_70.png](https://images.zenhubusercontent.com/5be34a63f724c70c7221c972/1e0c553e-8e02-4629-bbcf-0d2b29e0146f)

I will fix this in the course of correcting the other problem.
