### ISSUE TITLE
QA and/or DataDocument page formset redesign

### ISSUE THREAD

**Issue by mwfrost** [HumanExposure/factotum#790]
We discussed changes to the layout of the child records on the QA page - they may also be applicable to the data document show page. 

For each raw chem record, the row will contain a column with the raw chem name as an h4 and the raw cas as a muted h4. Then the other attributes will appear as a list of labels and values to the right. 

Rather than using a single `<form>` for all the detailed records at once, switch to record-by-record editing, maybe with AJAX or a modal window. 

![Image from iOS](https://user-images.githubusercontent.com/201835/55476333-4e88bf80-55e4-11e9-8969-c4d888811f1e.jpg)

**Comment by kdionisio** [comment]
rewritten as #879
