### ISSUE TITLE
Refactor conditional logic in data_document_detail.html template

### ISSUE THREAD

**Issue by mwfrost** [HumanExposure/factotum#792]
The template for the data document detail page needs some attention. It includes hard-coded field names that should instead be drawn from the `verbose_name` property of the field and it uses a series of conditional statements like `{% if not doc.data_group.is_habits_and_practices %}` to determine which data to display. The grouptype-specific logic should be pulled out into smaller template files, and the template should probably not be in the business of specifying which fields should appear on the page. That probably belongs in the view that delivers the data.

The source file: `https://github.com/HumanExposure/factotum/blob/dev/templates/data_document/data_document_detail.html`

**Comment by mwfrost** [comment]
Another example of how the conditional logic has failed: this statement `{% if doc.data_group.is_hh %}` allows the template to show certain HH-specific fields (HH Report No., Study Location, etc) when the document belongs to an HH data group, but there is no comparable branch for CPCat records. The only fields that show up for a CPCat record are the ones that belong to the ExtractedText object. The Cat Code, CPCat Code, etc fields do not show up. Was this a deliberate choice?

**Comment by kdionisio** [comment]
not needed anymore
