### ISSUE TITLE
Create Elastic Index

### ISSUE THREAD

**Issue by dmlyons2** [HumanExposure/factotum#799]
## Describe the ideal solution or feature request
Referencing the requirements for search in #797, model `prod_factotum` data to enable a search from input on chemical name, CAS, or SID and results that consider raw_cas, raw_chem_name, true_cas, true_chemname and sid fields.  

All files created should go in the [Factotum Elastic](https://github.com/HumanExposure/factotum_elastic) repo

## Difficulty, impact, and usage score
| Technical difficulty | User goals | Usage frequency |
|--------------------| --------------------| --------------------|
| Medium|  Improved Search | Daily |

## How does this tie into our current product?
This is the beginning steps for upgrading Elasticsearch within our app

## Who asked for this?
@dmlyons2 

## Definition of Done

- Create an Elasticsearch index named factotum_chemicals to provide the information requested that will be searched for through ticket #797 
- Populate factotum_chemicals index from the seed data
- Create a mapping file for factotum_chemicals to return the information required in ticket #797 

## What is the test(s)
Use kibana to demonstrate a search on factotum_chemicals. (live demo at review)

**Comment by mwfrost** [comment]
Still a work in progress, but if anyone wants to play around...

This ticket changes the contents of `requirements.txt`, so there's a file called `search_notes.md` to explain the update process. 

But once that is complete, run `python manage.py search_index --rebuild` and it will serialize your dev database into elastic.

In Kibana:
```
GET /factotum_chemicals/_mapping/
```
Output:
```
{
  "factotum_chemicals" : {
    "mappings" : {
      "doc" : {
        "properties" : {
          "data_document_id" : {
            "type" : "integer"
          },
          "dsstox" : {
            "properties" : {
              "true_cas" : {
                "type" : "keyword"
              },
              "true_chemname" : {
                "type" : "keyword"
              }
            }
          },
          "facet_model_name" : {
            "type" : "keyword"
          },
          "product_count" : {
            "type" : "integer"
          },
          "raw_cas" : {
            "type" : "keyword"
          },
          "raw_chem_name" : {
            "type" : "text"
          }
        }
      }
    }
  }
}
```

This is just the mapping. It's like the elasticsearch version a database table description. It's what will be pasted into the Kibana console on prod to tell it how the serialized data will be structured.

The serialized data should be in elastic on your dev environment, thanks to the python management command, though, so you can still see the results. 

To search for a CAS, try:
```
GET /factotum_chemicals/_search/
{
    "query": {
        "query_string" : {
            "default_field" : "raw_cas",
            "query" : "0000075-37-61"
        }
    }
}
```

Then the output looks like this:

```
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 6.291569,
    "hits" : [
      {
        "_index" : "factotum_chemicals",
        "_type" : "doc",
        "_id" : "758",
        "_score" : 6.291569,
        "_source" : {
          "facet_model_name" : "Chemical",
          "data_document_id" : 254780,
          "product_count" : 0,
          "raw_cas" : "0000075-37-61",
          "dsstox" : { },
          "raw_chem_name" : "hydrofluorocarbon 152a"
        }
      }
    ]
  }
}
```

**Comment by mwfrost** [comment]
The PR for this ticket, which is on the `factotum_elastic` branch, is here:
https://github.com/HumanExposure/factotum_elastic/pull/1
