### ISSUE TITLE
extracted CP fields not displaying on data doc page - take 2

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#801]
When entering a new set of extracted text for a CP data document using the new webform functionality for manual data entry, the data entered is not displayed on the data doc page after saving in the modal window. 

(note originally ticketed in #751 but functionality was not achieved in that ticket even though ticket was closed)

Definition of Done:
- After entering and saving CP data in modal window, data should be displayed on the CP data document page.

- Additional fields to display on the data document page (from extractedcpcat model): 

cat_code (labeled as 'cat_code')
description_cpcat (labeled as 'CPCat cassette')
cpcat_code (labeled as 'ACToR snaid')
cpcat_sourcetype (labeled as 'CPCat source')

- if any of the above fields are null, field and field label are not displayed

**Comment by debboutr** [comment]
{% if extext.cpcat_sourcetype %}
    ...display field w/ label
{% endif %}
