### ISSUE TITLE
manually entered extracted child records not displaying on CO data doc pages

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#802]
Recently completed ticket #757 to implement ability to manually add extracted text data for documents of data group type CO directly into Factotum. However when extracted child records are added using this new functionality, the data entered does not display on the page (it disappears into the black hole)

Definition of Done:
Extracted child records entered manually on data doc page for CO data docs should display on the page when saved.

**Comment by justatad44** [comment]
The behavior I am seeing is that the data enter the black hole when the unit type is left out. Can this be confirmed? And if so, how should this be handled? Default to "unknown"? A pop-up alert to let users know it was left out?

**Comment by mwfrost** [comment]
This is happening because the unit type is a required field, and the new form does not include the validation logic that the QA page uses. In `data_document.py`:
```
@login_required
def extracted_child_edit(request, pk):
    doc = get_object_or_404(DataDocument, pk=pk)
    _, ChildFormSet = create_detail_formset(doc, extra=1, can_delete=True)
    formset = ChildFormSet(request.POST, instance=doc.extractedtext)
    if formset.is_valid():
        formset.save()
    return redirect('data_document', pk=doc.pk)
```

If the formset fails to validate, the control flow skips over it silently. We need to implement a new `else` that handles an invalid formset.

**Comment by justatad44** [comment]
Correct, but I wanted to confirm that this is indeed the behavior the ticket was based on (ie "black hole") and how it should be handled in the else.

**Comment by kdionisio** [comment]
Additional notes to clarify - 
it is correct that if 'unit type' is included on the new extracted child record being created using the manual data entry form, the new child record DOES display on the page. If the unit type is NOT included, then the child record does NOT display on the page.

To resolve: Note that 'unit type' should only be a required field when at least one of raw min comp, raw central comp, or raw max comp are populated. If none of these three fields are populated, then unit type should *not* be required.

**Comment by mwfrost** [comment]
#539 is the ticket that describes the functionality requested above.

**Comment by kdionisio** [comment]
To clarify - after discovering what is causing this bug, definition of done will be a adding a message to the extracted child record input form to note that unit type is a required field. Overhaul of editing functionality will address the conditional logic stated above.
