### ISSUE TITLE
Upgrade to  Django 2.2

### ISSUE THREAD

**Issue by dmlyons2** [HumanExposure/factotum#803]
Upgrade to  Django 2.2

## Definition of Done
- modify requirements.txt to be equals rather than greater thans

**Comment by dmlyons2** [comment]
@dmlyons2 will provide pip freeze from prod

**Comment by debboutr** [comment]
I think the thing to do here might be to just lock our major and minor version to `2.2`, seems like bug fixes and patches will come in in the micro version `major.minor.micro` which we will likely want. So, for this, we would want to use the following in `requirements.txt`

`Django>=2.2,<2.3`

[PEP 440](https://www.python.org/dev/peps/pep-0440/#semantic-versioning)

**Comment by debboutr** [comment]
looks like we will need to upgrade the version of `mysqlclient` along with this 

```
  File "/home/debboutr/anaconda3/envs/upg/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 36, in <module>
    raise ImproperlyConfigured('mysqlclient 1.3.13 or newer is required; you have %s.' % Database.__version__)
django.core.exceptions.ImproperlyConfigured: mysqlclient 1.3.13 or newer is required; you have 1.3.12.
```
this is given in the release notes

`https://docs.djangoproject.com/en/2.2/releases/2.2/`


the `mysqlclient` is a pkg we have always needed to add to `requirements.txt` but haven't, I'll do it here w/

`mysqlclient==1.3.12`

**Comment by debboutr** [comment]
if following the wiki on dev setup the `certifi` package will be installed, but as version `2019.3.9` in the 

`conda create` command

when we then use pip to install `requirements.txt` it expects an older version and errors on uninstalling

```
ERROR: Cannot uninstall 'certifi'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

I would think we will always want the most current version so should we just remove the `==2018.11.29`??

`requirements.txt` is ahead of `prod` at the moment for this pkg
