### ISSUE TITLE
creation of a PUC landing page

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#813]
As a product owner
I would like to create a PUC landing page for each PUC
So that I have a place to represent up to date summaries for each PUC and can link to the PUC landing page from other pages in Factotum

Definition of Done:
PUC landing page includes summary information for 1 PUC, including:
1. Basic information about the PUC
- PUC name (gen_cat, prod_fam, and prod_type fields from dashboard_puc model)
- definition of the PUC (description field from dashboard_puc model)
- assumed attributes for the PUC
- allowed attributes for the PUC
- 'kind' of the PUC
2. Summary statistics about the PUC
- number of products assigned to that PUC
- number of different curated chemicals (counted by unique DTXSIDs) associated with that PUC
- number of documents associated with the PUC (e.g. a PUC may have 10 products associated with it, but all 10 products may be linked to a single document)

**Comment by dmlyons2** [comment]
![2_813PUCLanding](https://user-images.githubusercontent.com/1336349/57027751-dde4bb00-6c02-11e9-96cd-7ffa20fff3ba.png)

**Comment by dmlyons2** [comment]
![image](https://user-images.githubusercontent.com/1336349/57027789-f48b1200-6c02-11e9-85fb-98b7335fb281.png)
