### ISSUE TITLE
link elastic search results to PUC landing page

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#814]
As a product owner
I would like to link the PUC represented on the elastic search landing page to the PUC landing page
So that Factotum users can easily view summaries of the PUC they are interested in exploring

Definition of Done:
On elastic search landing page created in #825, PUC included in search results should hyperlink to the PUC landing page created in #813

**Comment by mcovalt** [comment]
This was completed in PR #925. It was easier to include a fix to this issue than not.

**Comment by kdionisio** [comment]
completed as part of ticket #825
