### ISSUE TITLE
add data group id to uncurated chemical list download

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#822]
Per #732, please add data group id to uncurated chemical list download. Ticket was completed in Inchworm sprint but does not appear to be working in production.

Definition of Done:
data group ID appears as a column in the uncurated chemical list download on http://factotum.epa.gov/chemical_curation/

**Comment by mwfrost** [comment]
I think the changes made on ticket #732 were undone or overwritten when this functionality was moved from `views/get_data.py` to `views/chemical_curation.py`. I still have a local copy of the 732 branch, which I will push up to the repo for reference.

**Comment by mwfrost** [comment]
Here is the branch that contains the new column in the downloaded table and the test:
https://github.com/HumanExposure/factotum/tree/732_rawchem_download_update

**Comment by debboutr** [comment]
@kdionisio will we need to add the DataGroup ID into the upload as well?

![image](https://user-images.githubusercontent.com/7052993/56867715-682be580-699d-11e9-9e65-0a1cdffdfa6e.png)

**Comment by kdionisio** [comment]
Good question but no! Data group id is just to help me prioritize which
records should be curated first.
