### ISSUE TITLE
Change detail form background to bg-light

### ISSUE THREAD

**Issue by mwfrost** [HumanExposure/factotum#827]
The background color of each detail form in the data document detail page currently uses the `bg-info` selector, which is a saturated blue. That color is best used for smaller areas. Changing the form background to a less-saturated tone will make the page easier to look at and will preserve the more saturated colors for focusing attention where necessary, like on callout boxes or buttons.

In `templates/data_document_detail.html`, simply changing `<div class="card bg-info">` to `<div class="card bg-light">` will make this change.

**Comment by kdionisio** [comment]
closing - will be resolved in #862
