### ISSUE TITLE
change field labels on CP extracted text modal

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#836]
As the product owner
I would like the field labels in the CP extracted text editing modal to be the same as those displayed on the CP data document page
So that users are not confused by the fields.

Definition of Done:
Change field labels on CP extracted text editing modal to match the field labels currently reflected on CP data document page

No test required

**Comment by mwfrost** [comment]
these values should be specified in the model as `verbose_name` arguments to the attributes in the model
