### ISSUE TITLE
Product Use Category (PUC) Web Service

### ISSUE THREAD

**Issue by dmlyons2** [HumanExposure/factotum#842]
## Describe the ideal solution or feature request
Given a DTXSID such as DTXSID9022998, return json response of all PUC's that have products that contain the given chemical as well as a total number of products with that chemical within the PUC

## Difficulty, impact, and usage score
| Technical difficulty | User goals | Usage frequency |
|--------------------| --------------------| --------------------|
| medium | needed for a link to Chemical Dashboard |Daily |

## How does this tie into our current product?
Offer a machine to machine interface for consuming our data

## Who asked for this?
Chemical Dashboard product owner

## Definition of Done
- Given a GET request to `http://127.0.0.1/pucs?DTXSID9022998` return a list of PUCs that contain products that have data documents that match the DTXSID and a count of those products within the PUC

**Comment by kdionisio** [comment]
Page we are trying to populate with this web service is: https://comptox.epa.gov/dashboard/dsstoxdb/results?search=DTXSID9022528#exposure 

THe 'Product & Use Categories' sub-tab under the exposure tab on the left.

**Comment by mcovalt** [comment]
A PR has been made for this issue here: HumanExposure/factotum_ws#1.
