### ISSUE TITLE
add definition for PUC tags/attributes

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#854]
As the product owner,
I want the ability to store a definition for each PUC tag/attribute
So that users can easily reference the meaning for the PUC tag/attribute

Definition of Done:
1. ability to store definition for each PUC attribute (i.e. dashboard_puctag) (max 255 characters, not required)
2. ability to view/add/edit  PUC attribute definition from admin panel (i.e. view definition next to PUC attribute on this page: http://factotum.epa.gov/admin/dashboard/puctag/, edit attribute from this page: http://factotum.epa.gov/admin/dashboard/puctag/3/change/)
3. From Get Data page (http://factotum.epa.gov/get_data/), in Downloads section, underneath 'Download PUCs' button, add a 'Download attributes' button which allows user to download a csv listing the registered attributes (i.e. dashboard_puctag.name) along with their definition

**Comment by debboutr** [comment]
@kdionisio did you say that you have all of the defintinons in a CSV that we can load into the field for each PUC? or were you thinking that you were going to do it in the admin panel after we add the field? or something else?

**Comment by kdionisio** [comment]
I will add the definitions in via the admin panel after this is
implemented. There are <20 attributes so it won’t be an issue.
