### ISSUE TITLE
remove .txt documents from data group id=81

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#856]
As the product owner
I would like to remove all .txt data documents and associated data from the 'Walmart - in CPDat' data group
So that I can remove duplicate data/non primary source data from Factotum

Definition of Done:
1. Remove all .txt data documents, and any linked/associated data (e.g. extracted text or product data) from the 'Walmart - in CPDat' data group (dashboard_datagroup.id=81). 
2. All .pdf documents in above data group and their associated data should STAY in the data group

**Comment by dmlyons2** [comment]
Completed
