### ISSUE TITLE
restrict groups displayed on QA page

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#864]
As the product owner
I would like to clean up the QA pages
to more efficiently and correctly display data, removing data that is not relevant or not appropriate for the page.

Definition of Done:
- On this page: http://factotum.epa.gov/qa/extractionscript/, do *not* display scripts associated with CP data group types
- On this page: http://factotum.epa.gov/qa/chemicalpresencegroup/217/, remove the 'product name' column
- ~On this page: http://factotum.epa.gov/qa/chemicalpresence/,~
    - ~the statistic in the 'Percent QA checked' column should represent the % of data documents in that data group which have QA complete (ie # data docs with QA complete/total # data docs in that data group)~
    - ~the button currently indicating 'View chemical presence list' should change to text that states 'QA complete' once all data docs in the data group have QA complete~
KD edit 7/8/2019 - strike through bullet no longer applicable due to previously completed ticket

**Comment by debboutr** [comment]
this is somewhat unrelated to this ticket specifically, but may play a role in how it is solved. the code below is a method from the `Script` model
```
    def create_qa_group(self, force_doc_id=None):
        """
        Creates a QA Group for the specified Script object;
        Use all the related ExtractedText records or, if there are more than 100,
        select 20% of them. 
        """
        from .qa_group import QAGroup
        from .extracted_text import ExtractedText
        es = self
        # Handle cases where a QA group already exists for the script
        if QAGroup.objects.filter(extraction_script = es).count() == 1:
            # This is a valid state
            return QAGroup.objects.get(extraction_script = es)
        elif QAGroup.objects.filter(extraction_script = es).count() > 1:
            # this is a failure mode induced by the system's allowing
            # duplicate QA Groups to be created for a single script
            return QAGroup.objects.filter(extraction_script = es).first()
```

**Comment by debboutr** [comment]
@kdionisio  would **_scripts associated with CP data group types_** be a script that has even one ExtractedText record that is related to a CP data group OR would it need to be ALL ExtractedTexts related to the script?

**Comment by kdionisio** [comment]
@debboutr yes, you could implement the 'scripts associated with CP data group types' as a script that has >=1 extracted text record related to a CP data group.

From the science side, we do not have any extraction scripts that are linked to both CP and CO data groups, though I recognize that logic is not officially implemented as a requirement in the application.

**Comment by debboutr** [comment]
another quick thing about bullet #1, if the script has 0 documents, which I am guessing is rarely the case on prod, we probably don't want to see that script in the list on the `/qa/extractionscript/` page? right

**Comment by kdionisio** [comment]
@debboutr Correct!!

**Comment by debboutr** [comment]
@kdionisio referring to the firs part of the third or last bullet here, I think the reason you're asking for this is because you're seeing some positive value for the # of DataDocuments, but when you go to view the chemicalPresence lists there are none shown in the list. the reason that the 0% comes up for the percent QA checked and that there are no ExtractedText records made for these DataDocuments. Without and extractedText a DataDocument can NOT be qa_checked. Is this the issue you're having? Maybe when we go to the `/qa/chemicalpresencegroup/< datagroup.id >` instead of looking at a list of the ExtractedCPCat records we could just look at a list of the documents so that the user can get to the datadocument detail page so that they can add ExtractedTexts manually?

**Comment by kdionisio** [comment]
see KD edit within ticket above in response to @debboutr comment
