### ISSUE TITLE
change display of higher tier PUCs in bubble plot

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#866]
As the product owner
I would like to change how higher tier PUCs are represented in the Dashboard bubble plot
So that the bubble plot representation can better represent the science.

Definition of Done:
For a higher tier PUC (defined as a PUC with a gen_cat only, or a gen_cat and a prod_fam only), the size of the bubble should represent the number of products in that PUC PLUS the number of products in any more refined levels of that PUC.

e.g., for the PUC:
Personal care products (gen cat) - null (prod_fam) - null (prod_type), 
size of bubble should be 
number of products in Personal care products - null - null +
number of products in Personal care products - any prod fam - null +
number of products in Personal care products - any prod fam - any prod type

**Comment by debboutr** [comment]
@kdionisio what do you want to see in the output for the CSV that gets downloaded in the "Download PUCs" button on the `/get_data/` page?

right now @mwfrost has it set up with the following columns to provide the cumulative count of products for each PUC:
```
['General category','Product family','Product type','Allowed attributes','Assumed attributes','Description','PUC type','PUC level','Product count','Cumulative product count']
```
with both "Product count" **and** "Cumulative product count"
do you want both of these fields in the download file? or just a singular product count field that would be the cumulative number of products related to the PUC?
_also, if you want both are you good with the names?_

**Comment by mwfrost** [comment]
As Rick points out, I have changed the bubble sizes by adding a column to the csv. If you do not want the cumulative count in the csv, we can just make a separate view to provide data to the bubble chart.

**Comment by kdionisio** [comment]
@debboutr yeah, let's keep both the cumulative product count and the product count in the csv, that info is helpful. Thanks!
