### ISSUE TITLE
link chemical landing page to data document page

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#870]
As a Factotum user
I would like to be able to link to a summary page about the chemical from the data document page
So that I can see overview information about a chemical

Chemical landing page was created in #815

Definition of Done:
True chemical name present in the extracted chemical record boxes (center of page) on the data document page should be a hyperlink to the appropriate chemical landing page created in #815

**Comment by mwfrost** [comment]
@debboutr Did you already solve this ticket in your changes to the data document detail page?
