### ISSUE TITLE
data document page redesign

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#879]
As the product owner
I would like to redesign the look and feel of the data document page
To improve the usability of the application, efficiency of use of space on each page, and ease of navigating a data document record.

Definition of Done:
Redesign layout of data document page for CO group type per the mock-up below, and to include the following specifications:
1. Change Bootstrap to a full page layout (as opposed to the current middle layout with whitespace on the sides.)

2. Use bootstrap color scheme

3. Data document title (dashboard_datadocument.title) at top of page, with sub-title (dashboard_datadocument.subtitle) beneath in smaller font (see mock-up; if sub-title is null, nothing appears on page)

4. Upper right hand corner of page should include icons as detailed below
    - url icon (links to url in dashboard_datadocument.url field; if field is empty/null url icon does not appear on page)
    - GitHub icon (links to download script url identified by dashboard_datagroup.download_script_id; if field is empty/null then icon does not appear on page)
    - pdf/txt icon (opens data document file, icon should be specific to file type)
    - trash can icon (deletes data document file and all associated data; user should be prompted to confirm delete)

5. Menu bar on left side of page, in the following order:
   - Meta data section
      - pencil icon, which links to modal window allowing for editing of data document title, sub-title, data document type, data document notes, and data document url (same functionality as current pencil icon on data document page)
      - Data source title (without label); should appear as hyperlink bringing user to data source page
      - Data group name (without label); should appear as hyperlink bringing user to data group page
      - Data group type and Data document type, written as 'Data group type: Data document type' **Note this is different layout than in mock-up
    - empty line
    - Data document notes (dashboard_datadocument.note)
   - horizontal line separator
   - Products section
       - 'Products' title
       - Button to create a new product linked to the data document
       - List of products linked to the data document. Should see the dashboard_product.title as a hyperlink to the product page.
     - horizontal line separator
   - Extracted text section
          - 'Extracted Text' title
         - pencil icon linking to modal window allowing for edits to the dashboard_extractedtext.prod_name, doc_date, and rev_num fields (same functionality as pencil icon in extracted text box on current data document page)
        - Github icon linking to extraction script url
        - Document date
        - Revision number
        - QA approved: Yes/No, with 'QA' button to link to QA page (same as on current data doc page)

6. Menu bar on right side of page; designed as 'quick jump/navigation' menu to bring you to a chemical of choice in the center of the page
    - Menu bar should include raw name of chemical (dashboard_rawchem.raw_chem_name) as hyperlink
    - underneath chemical name should see dashboard_rawchem.raw_cas

7. 'Scrolling' middle of page with box for each extracted chemical child record. Maintain current editing functionality of extracted chemical records with a 'save composition edits' button.
    - see mock-up - true chemical name (if assigned), raw chemical name, true cas (if assigned), raw cas should appear in upper left of box in that order
    - DTXSID (if assigned) should appear in upper right corner of box
    - true cas/name and DTXSID should appear in a different color scheme, shading level, etc. compared to the raw cas/name, to distinguish easily between the two different data types
    - label 'Raw composition' should appear below chemicals
    - beneath label, the raw min comp, raw central comp, raw max comp, and unit type fields should appear in one row, in that order
    - beneath these fields the ingredient rank, reported functional use, and weight fraction type fields should appear in one row in that order

**Comment by dmlyons2** [comment]
![DD001](https://user-images.githubusercontent.com/1336349/57777310-3fb72180-76e7-11e9-9cbd-49d530b0500c.png)

**Comment by mwfrost** [comment]
When we start designing this page, we should test it with the most rawchem-heavy records. If the right side navigation bar is sticky and does not have its own scroll chute, we risk running out of vertical space and leaving records in the right column that the user cannot reach.
```
select rc.extracted_text_id, count(rc.id) from dashboard_rawchem rc group by extracted_text_id
ORDER BY count(rc.id) desc;
```

**Comment by debboutr** [comment]
**1. Change Bootstrap to a full page layout (as opposed to the current middle layout with whitespace on the sides.)**

@dmlyons2 this will require overriding the `.container` that we have in `base.html` which is currently capping the width
```
.container {
    max-width: 1140px;
}
```
this is simple enough to override into every page which doesn't appear to be problematic with any view, but if we just want it in this new ddoc detail view I'll have to think of something different so it only gets implemented here. here's the diff on the index page:
![wide](https://user-images.githubusercontent.com/7052993/58638915-b8eb7280-82aa-11e9-8aec-96fa56509a65.png)
**>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>VS.<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<**
![narrow](https://user-images.githubusercontent.com/7052993/58638930-c1dc4400-82aa-11e9-979b-29d2b6acc0f0.png)

**Comment by dmlyons2** [comment]
@debboutr Let's go with it on all views - We can go back and fix any problems this causes with another ticket. Instead of overriding, you can just code it into base.html container 100%

**Comment by debboutr** [comment]
What are the fields that we will want to have in the scrollspy / on top of each card for the group type of HabitsNPractices? here is the chemical card layout for all other group types which have chem_name and CAS:
**![cannabidiol](https://user-images.githubusercontent.com/7052993/58887690-ef563280-869a-11e9-980b-8b96ad125503.png)**
**_but for HnP cards I'm not sure what to display??? in the card or on the scrollspy link_**
![habits](https://user-images.githubusercontent.com/7052993/58887762-0dbc2e00-869b-11e9-8428-4af0069fbacb.png)

there is also the hanging `SU` supplemental document group type that will get docs that we don't yet have any in seed data to deal with that could cause an issue here, but not sure

**Comment by kdionisio** [comment]
to follow up on discussion yesterday, for Habits and Practices group type, display a default for now - this ticket was only intended to cover the CO group type.
