### ISSUE TITLE
Change icon set

### ISSUE THREAD

**Issue by dmlyons2** [HumanExposure/factotum#888]
## Describe the ideal solution or feature request
We have outgrown our current icon set Open Iconic and need to replace with an icon set that offers more icons. This ticket replaces Open Iconic with the free version of [Font Awesome](https://fontawesome.com). 

## Difficulty, impact, and usage score
| Technical difficulty | User goals | Usage frequency |
|--------------------| --------------------| --------------------|
| small |  Needed for new changes for DD page | daily |

## Who asked for this?
@dmlyons2 

## Definition of Done
Remove Open Iconic and Replace with Font Awesome. 

## What is the test(s)
No test needed.

**Comment by mwfrost** [comment]
Ticket #813 is going to bring in some new Open Iconic references that need to be accounted for on this branch. Please wait until 813 has been merged into dev before approving and moving this.
