### ISSUE TITLE
tool tips for attributes on product page

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#898]
As a Factotum user,
I want to easily be able to view the definition of each attribute on the product  page
So that I can easily understand the meaning of the attribute so that I know if it is appropriate to assign to the product I am currently viewing

Definition of Done:
For the product page add tool tips which display the definition of the attributes (both for allowed and assumed attributes)

**Comment by debboutr** [comment]
@kdionisio do you want these definitions to appear on the PUC detail page as well `/puc/1/` ???
