### ISSUE TITLE
change associated extraction script

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#908]
As the Factotum product owner
I want to change the extraction script associated with two data documents
So that I can correct a mistake made on data loading

Definition of Done:
The following two data documents:
http://factotum.epa.gov/datadocument/1372609/
http://factotum.epa.gov/datadocument/1372610/

should be associated with extraction script:
dashboard_script.title = Manual (dummy)
dashboard_script.id=14
dashboard_script.script_type=EX

 rather than the extraction script they are currently associated with.

**Comment by debboutr** [comment]
are you asking just for a migration to properly associate these 2 ~~DataDocuments~~ ExtractedTexts with script.id=14? Or do you want the ability to do it in the admin panel so you can do it yourself?

**Comment by kdionisio** [comment]
@debboutr Just the migration is fine, thanks!!
