### ISSUE TITLE
export records to CSV not working

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#909]
The 'Export all records to CSV' button on the data group page appears to not be working for some data groups, including http://factotum.epa.gov/datagroup/410/

Error seen is:
ValidationError at /datagroup/docs_csv/410/
['the only accepted file extension is .csv']

Definition of Done:
Export all records to CSV button produces CSV download rather than an error.

**Comment by kdionisio** [comment]
Bug seems to no longer be present, potentially fixed inadvertently in a different recent ticket.

**Comment by zachmunzenrider** [comment]
I believe that I addressed this in an earlier ticket by
