### ISSUE TITLE
exit button on QA page

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#927]
Exit button on QA page (http://factotum.epa.gov/qa/extractedtext/1373516/) gives a 'Page not found (404) error.

Definition of Done:
Exit button on QA page for CP data group type brings you back to the QA data group list page (http://factotum.epa.gov/qa/chemicalpresencegroup/404/) for that data group.

**Comment by michael-barbour** [comment]
So I can't find an "exit" button.  Can you confirm this QA button is the exit button.  It seems like it leads to a 404 every time (http://factotum.epa.gov/qa/).

![qa_breadcrumb_button](https://user-images.githubusercontent.com/22226925/69096696-e8da2e00-0a22-11ea-98b8-f79d1956cd04.png)

**Comment by kdionisio** [comment]
@michael-barbour  Yes it looks like you are right - the exit button no longer gives an error. Just getting the exit button to redirect to the link indicated in the ticket would be great. Thanks!
