### ISSUE TITLE
unsuccesful upload of curated chemicals

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#942]
In attempting to 'Upload curated chemicals' csv on this page: http://factotum.epa.gov/chemical_curation/, the upload appears to not be successful. No error message is seen, however the number of chemicals remaining to curate does not go down (which it should have if the upload were successful).

*Note, this is only the second curated chemical list from group type 'CP' which I have attempted to upload.

Definition of Done:
Identify error causing unsuccessful upload of curated chemical list.
*File being used in upload (Factotum_30) available upon request.

**Comment by mwfrost** [comment]
What is the source for the number of chemicals remaining to curate? Is it the dropdown menu?

**Comment by kdionisio** [comment]
It is the statistic displayed on this page: http://factotum.epa.gov/chemical_curation/

**Comment by kdionisio** [comment]
This bug was resolved after pushing the Owlfly sprint.
