### ISSUE TITLE
consistent color scheme on bubble plots

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#946]
As a Factotum product owner
I would like to see consistent colors used in bubble plots for each dashboard_puc.gen_cat
So that users can easily compare plots

Definition of Done:
Currently PUC bubble plots on http://factotum.epa.gov/ and on chemical landing page created in #815 assign default colors to the dashboard_puc.gen_cat field (resulting in inconsistent color assignment between the two plots). Fix colors such that each dashboard_puc.gen_cat uses the same color on both bubble plots.

**Comment by debboutr** [comment]
this got done on @mcovalt 's #867 branch

**Comment by kdionisio** [comment]
completed assuming that new gen cats are not added
