### ISSUE TITLE
'too many fields sent' error

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#970]
When manually entering new chemicals on: http://factotum.epa.gov/datadocument/1363503/

following error was seen:
Too many fields sent 
The number of get/post parameters exceeded settings.data_upload_max_number fields

Definition of done:
Ability to manually enter additional chemicals on above page
(Note: Reduce the amount of form fields set by removing the form set from the data document detail view)

**Comment by debboutr** [comment]
@kdionisio just to be clear here, the implementation of removing the formset from this detail view will create an add/edit view for chemical forms individually in a similar way that you see happening when you click on the edit button for the datadocument up in the top right of this view, the user will be sent to a page to add/edit a chemical and will then return to this detail view. So in your definition of done, the 

> Ability to manually enter additional chemicals on above page

will technically be done on another page, but will be accessible from this one. Hope this makes sense.
