### ISSUE TITLE
error when deleting chemical records on data document page

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#971]
When attempting to delete an individual chemical record on a data document page (http://factotum.epa.gov/datadocument/1373717/#chem-1563034), it appears that the chemical record is not deleted (it still remains in the center display, but changes position in the list). In addition, the list of chemicals in the right hand scroll bar appears to duplicate itself each time the user attempts to delete a chemical record.

(To reproduce the error, attempt to delete an individual chemical record on the data document page; issue was occurring on a page with approx 25 chemical records but did not appear on a page with approx 10 chemical records)

Definition of Done:
appropriately delete an individual chemical record when from data document page using red trash can icon

**Comment by mwfrost** [comment]
Whoever takes this ticket, please check to see if the error occurs on the QA page as well.

**Comment by debboutr** [comment]
I wasn't able to reproduce this error on `dev` or on `prod`. I did however have to disable the cache and refresh when on `prod` to get the page to show up as it should

**Comment by kdionisio** [comment]
Hmmm thanks @debboutr . Let's put a hold on this one until I can test more on prod/with students to see if this is another cache/refresh issue.

**Comment by kdionisio** [comment]
Confirming that clearing the cache solved this bug for our SSC. Thus no code changes are needed.
