### ISSUE TITLE
products not connected to data documents

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#991]
It was discovered that there are 1888 products on prod that are not connected to a data document. Suspect there may be an issue where a cascading delete is needed but is not implemented.

Query to use on prod to see 1888 products which are not connected to a data document:
```SQL
SELECT * FROM prod_factotum.dashboard_product  
WHERE dashboard_product.id NOT IN  
  (SELECT product_id FROM prod_factotum.dashboard_productdocument)
```
Definition of Done:
- In the future, if a data document is deleted, all associated product records must be deleted
- Fix logic in application which is allowing a product to exist without being linked to a data document

**Comment by mwfrost** [comment]
These orphaned products may have been caused by the relationship described in #1019
