### ISSUE TITLE
incorrect text in tool tip

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#995]
On the http://factotum.epa.gov/datadocument/1372072/ page, the dashboard_datadocument.subtitle is displayed at the top of the page, beneath the dashboard_datadocument.title.

The dashboard_datadocument.subtitle has an ellipsis if the subtitle is too long to be displayed on the page. There is a tool tip when you hover over the subtitle which is supposed to display the full dashboard_datadocument.subtitle. Instead, the tool tip displays the full dashboard_datadocument.title

Definition of Done:
Tool tip displayed when the dashboard_datadocument.subtitle has an ellipsis should display the full dashboard_datadocument.subtitle

**Comment by mwfrost** [comment]
Please add a test that would have caught this.
